export default {
    'account.accountInfo': 'Accountbeheer',
    'account.account': 'Account',
    'account.username': 'Gebruikersnaam',
    'account.resetPswd': 'Wachtwoord resetten',
    'account.resetPswdTip1':
        'Na het resetten van het wachtwoord zal dit account automatisch worden uitgelogd.',
    'account.resetPswdTip2':
        'Let op: Als u andere Gebruikerscentrumproducten hebt gebruikt, wordt het wachtwoord synchroon bijgewerkt.',
    'account.pswdManagement': 'Wachtwoordbeheer',
    'account.password': 'Wachtwoord',
    'account.remoteLock': 'Wachtwoord voor {type} vergrendeling',
    'account.password.remoteLock.desc':'Voer het wachtwoord in om het apparaat uit te schrijven.',
    'account.remoteLockDesc':
        'Vergrendel {type} in Instellingen. Voer het wachtwoord in om te ontgrendelen.',
    'account.deviceSettingLock': 'Apparaatinstelling vergrendeld',
    'account.deviceSettingLockDesc':
        'Vergrendel Instellingen in het apparaat. Voer het wachtwoord in om het te ontgrendelen.',
    'account.screenLock': 'Wachtwoord voor schermvergrendeling',
    'account.screenLockDesc':
        'Vergrendel het apparaatscherm een bepaalde periode. Voer het wachtwoord in om te ontgrendelen.',
    'account.school': 'Organisatie',
    'account.schoolName': 'Organisatienaam',
    'account.state': 'Status',
    'account.admin': 'Admin manager',
    'account.email': 'E-mail',
    'account.schoolCode': 'Organisatiecode',
    'account.serverManagement': 'WOL-server',
    'account.serverName': 'Servernaam',
    'account.powerState': 'Server Status',
    'account.connectNum': 'Verbonden nr.',
    'account.delete': 'Verwijderen',
    'account.deleteServer': 'Server verwijderen',
    'account.delServerTip': 'Wilt u {serverName} verwijderen uit {unitName}?',
    'account.delServerSuc': 'Server {serverName} verwijderd uit {unitName}.',
    'account.serverOff': 'Niet beschikbaar',
    'account.serverOn': 'Beschikbaar',
    'account.about': 'Over',
    'account.legalInfo': 'Wettelijke informatie',
    'account.userExpPlan': 'Gebruikers ervaringsplan',
    'account.userExpPlan1': 'Gebruikers ervaringsplan>',
    'account.OK': 'OK',
    'account.accept': 'Accepteren',
    'account.quit': 'Afsluiten',
    'account.userArgeement': 'Gebruikersovereenkomst >',
    'account.privacyPolicy': 'Privacy-beleid >',
    'account.openLicense': 'Opensource-licentie >',
    'account.pleaseEnterPswd': 'Voer uw wachtwoord in.',
    'account.pswdLen6': 'Wachtwoorden moeten uit 6 tekens bestaan.',
    'account.pswdOnlyNumber': 'Sorry, alleen cijfers (0-9) zijn toegestaan.',
    'account.userNameValidateInfo':
        'Sorry, alleen letters (a-z), cijfers(0-9) en tekens (@,_) zijn toegestaan.',
    'account.logout': 'Uitloggen',
    'account.userName': 'Gebruikersnaam',
    'account.edit': 'Bewerken',
    'account.pswd': 'Wachtwoord',
    'account.reset': 'Resetten',
    'account.location': 'Locatie',
    'account.adminUserName': 'Admin',
    'account.adminAccount': 'Admin-account',
    'account.schoolInfoMod': 'Wijziging organisatie-informatie',
    'account.deleteConfirm': 'Wilt u {account} verwijderen uit {unitName} ?',
    'account.anEmailWillSent': 'Er wordt een e-mail verzonden naar {account}.',
    'account.serverManagement.hint':
        'Wake-on-LAN (WoL) is een Ethernet- of Token Ring-computernetwerkstandaard waarmee een computer kan worden ingeschakeld of gewekt door een netwerkbericht.',
    'account.notConnectHint': '{num} apparaten die niet zijn verbonden met een server',
    'account.connectedDeivces': 'Verbonden apparaten',
    'account.two.factor.authentication': '2-Factor Authenticatie',
    'account.2FATip':
        'Als tweefactorauthenticatie is ingeschakeld, moet u een verificatiecode opgeven om in te loggen op Bytello DMS',
    'account.error.twoFA.isEmpty': 'Voer een 6-cijferige verificatiecode in',
    'account.Authenticate.password.title': 'Verifieer om door te gaan',
    'account.disable.2FA.title': '2-Factor Authenticatie uitschakelen',
    'account.Authenticate.password.label': 'Voer uw accountwachtwoord in',
    'account.Authenticate.password.confirm': 'Authenticeren',
    'account.enable.2FA.title': '2-Factor Authenticatie inschakelen',
    'account.Authenticate.tip':
        'Schakel 2-factor-authenticatie in om ervoor te zorgen dat uw account beter beveiligd is. Installeer Google Authenticator of Microsoft Authenticator',
    'account.Authenticate.ScanCode.title': '1 / Scan deze OF-code met je verificatie-app',
    'account.Authenticate.ScanCode.cannotScan': 'Kunt u deze OF-code niet scannen?',
    'account.Authenticate.code.text.title': 'Voer deze code in voor de authenticator-app:',
    'account.Authenticate.input.title':
        '2 / Voer een 6-cijferige verificatiecode in vanuit uw verificatie-app',
    'account.error.faInvalid': 'Ongeldige verificatie code',
    'account.Authenticate.2fa.enable': 'Inschakelen',
    'account.success.enable.fa': 'Activeer 2-Factor Authentication succesvol',
    'account.success.disable.fa': '2-Factor Authenticatie uitgeschakeld',
    'account.disable.2FA': 'Schakel 2FA uit',
};
