export default {
    'cmdRecords.execHistory.recallSent': 'Terugroepopdracht verzonden.',
    'cmdRecords.execHistory.unableSent': 'Kan niet verzenden.',
    'cmdRecords.execHistory.unlockSent': 'Deblokkeeropdracht verzonden.',
    'cmdRecords.execHistory.cmdSent': 'Opdracht verzonden',
    'cmdRecords.cmdInSchedule.timed': 'Getimed',
    'cmdRecords.cmdInSchedule.recurring': 'Terugkerend',
    'cmdRecords.updateTime': 'Tijd bijwerken',
    'cmdRecords.cmdName': 'Opdrachtnaam',
    'cmdRecords.cmdOwner': 'Opdrachteigenaar',
    'cmdRecords.timeMode': 'Tijdmodus',
    'cmdRecords.devices': 'Apparaten',
    'cmdRecords.cmdStatus': 'Opdrachtstatus',
    'cmdRecords.details': 'Details',
    'cmdRecords.executed': 'Uitgevoerd',
    'cmdRecords.unexecuted': 'Niet uitgevoerd',
    'cmdRecords.recalled': 'Teruggeroepen',
    'cmdRecords.deviceCmdExecTable.settingFailed': 'Instellen mislukt',
    'cmdRecords.deviceCmdExecTable.systemError': 'Systeemfout',
    'cmdRecords.deviceCmdExecTable.unknownError': 'Onbekende fout',
    'cmdRecords.deviceCmdExecTable.resetFail': 'Resetten mislukt',
    'cmdRecords.deviceCmdExecTable.downloadError': 'Downloadfout',
    'cmdRecords.deviceCmdExecTable.rejectByUser': 'Afgewezen door gebruiker',
    'cmdRecords.deviceCmdExecTable.notImplemented': 'Functie niet geïmplementeerd',
    'cmdRecords.deviceCmdExecTable.cmdCovered': 'Opdracht verborgen ',
    'cmdRecords.deviceCmdExecTable.notSupport': 'Niet ondersteund door Android',
    'cmdRecords.deviceCmdExecTable.unsupportResetWallpaper':
        'Resetten van de achtergrond wordt niet ondersteund',
    'cmdRecords.deviceCmdExecTable.alreadyExists': 'Bestaat al',
    'cmdRecords.deviceCmdExecTable.installConflict': 'Installeer conflict',
    'cmdRecords.deviceCmdExecTable.versionTooOld': 'Versie is te oud',
    'cmdRecords.deviceCmdExecTable.insufficientStorage': 'Onvoldoende opslagruimte',
    'cmdRecords.deviceCmdExecTable.formatNotSupport': 'Dit formaat wordt niet ondersteund',
    'cmdRecords.deviceCmdExecTable.userRestricted': 'Gebruiker beperkt',
    'cmdRecords.deviceCmdExecTable.installError': 'Installatiefout',
    'cmdRecords.deviceCmdExecTable.channelNameEmpty': 'Kanaalnaam leeg',
    'cmdRecords.deviceCmdExecTable.nonExist': 'Niet-bestaand',
    'cmdRecords.deviceCmdExecTable.switchFailed': 'Overschakelen mislukt',
    'cmdRecords.deviceCmdExecTable.timeout': 'time-out',
    'cmdRecords.deviceCmdExecTable.deviceIsOff': 'Apparaat staat uit',
    'cmdRecords.deviceCmdExecTable.deviceNotExists': 'Apparaat bestaat niet',
    'cmdRecords.deviceCmdExecTable.virtualDeviceNotSupport':
        'Een virtueel apparaat wordt niet ondersteund',
    'cmdRecords.deviceCmdExecTable.wolNotEnabled':'WOL niet ingeschakeld',
    'cmdRecords.deviceCmdExecTable.withdrawal': 'Intrekking',
    'cmdRecords.deviceCmdExecTable.waitForExecute': 'wacht op uitvoering',
    'cmdRecords.deviceCmdExecTable.deviceUnbound': 'Apparaat niet verbonden',
    'cmdRecords.deviceCmdExecTable.expired': 'verlopen',
    'cmdRecords.deviceCmdExecTable.noBinding': 'Geen verbinding',
    'cmdRecords.deviceCmdExecTable.wakeServerNotExists': 'Wake server bestaat niet',
    'cmdRecords.deviceCmdExecTable.wakeServerIsOff': 'Wake server staat uit',
    'cmdRecords.deviceCmdExecTable.cmdNotSupported': 'Opdracht niet ondersteund',
    'cmdRecords.deviceCmdExecTable.unlocked': 'Ontgrendeld',
    'cmdRecords.deviceCmdExecTable.reset': 'Resetten',
    'cmdRecords.deviceCmdExecTable.ok': 'OK',
    'cmdRecords.deviceCmdExecTable.deviceName': 'Apparaatnaam',
    'cmdRecords.deviceCmdExecTable.execTime': 'Uitvoeringstijd',
    'cmdRecords.deviceCmdExecTable.execResults': 'Uitvoeringsresultaten',
    'cmdRecords.deviceCmdExecTable.loading': 'Bezig met laden...',
    'cmdRecords.deviceCmdExecTable.resend': 'Opnieuw verzenden',
    'cmdRecords.deviceCmdExecTable.unlock': 'Ontgrendelen',
    'cmdRecords.deviceCmdExecTable.recall': 'Terugroepen',
    'cmdRecords.deviceCmdExecTable.wait': 'wachten',
    'cmdRecords.deviceCmdExecTable.pending': 'in afwachting van',
    'cmdRecords.deviceCmdExecTable.recalled': 'teruggeroepen',
    'cmdRecords.deviceCmdExecTable.covered': 'verborgen',
    'cmdRecords.deviceCmdExecTable.success': 'succes',
    'cmdRecords.deviceCmdExecTable.failed': 'mislukt',
    'cmdRecords.recordDetailDrawer.bells': 'Signalen',
    'cmdRecords.recordDetailDrawer.text': 'Tekst',
    'cmdRecords.recordDetailDrawer.media': 'Media',
    'cmdRecords.recordDetailDrawer.file': 'Bestand',
    'cmdRecords.recordDetailDrawer.soundMode': 'Geluidsmodus',
    'cmdRecords.recordDetailDrawer.imageMode': 'Afbeeldingsmodus',
    'cmdRecords.recordDetailDrawer.androidState': 'Android status',
    'cmdRecords.recordDetailDrawer.wallpaper': 'Achtergrond',
    'cmdRecords.recordDetailDrawer.logo': 'Logo',
    'cmdRecords.recordDetailDrawer.detail': 'Detail',
    'cmdRecords.recordDetailDrawer.switchTo': 'Overschakelen naar',
    'cmdRecords.recordDetailDrawer.cmdOwner': 'Opdrachteigenaar:',
    'cmdRecords.recordDetailDrawer.deviceNo': 'Apparaatnr:',
    'cmdRecords.recordDetailDrawer.devices': 'apparaten',
    'cmdRecords.recordDetailDrawer.timeMode': 'Tijdmodus:',
    'cmdRecords.recordDetailDrawer.cmdSetTime': 'Opdrachttijd instellen:',
    'cmdRecords.recordDetailDrawer.unlockAllTip': 'Alle door mij bestuurde apparaten ontgrendelen',
    'cmdRecords.recordDetailDrawer.unlockAll': 'Alles ontgrendelen',
    'cmdRecords.recordDetailDrawer.seeRecurring': 'Zie terugkerend',
    'cmdRecords.recordDetailDrawer.recallAllTip': 'Roep alle door mij bestuurde apparaten terug',
    'cmdRecords.recordDetailDrawer.recallAll': 'Alles terugroepen',
    'cmdRecords.recordDetailDrawer.isNotManageTip':
        '{val1} apparaten niet door mij bestuurd, inclusief {val2} uitgevoerd',
    'cmdRecords.recordDetailDrawer.isManageTip': '{val1} apparaten niet door mij bestuurd',
    'cmdRecords.tableFilter.selectCmdName': 'Selecteer opdrachtnaam',
    'cmdRecords.tableFilter.selectTimeMode': 'Selecteer tijdmodus',
    'cmdRecords.tableFilter.selectCmdStatus': 'Selecteer opdrachtstatus',
    'cmdRecords.recurringTable.fold': 'Vouwen',
    'cmdRecords.recurringTable.expand': 'Uitbreiden',
    'cmdRecords.recurringTable.edit': 'Bewerken',
    'cmdRecords.recurringTable.sunday': 'Zo.',
    'cmdRecords.recurringTable.monday': 'Ma.',
    'cmdRecords.recurringTable.tuesday': 'Di.',
    'cmdRecords.recurringTable.wednesday': 'Wo.',
    'cmdRecords.recurringTable.thursday': 'Do.',
    'cmdRecords.recurringTable.friday': 'Vrij.',
    'cmdRecords.recurringTable.saturday': 'Za.',
    'cmdRecords.recurringTable.deleteCommand': 'Opdracht verwijderen',
    'cmdRecords.recurringTable.areYouSureDelCommand':
        'Weet u zeker dat u deze opdracht wilt verwijderen?',
    'cmdRecords.recurringTable.statusChangeSuc': 'Status gewijzigd',
    'cmdRecords.recurringTable.statusChangeFail': 'Kan niet veranderen',
    'cmdRecords.tableFilter.today': 'Vandaag',
    'cmdRecords.tableFilter.dayRange': '{val1} {val2} dagen',
    'cmdRecords.recordDetailDrawer.updateVersion': 'Versie bijwerken',
    'cmdRecords.recordDetailDrawer.livechannel': 'Kanaalnaam',
    'cmdRecords.deviceCmdExecTable.notsupport': 'OS wordt niet ondersteund',

    'cmdRecords.search.owner': 'Zoekopdracht eigenaar e-mail',
    'cmdRecords.deviceCmdExecTable.uninstall': 'App bestaat niet',
    'cmdRecords.send.failed': 'verzendopdracht mislukt',
};
