export default {
    'commandModal.pleaseSelectABell': 'Selecteer een signaal.',
    'commandModal.bellList': 'Signalenlijst',
    'commandModal.bellName': 'Signaalnaam',
    'commandModal.size': 'Grootte',
    'commandModal.time': 'Tijd',
    'commandModal.pleaseUploadABell': 'Upload een geluid ',
    'commandModal.fileSize10M': 'Bestand mag niet groter zijn dan 10MB',
    'commandModal.bellFormat': 'Bestandsformaat moet MP3, WAV, AAC of OGG zijn',
    'commandModal.selectUpto': 'Selecteer tot {val1} per keer.',
    'commandModal.reachedMaxLimit': 'De maximale grenswaarde is bereikt.',
    'commandModal.fileNotSupport': 'Het huidige bestandsformaat ondersteunt geen voorbeeldvenster.',
    'commandModal.youHaveSelected': 'U hebt dit bestand geselecteerd.',
    'commandModal.sureDelete': 'Weet u zeker dat u wilt verwijderen?',
    'commandModal.deleteFile': 'Bestand verwijderen?',
    'commandModal.bellForamtHint': 'Formaat: MP3, WAV, AAC, OGG',
    'commandModal.bellSize': 'Grootte: max. 10MB',
    'commandModal.playWhole': 'Volledig afspelen',
    'commandModal.setAtLeastOneCycle': 'Stel ten minste één cyclus in',
    'commandModal.lockDuration': 'Vergrendelingsduur',
    'commandModal.now': 'Nu',
    'commandModal.selectATimePeriod': 'Selecteer een tijdsperiode',
    'commandModal.timeExpired': 'Tijd verlopen',
    'commandModal.endTimeCannotEarlier': 'De eindtijd kan niet voor de begintijd liggen',
    'commandModal.timeCannotRepeat': 'Tijd mag maar een keer voorkomen',
    'commandModal.periodNotRepeat': 'De tijdsperiode mag maar een keer voorkomen',
    'commandModal.selectMutimedia': 'Selecteer een multimediabestand.',
    'commandModal.upTo50Uploads': 'Tot 50 uploads',
    'commandModal.annFileFormat': 'Formaat: MP4, AVI, JPG, PNG',
    'commandModal.annFileSize': 'Grootte: max. 200MB',
    'commandModal.annTitle': 'Multimedia',
    'commandModal.selectAMutimedia': 'Selecteer een multimediabestand',
    'commandModal.pleaseUploadAMutim': 'Upload een multimediabestand',
    'commandModal.preiew': 'Voorbeeldvenster',
    'commandModal.deviceWillPlayAuto': '(Het apparaat speelt automatisch af tijdens het uitvoeren)',
    'commandModal.mutimediaList': 'Multimedialijst',
    'commandModal.fileMultFormat': 'Bestandsformaat moet MP4, AVI, JPG of PNG zijn',
    'commandModal.fileMultSizeLimit': 'Bestand mag niet groter zijn dan 200MB',
    'commandModal.wallpaperFormat': 'Bestandsformaat moet JPG zijn',
    'commandModal.pleaseUploadA': 'Upload a.u.b. {val1}',
    'commandModal.wallTitle': 'Achtergrond',
    'commandModal.logoTitle': 'Logo',
    'commandModal.soundModeStandard': 'Standaard',
    'commandModal.soundModeClassroom': 'Klaslokaal',
    'commandModal.soundModeMetting': 'Vergadering',
    'commandModal.soundModeCustom': 'Aangepast',
    'commandModal.imageModeStandard': 'Standaard',
    'commandModal.imageModeBright': 'Heldere modus',
    'commandModal.imageModeSoft': 'Soft',
    'commandModal.imageModeCustom': 'Aangepast',
    'commandModal.switchAnd': 'Overschakelen naar Android inschakelen',
    'commandModal.allowToSwitch': 'Toestaan dat apparaten overschakelen op Android-kanalen.',
    'commandModal.NoSignalTimeNever': 'Nooit',
    'commandModal.NoSignalTime1min': '1 min.',
    'commandModal.NoSignalTime3min': '3 min.',
    'commandModal.NoSignalTime5min': '5 min.',
    'commandModal.NoSignalTime10min': '10 min.',
    'commandModal.NoSignalTime30min': '30 min.',
    'commandModal.NoSignalTime45min': '45 min.',
    'commandModal.NoSignalTime60hour': '60 min.',
    'commandModal.NoSignalTime90hour': '90 min.',
    'commandModal.NoSignalTime120hour': '120 min.',
    'commandModal.remainPowerOff': 'Uitgeschakeld blijven',
    'commandModal.autoPowerOn': 'Automatische inschakeling',
    'commandModal.returnPowerState': 'Keer terug naar de stroomstatus voor de onderbreking',
    'commandModal.noSignalShutdown': 'Geen signaaluitschakeling',
    'commandModal.autoPowerOff': 'Automatische uitschakeling wanneer er geen signaal binnenkomt.',
    'commandModal.displayAfter': 'Weergave na stroomonderbreking',
    'commandModal.deviceDisplayReconn': 'Apparaat opnieuw verbonden na stroomonderbreking.',
    'commandModal.wallpaper': 'Achtergrond ',
    'commandModal.logo': 'logo',
    'commandModal.useDefault': 'Standaard gebruiken',
    'commandModal.wallpaperCustom': 'Aangepast',
    'commandModal.returnToDefault': '(Ga terug naar de standaard {val1} van de apparaten)',
    'commandModal.pleaseSelect': 'Selecteer a.u.b. {val1}.',
    'commandModal.pleaseUpload': 'Upload a.u.b. een {val1}',
    'commandModal.pleaseSelectOne': 'selecteer een',
    'commandModal.upTo20Uploads': 'Tot 20 uploads',
    'commandModal.wallSizeLimit': 'Grootte: max. 3MB (1920*1080)',
    'commandModal.list': 'lijst',
    'commandModal.selectedDevices': '{num} apparaten geselecteerd',
    'commandModal.filePublish.pleaseSelect': 'Selecteer eerst een bestand',
    'commandModal.filePublish.selectUpTo': 'Selecteer maximaal {val1} per keer.',
    'commandModal.filePublish.reachTheMaximum': 'De maximale grenswaarde bereikt.',
    'commandModal.filePublish.fileNameTooLong': 'Bestandsnaam is te lang',
    'commandModal.filePublish.fileSize200': 'Bestand mag niet groter zijn dan 200MB',
    'commandModal.filePublish.pleaseUpload': 'Upload een bestand',
    'commandModal.filePublish.selectAFile': 'Selecteer een bestand',
    'commandModal.filePublish.fileWillSave': '(Bestand wordt opgeslagen in Finder)',
    'commandModal.filePublish.multiTimeZoneSelected':
        'Opdrachten worden uitgevoerd volgens de lokale tijdzone van het apparaat (als meerdere tijdzones zijn geselecteerd).',
    'commandModal.filePublish.fileList': 'Bestandslijst',
    'commandModal.filePublish.fileName': 'Bestandsnaam',
    'commandModal.filePublish.format': 'Formaat',
    'commandModal.filePublish.fileSize': 'Grootte',
    'commandModal.filePublish.selected': 'U hebt dit bestand geselecteerd.',
    'commandModal.filePublish.deleteConfirmTip': 'Weet u zeker dat u wilt verwijderen?',
    'commandModal.filePublish.deleteConfirmTip1': 'Bestand verwijderen?',
    'commandModal.filePublish.delete': 'Verwijderen',
    'commandModal.filePublish.upToFilesUploads': 'Tot {val1} bestanden uploaden',
    'commandModal.notification.times1': '1 keer',
    'commandModal.notification.times3': '3 keer',
    'commandModal.notification.times5': '5 keer',
    'commandModal.notification.times10': '10 keer',
    'commandModal.notification.times20': '20 keer',
    'commandModal.notification.canNotEmpty': 'Invoer mag niet leeg zijn.',
    'commandModal.notification.text': 'Tekst',
    'commandModal.notification.preview': 'Voorbeeldvenster',
    'commandModal.notification.displayArea': 'Weergavegebied',
    'commandModal.notification.loopTimes': 'Herhaaltijd',
    'commandModal.announcement.displayArea': 'Weergavegebied',
    'commandModal.turnOnTheSwitch':
        'Zet de schakelaar aan om de tijd en terugkerende opdracht in te stellen.',
    'commandModal.setAsSchedule': 'Instellen als schema',
    'commandModal.setTime': 'Tijd instellen',
    'commandModal.offlineMode': 'Offline modus',
    'commandModal.offlineTooltip':
        'Met de offline modus kunnen apparaten opdrachten uitvoeren zonder internetverbinding.',
    'commandModal.timed': 'Getimed',
    'commandModal.timeTooltip':
        'Opdrachten worden uitgevoerd volgens de lokale tijdzone van het apparaat (als meerdere tijdzones zijn geselecteerd).',
    'commandModal.recurr': 'Terugkerend',
    'commandModal.recurrTooltip':
        'Er geldt slechts een enkele set van terugkerende opdrachten voor een apparaat. Nieuwe terugkerende opdrachten zullen de oude overschrijven.',
    'commandModal.selectATime': 'Selecteer een tijd.',
    'commandModal.only10times': 'Een cyclus kan slechts 10 keer worden ingesteld',
    'commandModal.addATime': 'Een tijd toevoegen',
    'commandModal.addARecurring': 'Toevoegen van terugkerend',
    'commandModal.multipleTimeZones':
        'Apparaten in meerdere tijdzones geselecteerd. Geef datum en tijd weer als UTC{val1}.',
    'commandModal.oneTimeZones':
        'Apparaat(en) in UTC{val1} geselecteerd. Geef datum en tijd weer als UTC{val2}.',
    'commandModal.loading': 'B E Z I G  M E T  L A D E N ',
    'commandModal.videoNotPlayed':
        'Wordt deze video niet goed afgespeeld? Download om te bekijken.',

    'commandModal.playmode': 'Speel modus',
    'commandModal.playmode.loop': 'Loop',
    'commandModal.playmode.duration': 'Duur afspelen',
    'commandModal.playmode.right': 'Operationele rechten',
    'commandModal.playmode.turnoff':
        'Zet de schakelaar uit om de gebruiker op elk moment het commando uit te zetten.',
    'commandModal.playmode.times': '{value} tijden',
    'commandModal.playmode.throughtout': 'Doorheen',
    'commandModal.playmode.min': '{value} minuut',
    'commandModal.powerOnHint':
        '{num} apparaten kunnen de Power on-opdracht niet uitvoeren vanwege de WOL-serverfout',
    'commandModal.blockList.allowList': 'Lijst toestaan',
    'commandModal.blockList.closeHint':
        'Sluit de bestaande witte lijst of blokkeerlijst op het apparaat',
    'commandModal.blockList.listManage': 'Lijst beheren',
    'commandModal.blockList.blockHint': `URL's die niet zijn toegestaan`,
    'commandModal.blockList.allowHint': `Specifieke URL's toegestaan`,
    'commandModal.blockList.URL': 'URL',
    'commandModal.blockList.enterURL': 'Voer een URL in',
    'commandModal.blockList.mustBeValidURL': 'Moet een geldige url zijn',
    'commandModal.blockList.URLExist': 'URL bestaat al',
    'commandModal.blockList.enterURLHere': 'Voer hier de URL in',
    'commandModal.blockList.listType': 'Lijsttype',
    'commandModal.blockList.list': 'Lijst',
    'commandModal.blockList.pleaseSelectAURL': 'Selecteer een URL',
    'commandModal.blockList.deleteUrl': 'URL verwijderen?',
    'commandModal.blockList.exist.url':'URL bestaat al'
};
