export default {
    'common.noData': 'Geen gegevens',
    'common.unknownError': 'Onbekende fout.',
    'common.agreementTitle': 'Bytello Gebruikersovereenkomst apparaatbeheersysteem',
    'common.policyTitle': 'Bytello Aapparaatbeheersysteem en Privacy-beleid',
    'common.quitExpPlanTitle':
        'Mededeling voor het stoppen van het [Bytello Apparaatbeheersysteem] Productgebruiker ervaringsplan',
    'common.userExpPlanTitle':
        'Bytello Apparaatbeheersysteem en het Productgebruiker ervaringsplan',
    'common.filter.clear': 'Wis filters',
    'common.filter.apply': 'Filters toepassen',
    'common.pleaseSelectDevice': 'Selecteer apparaten a.u.b!',
    'common.selectCmd': 'Selecteer Opdracht',
    'common.allTypes': 'Alle typen',
    'common.soundBar': 'Sound bar',
    'common.ifp': 'IFP',
    'common.paginationTotal': 'Totaal {val1} items',
    'common.paginationTotal20Page': '20 / pagina',
    'common.paginationTotal40Page': '40 / pagina',
    'common.paginationTotal80page': '80 / pagina',
    'common.executeNow': 'Nu uitvoeren',
    'common.recurring': 'Terugkerend',
    'common.timed': 'Getimed',
    'common.powerOn': 'Aanzetten',
    'common.powerOff': 'Uitzetten',
    'common.reboot': 'Opnieuw opstarten',
    'common.bells': 'Signalen',
    'common.screenLock': 'Schermvergrendeling',
    'common.blockList': 'Blokkeerlijst',
    'common.notification': 'Tekst',
    'common.announcement': 'Multimedia',
    'common.filePublish': 'verzenden',
    'common.liveChannel': 'Live-kanaal',
    'common.soundMode': 'Geluidsmodus',
    'common.imageMode': 'Afbeeldingsmodus',
    'common.powerState': 'Stroomstatus',
    'common.androidState': 'Android status',
    'common.wallpaper': 'Achtergrond',
    'common.logo': 'Opstart logo',
    'common.emergency': 'Waarschuwing',
    'common.softwareUpdate': 'Software-update',
    'common.applicationInstall': 'Applicatie installeren',
    'common.applicationUninstall': 'Applicatie verwijderen',
    'common.applicationAble': 'Applicatie (inschakelen / uitschakelen)',
    'common.inputSwitch': 'Ingangsschakelaar',
    'common.actions': 'Acties',
    'common.selectGroup': 'Selecteer groep',
    'common.deviceControl': 'Apparaatbesturing',
    'common.message': 'Bericht',
    'common.deviceSetting': 'Apparaatinstellingen',
    'common.allGroup': 'Alle groep',
};
