export default {
    'deviceDetail.all': 'Alle',
    'deviceDetail.unbindDevice': 'Apparaat uitschrijven',
    'deviceDetail.allDeviceDataErased': 'Alle apparaatgegevens worden gewist.',
    'deviceDetail.deviceWillUnbind':
        'Binding van apparaat {deviceName} aan { unitName } wordt ongedaan gemaakt.',
    'deviceDetail.unbind': 'Uitschrijven',
    'deviceDetail.noData': 'Geen gegevens',
    'deviceDetail.group': 'Groep: {val1}',
    'deviceDetail.deviceId': 'Apparaat-ID',
    'deviceDetail.model': 'Model',
    'deviceDetail.osVersion': 'OS-versie',
    'deviceDetail.operationOs': 'Besturingssysteem',
    'deviceDetail.processerCPU': 'CPU',
    'deviceDetail.touchFrame': 'Touch frame',
    'deviceDetail.DMSVersion': '{type} versie',
    'deviceDetail.devicesInCommands': 'Apparaat in geplande opdrachten',
    'deviceDetail.commands': 'Voer het bevel op schema',
    'deviceDetail.mode': 'Modus',
    'deviceDetail.commandOwner': 'Opdrachteigenaar',
    'deviceDetail.time': 'Tijd',
    'deviceDetail.ram': 'RAM',
    'deviceDetail.storage': 'Opslag',
    'deviceDetail.deviceInGroup': 'Apparaat in groepen',
    'deviceDetail.groupName': 'Groepsnaam',
    'deviceDetail.tags': 'Tags',
    'deviceDetail.selectAtag': 'Selecteer een tag of maak er een aan',
    'deviceDetail.add': 'Toevoegen',
    'deviceDetail.deviceName': 'Apparaatnaam',
    'deviceDetail.deviceNameIsNull': 'Voer a.u.b. apparaatnaam in',
    'deviceDetail.onlyLettersHint': 'Alleen letters, cijfers en de symbolen - + / zijn toegestaan.',
    'deviceDetail.tagIsNull': 'Voer een tag in',
    'deviceDetail.lettersNumberAllowed': 'Alleen letters en cijfers zijn toegestaan.',
    'deviceDetail.tagsExists': 'Tag bestaat',
    'deviceDetail.addNew': 'Toevoegen nieuwe',
    'deviceDetail.deviceInfomation': 'Apparaatinformatie',
    'deviceDetail.deviceDetails': 'Apparaatdetails',
    'deviceDetail.application.enable': 'Inschakelen',
    'deviceDetail.application.enableTip':
        'Na het inschakelen zijn de apps beschikbaar op apparaten waarop deze al is geïnstalleerd.',
    'deviceDetail.application.disable': 'Uitschakelen',
    'deviceDetail.application.disableTip':
        'Na het uitschakelen zijn de apps niet beschikbaar op apparaten waarop deze al is geïnstalleerd.',
    'deviceDetail.application.processing': 'Bezig met verwerken...',
    'deviceDetail.application.updateTip': 'De applicatie is niet beschikbaar tijdens de update.',
    'deviceDetail.application.update': 'Bijwerken',
    'deviceDetail.application.uninstall': 'Installatie ongedaan maken',
    'deviceDetail.application.uninstallTip': 'De apps worden van het apparaat verwijderd.',
    'deviceDetail.application.cmdSentWaitForExec':
        'Opdracht verzonden, wacht met uitvoeren tot het apparaat online is.',
    'deviceDetail.application.applicationManagement': 'Applicatiebeheer',
    'deviceDetail.application.refreshed': 'Vernieuwen',
    'deviceDetail.application.clickToRefresh': 'Klik om te verversen',
    'deviceDetail.application.thirdPartyApps': 'Apps van derden',
    'deviceDetail.application.nativeApps': 'Native apps',
    'deviceDetail.execTime': 'Uitvoeringstijd',
    'deviceDetail.deviceType': 'Apparaattype',
    'deviceDetail.SerialNo': 'Serienummer',
    'deviceDetail.useageDataForToday': 'Gebruiksgegevens van vandaag',
    'deviceDetail.deviceUseage': 'Gebruiksgegevens van het apparaat',
    'deviceDetail.appUseage': 'Gegevens over applicatiegebruik',
    'deviceDetail.timeOfUse': 'Teller applicatiegebruik',
    'deviceDetail.countTheTime': 'Tel het aantal keren dat elke Applicatie is gebruikt',
    'deviceDetail.useTime': 'Gebruikstijd applicatie ',
    'deviceDetail.countTheTotal': 'Tel van elke Applicatie de totale tijd op',
    'deviceDetail.bootTimes': 'Online frequentie',
    'deviceDetail.bootTime': 'Gebruikstijd van het apparaat',
    'deviceDetail.tab.basic': 'Basis',
    'deviceDetail.tab.commands': 'Opdrachten',
    'deviceDetail.tab.useage': 'Gegevens',
    'deviceDetail.tab.application': 'Apps',
    'deviceDetail.onlineTime': 'Online tijd',
    'deviceDetail.noAppHint': 'Hebt niet gebruikt',
    'deviceDetail.online': 'Online',
    'deviceDetail.offline': 'Offline',
    'deviceDetail.notify': 'Meld weergave in realtime',
    'deviceDetail.today': 'Vandaag',
    'deviceDetail.yesterday': 'Gisteren',
    'deviceDetail.last7': 'Laatste 7 dagen',
    'deviceDetail.last30': 'Laatste 30 dagen',
    'deviceDetail.onlineTrends': 'Online trends',
    'deviceDetail.tooltipTime': 'Tijd',
    'deviceDetail.activeDays': 'Actieve dagen',
    'deviceDetail.onlineRate': 'Online snelheid',
    'deviceDetail.networkInterface': 'Netwerkinterface',
    'deviceDetail.macAdress': 'Mac adres',
    'deviceDetail.IPAdress': 'IP adres',
    'deviceDetail.disconnected': 'Verbinding verbroken',
    'deviceDetail.Fold': 'Vouwen',
    'deviceDetail.Expand': 'Uitbreiden',
    'deviceDetail.application.disable.hide.slider':
        'Uitschakelen - Hulpmiddelen in de zijbalk verbergen',
    'deviceDetail.application.disable.show.slider':
        'Uitschakelen - Hulpmiddelen in de zijbalk weergeven',
};
