export default {
    'deviceList.ifpAll': 'IFP: Alle({val1})',
    'deviceList.soundbarAll': 'Sound bar: Alles({val1})',
    'deviceList.allTypeAll': 'Alle typen: Alle({val1})',

    'deviceList.deviceErased': 'Alle apparaatgegevens worden gewist.',
    'deviceList.unbindTip': 'Apparaat "{val1}" zal worden losgekoppeld van {val2}.',
    'deviceList.groupNameCannotEmpty': 'Groepsnaam mag niet leeg zijn',
    'deviceList.allDevices': 'Alle apparaten',
    'deviceList.groupNameExists': 'Apparaatgroep "Alle apparaten" bestaat al!',
    'deviceList.groupNameAlreadyExists': 'Apparaatgroep "{val1}" bestaat al!',
    'deviceList.deviceGroupCreated': 'Apparaatgroep aangemaakt',
    'deviceList.filter.searchDeviceName': 'Zoek apparaatnaam',
    'deviceList.filter.selectStatus': 'Selecteer status',
    'deviceList.filter.selectTimezone': 'Selecteer tijdzone',
    'deviceList.filter.selectTags': 'Selecteer tags',
    'deviceList.table.deviceName': 'Apparaatnaam',
    'deviceList.table.status': 'Status',
    'deviceList.table.tags': 'Tags',
    'deviceList.table.school': 'Organisatie',
    'deviceList.table.timezone': 'Tijdzone',
    'deviceList.table.nextCmd': 'Volgende opdracht',
    'deviceList.table.coAdmin': 'Mede-admin',
    'deviceList.table.details': 'Details',
    'deviceList.table.searchName': 'Zoeken {val1}',
    'deviceList.table.reset': 'Resetten',
    'deviceList.table.search': 'Zoeken',
    'deviceList.table.device': 'apparaat',
    'deviceList.group': 'Groep',
    'deviceList.hasTypeAll': '{val1}',
    'deviceList.tabel.all': 'Selecteer alles',
    'deviceList.tabel.list': 'Lijst',
    'deviceList.tabel.grid': 'Raster',
    'deviceList.select.group': 'Groep',
    "device.table.school": "School",
};
