export default {
    'menu.home': 'home',
    'menu.dashboard.dashboard': 'Dashboard',
    'menu.deviceManagement': 'Apparaten',
    'menu.deviceManagement.allTypes': 'Alle typen',
    'menu.deviceManagement.ifp': 'IFP',
    'menu.deviceManagement.soundBar': 'Sound bar',
    'menu.deviceManagement.ledWall': 'Led wall',
    'menu.functions': 'Geavanceerd',
    'menu.functions.profile': 'Profiel',
    'menu.functions.appManage': 'Toepassingen',
    'menu.functions.inputSwitch': 'Ingangsschakelaar',
    'menu.functions.firmwareUpdate': 'Firmware update',
    'menu.functions.softwareUpdate': 'Software bijwerken',
    'menu.commandRecords': 'Records',
    'menu.commandRecords.exeHistory': 'Geschiedenis',
    'menu.commandRecords.inSchedule': 'In schema',
    'menu.user.userManagement': 'Gebruikersbeheer',
    'menu.account.accountSettings': 'Accountinstellingen',
    'menu.systemManage': 'Systeem',
    'menu.systemManage.adminManage': 'Gebruikers',
    'menu.systemManage.schoolManage': 'Organisatie',
    'menu.systemManage.passwordManage': 'wachtwoord',
    'menu.systemManage.userSettings': 'Instellingen',
    'menu.resources.resources': 'Hulpbron',
    'global.error.network': 'netwerkfout',
    'global.network.timeout': 'time-out',
    'global.network.error': 'Internetfout',
    'global.btn.ok': 'OK',
    'upload.getUploadPolicyError': 'Uploaden mislukt',
    'upload.networkError': 'Uploaden mislukt',
    'upload.cancelled': 'Annuleer uploaden taak!',
    'upload.formatError': 'Fout bestandsformaat',
    'upload.fileNameError': 'bestandsnaam is te lang',
    'upload.parsing': 'Bezig met parseren...',
    'upload.fileExist': 'Bestand bestaat al',
    'upload.fileNameTooLong': 'Bestandsnaam is te lang',
    'upload.fileJPG': 'Bestandsformaat moet JPG zijn',
    'upload.file3M1920': 'Bestand mag niet groter zijn dan 3MB (1920*1080)',
    'upload.formatJPG': 'Formaat: JPG',
    'upload.size3M': 'Grootte: max. 3MB (1920x1080)',
    'global.cancel': 'Annuleren',
    'global.save': 'Opslaan',
    'global.confirm': 'Bevestig',
    'global.send': 'Verzenden',
    'global.delete': 'Verwijderen',
    'global.close': 'Dichtbij',
    'global.commandSent': 'Opdracht verzonden',
    'global.unableSend': 'Kan niet verzenden',
    'global.commandSave': 'Opdracht opgeslagen',
    'global.unableSave': 'Kan niet opslaan',
    'global.commandDelete': 'Opdracht verwijderd',
    'global.unableDelete': 'Kan niet verwijderen',
    'global.empty': 'Leeg',
    'header.infoCenter': 'Infocentrum',
    'header.allSchool': 'Alle organisaties',
    'header.sendAll': 'Alles verzenden',
    'header.todayCommand': 'De opdracht vandaag',
    'header.admin': 'Admin',
    'header.expired':'Verlopen',
    'header.trial': 'Proef',
    'header.feedback': 'Feedback verzenden',
    'header.inactive': 'Inactief',
    'header.emergency': 'Waarschuwing',
    'global.lockTip':
        'Daarna wordt het account vergrendeld en ontvangt u via e-mail een activeringscode.',
    'global.loading': 'Laden',
    'global.accept': 'Accepteren',
    'global.reject': 'Afwijzen',
    'global.protocplTip1': 'Door me aan te melden, accepteer ik het ',
    'global.protocplTip2': 'en bevestig de aanvaarding van de ',
    'global.userAgreeement': 'Gebruikersovereenkomst',
    'global.policy': 'Privacy-beleid',
    'global.pleaseCheck': 'Controleer de Gebruikersovereenkomst en het Privacy-beleid.',
    'global.switchDefaultTip':
        'Zet de schakelaar aan om de tijd en terugkerende opdracht in te stellen.',
    'global.noResults': 'Geen resultaten',
    'global.off': 'Offline',
    'global.on': 'Online',
    'global.language': 'Taal',
    'global.enroll': 'Aanmelden',
    'global.last': 'Laatste',
    'global.next': 'Volgende',
    'global.continue': 'Doorgaan',
    'global.saveChanges': 'Wijzigingen opslaan',
    'global.mode': 'Modus',
    'global.tags': 'Tags',
    'global.detail': 'Details',
    'global.update.time': 'Update tijd',
    'global.not.configured': 'Niet ingesteld',
    'global.save.and.sync': 'Opslaan en synchroniseren',
    'global.license': 'Vergunning',
    'global.day.remaing': 'Resterende dag',
    'global.linces.records': 'Records',
    'global.license.helper.title':
        'Resterende dagen is de tijdsduur dat dit account toegang heeft tot het product.',
    'global.license.helper.tip1':
        'Duur van de toegang = Het minimum tussen [Looptijd] en [Kredieten/ingeschreven apparaten]',
    'global.license.helper.tip2':
        '[Looptijd] is het aantal dagen dat kan worden gebruikt tot de vervaldatum.',
    'global.license.helper.tip3':
        '[Kredieten/geregistreerde apparaten] is het aantal dagen dat de resterende kredieten ondersteuning is gebruikt door een ingeschreven apparaat.',
    'global.uploading':'Uploaden',
    'global.leave': 'Het verlof',
    "global.change":"Wijziging",
    "global.sending":"Bezig met verzenden",
    "global.get.code":"Code ophalen",
    "global.resend.code":"Code nogmaals versturen",
    "global.change.email":"E-mail wijzigen",
    "global.unknow.error":"Onbekende fout"
};
