export default {
    'group.deviceName': 'Apparaatnaam',
    'group.timezone': 'Tijdzone',
    'group.groupManagement': 'Groepmanagement',
    'group.delGroupTip': 'Deze groep verwijderen?',
    'group.del': 'Verwijderen',
    'group.quit': 'Afsluiten',
    'group.popBtnText': 'Een {val1} groep afsluiten?',
    'group.create': 'Aanmaken',
    'group.save': 'Opslaan',
    'group.enterGroupName': 'Voer hier de groepsnaam in',
    'group.creating': 'Bezig met aanmaken',
    'group.modify': 'wijzigen',
    'group.addNew': 'Nieuwe groep toevoegen',
    'group.all': 'Alle',
    'group.allDevices': 'Alle apparaten {val1}/{val2}',
    'group.selectedDevices': 'Geselecteerde apparaten {val1}',
    'group.conditionLimit': 'Conditielimiet bereikt',
    'group.addCondition': 'Voorwaarde toevoegen',
    'group.autoAllocation': 'Automatische toewijzing',
    'group.manualSelection': 'Handmatige selectie',
    'group.enterConditionHere': 'Vul hier de voorwaarde in',
    'group.enterCondition': 'Voorwaarde invoeren',
    'group.select': 'Selecteer',
};
