export default {
    'channel.message.error': 'Selecteer een kanaal',
    'channel.select.placehoder': 'Selecteer een kanaal',
    'channel.live.name': 'Kanaalnaam',
    'channel.live.title': 'Lijst met live-kanalen',
    'channel.modal.title': 'Kanaal verwijderen?',
    'channel.modal.content': 'Wil je dit kanaal verwijderen?',
    'channel.modal.oktext': 'Verwijderen',
    'channel.form.nameerror': 'Naam mag niet leeg zijn.',
    'channel.form.addresserror': 'Adres mag niet leeg zijn.',
    'channel.form.formaterror': 'Foutief adresformaat.',
    'channel.btn.create': 'Aanmaken',
    'channel.btn.span': 'Ondersteunde livestream-protocol: RTMP, RTSP en HTTP Live Streaming',
    'channel.form.title': 'Bezig met het aanmaken van een live-kanaal',
    'channel.form.labelname': 'Kanaalnaam',
    'channel.form.labeladdress': 'Adres',
    'channel.live.label': 'Live-kanaal',
    'channel.btn.channellist': 'Lijst met live kanalen',
    'channel.form.addressholder': 'Kanaal url',
    'channel.name.exist': 'Kanaal bestaat al!',
    'channel.preview.notsupport': 'Dit live-kanaal ondersteunt geen voorbeeldvenster ',
    'channel.btn.newcreate': 'Maak een live-kanaal aan',
    'channel.edit.livechannel': 'Bewerken live kanaal',
    'channel.edit.save': 'Opslaan',
};
