export default {
    'login.error.emailEmpty': 'Voer uw e-mailadres in.',
    'login.error.emailInvalid': 'Sorry, deze e-mail is ongeldig.',
    'login.error.emailLetterInvalid':
        'Sorry, alleen letters (a-z), cijfers (0-9) en symbolen(@._) zijn toegestaan.',
    'login.error.emailNotFound': 'Geen account gevonden met dit e-mailadres.',
    'login.error.createWidthAccount': 'Met dit account aanmaken?',
    'login.error.pwdEmpty': 'Voer een wachtwoord in.',
    'login.error.pwdInvalid': 'Sorry, dit wachtwoord is onjuist.',
    'login.error.pwdEqualMail': 'Sorry, wachtwoorden mogen niet gelijk zijn aan uw e-mailadres.',
    'login.error.pwdLength': 'Wachtwoorden moeten uit 8-16 tekens bestaan.',
    'login.error.pwdFormat':
        'Een wachtwoord moet twee van de onderstaande categorieën bevatten: cijfers/letters/speciaal teken',
    'login.error.specialSymbol':
        'Sorry, alleen letters (a-z), cijfers (0-9) en speciale tekens (~!@#$%^&*()+-=,./;\\|<>?) zijn toegestaan.',
    'login.error.pwdNotEqual': 'Deze wachtwoorden komen niet overeen',
    'login.error.notLogin': 'U bent niet ingelogd. Log in a.u.b.',
    'login.error.verify': 'Controleer a.u.b.',
    'login.label.forgotPwd': 'Wachtwoord vergeten?',
    'login.label.email': 'E-mail',
    'login.label.notAccount': 'Geen account?',
    'login.label.createAccount': 'Maak een',
    'login.label.pwd': 'Wachtwoord',
    'login.title.account': 'Account',
    'login.title.login': 'Aanmelden',
    'login.title.tips': 'Tips',
    'login.btn.login': 'Aanmelden',
    'login.btn.confirm': 'Bevestig',
    'login.btn.ok': 'OK',
    'login.placeHolder.email': 'Voer uw e-mailadres in',
    'login.placeHolder.pwd': 'Voer uw wachtwoord in',
    'login.logout': 'Uitloggen',
    'login.error.noAuth': 'Account is niet geautoriseerd',
    'login.forgetPwd': 'Wachtwoord vergeten',
    'login.forgetTip':
        'Voer uw e-mailadres in en wij sturen u een link met een verificatiecode om het wachtwoord opnieuw in te stellen.',
    'login.verifyAgain': 'Er is een fout opgetreden. Controleer nogmaals a.u.b.',
    'login.next': 'Volgende',
    'login.backToLogin': 'Terug naar inloggen',
    'login.loginFailed': 'Inloggen mislukt',
    'login.accountExpired': 'Het account is verlopen, neem contact op met het moederaccount',
    'login.accountNoAuth': 'Account is niet geautoriseerd',
    'login.lockChances': '{val1} kansen over',
    'login.resetSuc': 'Resetten succesvol uitgevoerd! Log in...',
    'login.reset.characters816': '8-16 tekens',
    'login.reset.charactersCategories':
        'Twee van de onderstaande categorieën: cijfers/letters/speciale tekens',
    'login.reset.canNotMatch': 'Uw e-mailadres komt niet overeen',
    'login.reset.curPwd': 'Huidig wachtwoord',
    'login.reset.newPwd': 'Nieuw wachtwoord',
    'login.reset.confirmPwd': 'Bevestig wachtwoord',
    'login.modifyPwd': 'Wachtwoord wijzigen',
    'login.title.2FA': '2-Factor Authenticatie',
    'login.2FA.input.tip':'Voer verificatiecode in vanuit de apps van derden',
    "logout.text.tip":"Je logt uit"
};
