export default {
    'profile.createNew': 'Nieuw',
    'profile.time': 'Gemaakt in {createTime}, laatst gewijzigd in {modifyTime}',
    'profile.set': 'instellen als standaard',
    'profile.apply': 'sollicitatie',
    'profile.type': 'type',
    'profile.applied': 'Toegepast',
    'profile.remove': 'De verwijderen',
    'profile.modal.apply': 'sollicitatie',
    'profile.modal.profilename': 'naam',
    'profile.detail.delete': 'verwijderen',
    'profile.detail.seeprofile': 'Rekening',
    'profile.create.new': 'configuratie {os} maken',
    'profile.create.edit': 'Bewerk {os} configuratie',
    'profile.create.security': 'Veiligheid',
    'profile.create.app': 'Apps-beheer',
    'profile.create.securitydes':
        'Blokkeren：Lijstwebsites blokkeren om te voorkomen dat gebruikers toegang krijgen tot de website. Voeg de website toe aan de toegestane lijst om te voorkomen dat gebruikers toegang krijgen tot een andere website dan de toegestane lijst',
    'profile.create.appdes': 'Ondersteunt stille installatie van applicaties',
    'profile.create.appsettingdes': 'Stel de stroom-, weergave- en andere apparaatstatus in',
    'profile.create.config': 'Configuratie',
    'profile.create.checkprofilename': 'Configuratienaam mag niet leeg zijn',
    'profile.create.checkurl': 'URL mag niet leeg zijn',
    'profile.create.whiteblack': 'Blokkeren',
    'profile.create.addurl': 'Voeg URL toe',
    'profile.create.urls': 'URL',
    'profile.create.appremove': 'Apps van het apparaat verwijderen bij profielverwijdering',
    'profile.create.appsmanagement': 'Apps-beheer',
    'profile.create.installapps': 'Installeer app',
    'profile.create.addapps': 'App toevoegen',
    'profile.create.appname': 'naam',
    'profile.create.sleep': 'Automatische slaaptijd',
    'profile.create.sleepdes': 'Ga automatisch naar de slaapmodus geen bewerking is uitgevoerd',
    'profile.create.poweroff': 'Automatische uitschakeling',
    'profile.create.poweroffdes': 'Automatisch uitschakelen als tijd niet wordt gebruikt',
    'profile.create.signal': 'Geen signaaluitschakeling',
    'profile.create.signaldes': 'Automatische uitschakeling wanneer er geen signaalinvoer is',
    'profile.create.powersetting': 'Instellingen stroomuitval',
    'profile.create.powersettingdes': 'Het apparaat toont opnieuw aangesloten na stroomuitval',
    'profile.create.wakeon': 'Wakker worden inschakelen',
    'profile.create.andriodchannel': 'Android-kanaal',
    'profile.create.andriodchanneldes': 'Toestaan ​​dat apparaat overschakelt naar Android-kanaal',
    'profile.create.soundmode': 'Geluidsmodus',
    'profile.create.imagemode': 'Afbeeldingsmodus',
    'profile.create.imagemodedes': 'Afbeeldingsmodus ondersteunt alleen niet-Android-kanalen',
    'profile.create.autoturnoff': 'Schakel het scherm automatisch uit',
    'profile.create.autoturnoffdes':
        'Schakel het scherm automatisch uit zonder enige bewerking binnen de opgegeven tijd',
    'profile.create.sleepmode': 'Zet het apparaat automatisch in de slaapstand',
    'profile.create.sleepmodedes':
        'Zet het apparaat automatisch in de is binnen de opgegeven tijdsperiode',
    'profile.create.poweroffopt': 'Vertrekken',
    'profile.create.poweronopt': 'Aanzetten',
    'profile.create.powerlastopt': 'Laatste',
    'profile.create.none': 'Nooit',
    'profile.create.warning':
        'Alleen V1.9.0 of latere clients ondersteunen het gebruik van configuratiebestanden',
    'profile.create.default': 'standaard',
    'profile.create.savesuccess': 'Met succes opgeslagen',
    'profile.create.savefailed': 'Opslaan mislukt',
    'profile.modal.deletetitle': 'Het profiel verwijderen',
    'profile.modal.deletecontent': 'Weet je zeker dat je het profiel wilt verwijderen?',
    'profile.create.enterurl': 'URL invoeren',

    'profile.create.deletewhiteblack': 'Blokkeerlijst verwijderen/lijst toestaan',
    'profile.create.uninstallapps': 'app verwijderen',
    'profile.create.wakeonopt': 'Wake on LAN',
    'profile.create.autochannelopt': 'Android kanaal',
    'profile.create.sleepmodeopt': 'Slaapstand',
    'profile.route.title': 'Profiel niet opgeslagen',
    'profile.route.content':
        'Het profiel is niet opgeslagen, weet u zeker dat u deze pagina wilt verlaten?',
    'profile.app.size': 'Grootte: tot 300 MB',
    'profile.app.upfiles': 'Maximaal 50 bestanden uploaden',
    'profile.create.hidesidebar': 'Verberg de zijbalk',
    'profile.data.and.time.format.automatically': 'automatisch',
    'profile.data.and.time.format.matically': 'handmatig',
    'profile.12.hour.time': '12-uurs tijd',
    'profile.24.hour.time': '24-uurs tijd',
    'profile.save.failed': 'Opgeslagen mislukt',
    'profile.save.failed.tip':
        'Vul alle vereiste velden in of sluit de configuraties om het profiel op te slaan',
    'profile.device.general.settings': 'Algemene instellingen',
    'profile.update.software': 'Update software',
    'profile.associated.devices': 'Bijbehorende apparaten',
    'profile.not-compliant.num': 'Niet-conform',
    'profile.bytello.devices':
        'Instellingen ondersteund door apparaten die alleen werken met Bytello',
    'profile.date.and.time.label': 'Datum tijd',
    'profile.date.and.time.helper': 'Gebruik door het netwerk geleverde tijd',
    'profile.devices.time.zone': 'Tijdzone',
    'profile.devices.time.format': 'Tijd formaat',
    'profile.devices.non.compliant': 'Niet-conform',
    'profile.devices.compliant': 'Meewerkend',
    'profile.action.sync': 'Synchroniseren',
    'profile.devices.compoliant.status': 'Apparaten - Conforme status',
    'profile.details': 'Details',
    'profile.applied.devices': 'Toegepaste apparaten',
    'profile.create.brief1':
        'Een beleid is een reeks configuraties en beperkingen die zijn ontworpen om apparaten die zijn ingeschreven in DMS te beheren en te beveiligen.',
    'profile.create.brief2':
        'Na het instellen van een profiel als standaard, wanneer een apparaat is ingeschreven bij uw organisatie, zal het automatisch het standaardprofiel ontvangen en uitvoeren.',
    'profile.default.time.zone': 'Verander niet',
    'profile.set.default': 'Standaard instellen',
    'profile.associated.status': 'Selecteer Apparaten-compatibele status',
    'profile.associate': 'Associëren',
    'profile.devices': 'Apparaten',
    'profile.add.devices': 'Apparaten toevoegen',
    'profile.associate.devices': 'Apparaten koppelen',
    'profile.edit.savesuccess': 'Succesvol opslaan en synchroniseren',
};
