export default {
    'register.activateSchool': 'Organisatie activeren',
    'register.hasoOpenPer': ' heeft een {type} machtiging voor u geopend.',
    'register.licenseInfo': 'Licentie-informatie',
    'register.licenseType': 'Licentietype',
    'register.maxPanel': 'Maximum aantal panelen',
    'register.avaTime': 'Beschikbare tijd',
    'register.schoolInfo': 'Organisatie-informatie',
    'register.schoolCode': 'Organisatiecode',
    'register.adminAccount': 'Admin-account',
    'register.schoolName': 'Organisatienaam',
    'register.location': 'Locatie',
    'register.hint': 'Als u vragen heeft, neem dan contact op met ',
    'register.maxPanelHint': 'Als u het aantal wilt verhogen, neem dan contact op met ',
    'register.selectLocation': 'Kies uw land of regio',
    'register.typeSchoolName': 'type Organisatienaam',
    'register.schoolNameCannotRepeat':
        'De organisatienaam mag maar een keer voorkomen binnen een regio.',
    'register.selectLocationHint': 'Selecteer de Organisatielocatie.',
    'register.inputNoEmpty': 'Invoer mag niet leeg zijn.',
    'register.4Digit': 'Ten minste 4 cijfers',
    'register.quantity': 'Hoeveelheid',
    'register.credits': 'tegoeden',
};
