export default {
    'remote.detail.control': 'Schermbesturing',
    'remote.detail.realtime': 'Weergave in realtime',
    'remote.full.turnon': 'Schermbesturing ingeschakeld',
    'remote.full.turnoff': 'Schermbesturing uitgeschakeld',
    'remote.full.control': 'Schermbesturing',
    'remote.full.exitcontrol': 'Afsluiten schermbesturing',
    'remote.remote.control': 'Besturing op afstand: ',
    'remote.preview.off': 'Apparaat staat uit',
    'remote.preview.getscreen': 'Scherm ophalen...',
    'remote.video.offline':
        'Dit apparaat is offline, probeer de status van het apparaat of het netwerk te controleren',
    'remote.video.error':
        'Dit apparaat is verbonden door een andere gebruiker. Probeer het later nog eens.',
    'remote.video.failedtitle': 'Dit apparaat is offline.',
    'remote.video.try': 'probeer',
    'remote.video.checkpower': '·Controleer de stroom- en netwerkstatus van het apparaat',
    'remote.video.buttonreconnect': '·Klik op onderstaande knop om opnieuw te verbinden',
    'remote.video.button': 'Opnieuw verbinden',
    'remote.video.loading': 'Laden',
    'remote.command.tooltip': 'Nu uitgevoerd',
    'remote.command.poweron': 'Aanzetten',
    'remote.command.poweroff': 'Uitzetten',
    'remote.command.reboot': 'Opnieuw opstarten',
    'remote.command.lock': 'Schermvergrendeling',
    'remote.command.unlock': 'Ontgrendeling scherm',
    'remote.pop.power': 'Apparaatvoeding',
    'remote.pop.lock': 'Schermvergrendeling',
    'remote.reject.title': 'Apparaatgebruiker afgewezen',
    'remote.reject.conent':
        'De gebruiker moet toestemming geven voor besturing of afstand. Overleg vooraf met de gebruiker.',
    'remote.reject.okexit': 'Afsluiten',
    'remote.reject.ok': 'OK',
    'remote.device.touch': 'Touchapparaat',
    'remote.tooltip.waiting': 'In afwachting van machtiging',
};
