export default {
    'userDetail.pwdPermission': 'Wachtwoordmachtiging',
    'userDetail.authCommands': 'Geautoriseerde opdrachten',
    'userDetail.manage': 'Beheren',
    'userDetail.authCommandsSave': 'Geautoriseerde opdrachten opgeslagen.',
    'userDetail.unableSave': 'Kan niet opslaan.',
    'userDetail.authDevicesSave': 'Geautoriseerde opdrachten opgeslagen.',
    'userDetail.commandAuthFor': 'Opdracht autorisatie voor',
    'userDetail.device': 'Apparaat',
    'userDetail.label': 'Label',
    'userDetail.deviceAuthFor': 'Autorisatie apparaat voor',
    'userDetail.authDevices': 'Geautoriseerde apparaten',
    'userDetail.deviceNo': 'Apparaat nr.',
    'userDetail.authGroup': 'Geautoriseerde groepen',

    'userDetail.roleCannotDel': 'De rol kan niet worden verwijderd.',
    'userDetail.userIsUsing': 'De gebruiker die deze rol gebruikt:',
    'userDetail.deleteRole': 'Rol verwijderen?',
    'userDetail.roleName': 'Rol naam',
    'userDetail.customRole': 'Aangepaste rol',
    'userDetail.roleList': 'Rollenlijst',
    'userDetail.allDevicesAndGroup': 'Alle apparaten en groepen',
    'userDetail.createDeviceGroup': 'Apparaatgroep maken',
    'userDetail.deleteGroup': 'Deze groep verwijderen uit {username}?',
    'userDetail.switchRoleHint': 'Weet u zeker dat u de rol van {role} wilt wijzigen?',
    'userDetail.userInfomation': 'Gebruikers informatie',
    'userDetail.switchRole': 'Wissel van rol',
    'userDetail.createSucc': 'Succesvol aanmaken',
    'userDetail.operatorHint':
        'Operator ：Deze gebruiker heeft de volledige bevoegdheid om op elk aspect van het platform te handelen.',
    'userDetail.viewerHint': `Kijker: deze gebruiker kan alleen apparaat-, gebruiker-, inschrijvings- en applicatie-informatie bekijken. Kan geen wijzigingen aanbrengen in Intune.`,
    'userDetail.customHint': 'Aangepaste rol: Rollen maken met aangepaste machtigingen.',
    'userDetail.roleNameExists': 'Rolnaam {name} bestaat al',
    'userDetail.createAGroup': 'Een groep maken',
};
