export default {
    'user.title': 'Admin beheren',
    'user.username': 'Gebruikersnaam',
    'user.account': 'Account',
    'user.role': 'Rol',
    'user.latestOperation': 'Laatste bewerking',
    'user.deviceNum': 'Apparaatnr.',
    'user.commandNum': 'Opdrachtnummer',
    'user.remotePwd': '{type} wachtwoord',
    'user.screenLockPwd': 'Wachtwoord schermvergrendeling',
    'user.details': 'Details',
    'user.remotePwdStatus.disabled': 'Uitgeschakeld',
    'user.remotePwdStatus.visible': 'Zichtbaar',
    'user.remotePwdStatus.invisible': 'Onzichtbaar',
    'user.createSubAccount': 'Voeg gebruiker toe',
    'user.noAccountHint': 'Maak eerst een sub-account aan',
    'user.deleteSucHint': 'Sub-account {account} verwijderd uit {unitName}.',
    'user.delete': 'Verwijderen',
    'user.deleteSubAccount': 'Sub-account verwijderen',
    'user.deleteConfirm': 'Wilt u {account} uit {unitName} verwijderen? ',
    'user.anEmailWillSent': 'Er wordt een e-mail verzonden naar {account}.',
    'user.addAccountSucHint': '{email} toegevoegd aan {unitName}.',
    'user.addAccountErrHint': 'Kan geen sub-account aanmaken.',
    'user.information': 'Informatie',
    'user.device': 'Apparaat',
    'user.permission': 'Machtiging',
    'user.prev': 'Vorige',
    'user.create': 'Aanmaken',
    'user.next': 'Volgende',
    'user.createAPwd': 'Maak een wachtwoord aan dat:',
    'user.816Characters': '8-16 tekens',
    'user.twoCategories': 'Twee van de onderstaande categorieën: cijfers/letters/speciale tekens',
    'user.cannotMatchEmail': 'Uw e-mailadres komt niet overeen',
    'user.accountAlreayHas': 'Dit account is al een gebruiker van de organisatie.',
    'user.emailCheckEmpty': 'Voer uw e-mailadres in.',
    'user.emailCheckHasSpecialSymbol':
        'Sorry, alleen letters (a-z), cijfers (0-9) en symbolen(@._) zijn toegestaan.',
    'user.emailCheckFormat': 'Sorry, deze e-mail is ongeldig.',
    'user.pwdCheckEmpty': 'Voer een wachtwoord in.',
    'user.pwdCheckMatch': 'Sorry, wachtwoord komt niet overeen met uw e-mailadres.',
    'user.pwdCheckLength': 'Wachtwoorden moeten ten minste 8 tekens bevatten.',
    'user.pwdCheckHasSpecialSymbol':
        'Sorry, alleen letters (a-z), cijfers (0-9) en speciale tekens (~!@#$%^&*()+-=,./;\\|<>?) zijn toegestaan.',
    'user.pwdCheckFormat':
        'Wachtwoorden moeten ten minste twee van de volgende bevatten: cijfers/letters/speciale tekens.',
    'user.usernameCheckEmpty': 'Voer gebruikersnaam in',
    'user.usernameCheckFormat': 'Sorry, alleen letters (a-z) en cijfers (0-9) zijn toegestaan',
    'user.password': 'Wachtwoord',
    'user.accountMatched': 'Account gematcht',
    'user.enterAnEmail': 'Voer een e-mail adres in',
    'user.modify': 'Wijzigen',
    'user.verify': 'Controleer',
    'user.deviceName': 'Apparaatnaam',
    'user.coAdministrator': 'Mede-admin',
    'user.selected': 'Geselecteerd',
    'user.allDevices': 'Alle apparaten',
    'user.permissionAuth': 'Machtiging toegestaan voor',
    'user.pwdPermission': 'Wachtwoordmachtiging',
    'user.allCommands': 'Alle apparaten',
    'user.emerHint': 'Stuur een waarschuwingsbericht naar het apparaat.',
    'user.notificationHint': 'Scroll-bericht naar het apparaat verzenden.',
    'user.announcementHint': 'Pushbericht video/foto naar het apparaat.',
    'user.filePublishHint': 'Bestanden naar het apparaat verzenden.',
    'user.powerStateHint': 'Stel de statusweergave in nadat het apparaat is ingeschakeld.',
    'user.androidStateHint': 'Stel de zichtbaarheid van het Android-kanaal in.',
    'user.wallpaperHint': 'Verander op afstand de achtergrond van het apparaat.',
    'user.logoHint': 'Op afstand het opstartlogo wijzigen.',
    'user.input': 'Invoer',
    'user.hours': 'Verloopt over {time } uur',
    'user.days': 'Verloopt over { time } dag(en)',
    'user.yearsDays': 'Verloopt over { year } jaar en { days } dag(en)',
    'user.years': 'Verloopt over { year } jaar',
    'user.hoursLeft': '{ time } uur over',
    'user.daysLeft': '{ time } dagen over',
    'user.yearsDaysLeft': '{ year } jaar en { days } dagen over',
    'user.yearsLeft': '{ year } jaar over',
    'user.addUser': 'Voeg gebruiker toe',
    'user.allDevicesAndGroups': 'Alle groepen en apparaten',
    'user.enterRoleName': 'Voer hier de rolnaam in',
    'user.standard': 'Standaard',
    'user.email.change.title1':'E-mailadres van account wijzigen',
    'user.email.change.tip1':'We sturen u een verificatiecodelink om het e-mailadres van uw account te wijzigen.',
    'user.email.change.title2':"Verifieer om door te gaan",
    "user.email.change.tip2":"Hulp nodig? neem dan contact op met {val1}",
    "user.email.change.title3":"E-mailadres van account wijzigen",
    "user.email.change.tip3":"De beheerder van de wijzigingsorganisatie logt uit. Het inlogwachtwoord blijft hetzelfde na het wijzigen.",
    "user.email.change.new.input.tip":"Nieuwe e-mail",
    "user.email.change.input.placeholder":"Voer hier een nieuw e-mailadres in",
    "user.email.change.success.tip":"E-mailadres van account gewijzigd.",
    "user.email.change.fail.txt":"Sorry, dit e-mailadres is geregistreerd."

};
