export default {
    'account.personalInfo': 'Account management',
    'account.account': 'Account',
    'account.username': 'Username',
    'account.resetPswd': 'Reset password',
    'account.resetPswdTip1':
        'After reset the password,this account will be automatically logged out. ',
    'account.resetPswdTip2':
        'Caution:If you have use other Usercenter products,the password will be update synchronously.',
    'account.pswdManagement': 'Password management',
    'account.password': 'Password',
    'account.remoteLock': 'Password of {type} lock',
    'account.password.remoteLock.desc':'Enter the password to unenroll the device.',
    'account.remoteLockDesc': 'Lock {type} in Settings. Enter the password to unlock it.',
    'account.deviceSettingLock': 'Device setting lock',
    'account.deviceSettingLockDesc':
        'Lock Settings in the device. Enter the password to unlock it.',
    'account.screenLock': 'Password of screen lock',
    'account.screenLockDesc': 'Lock device screen for a period. Enter the password to unlock it.',
    'account.school': 'Organization',
    'account.schoolName': 'Organization name',
    'account.state': 'State',
    'account.admin': 'Admin manager',
    'account.email': 'Email',
    'account.schoolCode': 'Organization code',
    'account.serverManagement': 'WOL server',
    'account.serverManagement.hint':
        'Wake-on-LAN (WoL) is an Ethernet or Token Ring computer networking standard that allows a computer to be turned on or awakened by a network message.',
    'account.serverName': 'Server name',
    'account.powerState': 'Server state',
    'account.connectNum': 'Connected No.',
    'account.delete': 'Delete',
    'account.deleteServer': 'Delete Server',
    'account.delServerTip': 'Do you want to delete {serverName} from {unitName}?',
    'account.delServerSuc': 'Server {serverName} deleted from {unitName}.',
    'account.serverOff': 'Unavailable',
    'account.serverOn': 'Available',
    'account.about': 'About',
    'account.legalInfo': 'Legal information',
    'account.userExpPlan': 'User experience plan',
    'account.userExpPlan1': 'User Experience Plan >',
    'account.OK': 'OK',
    'account.accept': 'Accept',
    'account.quit': 'Quit',
    'account.userArgeement': 'User Agreement >',
    'account.privacyPolicy': 'Privacy Policy >',
    'account.openLicense': 'Opensource License >',
    'account.pleaseEnterPswd': 'Please enter your password.',
    'account.pswdLen6': 'Passwords must have 6 characters.',
    'account.pswdOnlyNumber': 'Sorry,only numbers(0-9) are allowed.',
    'account.userNameValidateInfo':
        'Sorry,only letters(a-z),numbers(0-9),and character(@,_) are allowed.',
    'account.logout': 'Logout',
    'account.userName': 'Username',
    'account.edit': 'Edit',
    'account.pswd': 'Password',
    'account.reset': 'Reset',
    'account.location': 'Location',
    'account.adminUserName': 'Admin',
    'account.adminAccount': 'Admin account',
    'account.schoolInfoMod': 'Organization information modification',
    'account.deleteConfirm': 'Do you want to delete {account} from {unitName} ?',
    'account.anEmailWillSent': 'An email will sent to {account}.',
    'account.notConnectHint': '{num} devices not connected to any server',
    'account.connectedDeivces': 'Connected devices',
    //2FA
    'account.two.factor.authentication': '2-Factor Authentication',
    'account.2FATip':
        'If two factor authenticatio is enabled, you will be required to provide a verification code to login Bytello DMS',
    'account.error.twoFA.isEmpty': 'Please enter 6-digit verification code',
    'account.Authenticate.password.title': 'Authenticate to continue',
    'account.disable.2FA.title': 'Disable 2-Factor Authentication',
    'account.Authenticate.password.label': 'Enter your account password',
    'account.Authenticate.password.confirm': 'Authenticate',
    'account.enable.2FA.title': 'Enable 2-Factor Authentication',
    'account.Authenticate.tip':
        'Enable 2 factor authentication make sure your account has more security. Please install Google Authenticator or Microsoft Authenticator',
    'account.Authenticate.ScanCode.title': '1 / Scan this OR code with your verification app',
    'account.Authenticate.ScanCode.cannotScan': 'Cannot scan this OR code?',
    'account.Authenticate.code.text.title': 'Enter this code to authenticator app:',
    'account.Authenticate.input.title':
        '2 / Input 6-digit verification code from your verification app',
    'account.error.faInvalid': 'Invalid verification code',
    'account.Authenticate.2fa.enable': 'Enable',
    'account.success.enable.fa': 'Enable 2-Factor Authentication successfully',
    'account.success.disable.fa': '2-Factor Authentication disabled',
    'account.disable.2FA': 'Disable 2FA',
};
