export default {
    'application.uploading': 'Uploading',
    'application.uploadingTip': 'Application uploading, exit will not save application.',
    'application.exit': 'Exit',
    'application.cancel': 'Cancel',
    'application.pleaseWait': 'Please wait for the current APK upload to complete.',
    'application.fileNameTooLong': 'File name too long',
    'application.support100Mb': 'Support 100MB max.',
    'application.alreadyHasNewer': 'Already has a newer version of this app.',
    'application.internetFailed': 'Internet failed.',
    'application.uploadSuc': 'Uploaded successfully.',
    'application.deleteApk': 'Delete APK',
    'application.deleteApkTip':
        'After deletion, {val1} will be removed from the application management list.',
    'application.delete': 'Delete',
    'application.deleteSuc': 'Application deleted successfully.',
    'application.pleaseSelectDevice': 'Please select a device.',
    'application.uploadApk': 'Upload APK',
    'application.installApp': 'Install application',
    'application.install': 'Install',
    'application.uninstallFromDevice': 'Uninstall from device',
    'application.uninstall': 'Uninstall',
    'application.uninstallTip': 'After uninstalling, this app will be delete from devices.',
    'application.disableInDevice': 'Disable in device',
    'application.disable': 'Disable',
    'application.disableTip':
        'After disabling, the application will not be available in devices where it is already installed.',
    'application.enableInDevice': 'Enable in device',
    'application.enable': 'Enable',
    'application.enableTip':
        'After enabling, the app will be available in devices where it is already installed.',
    'application.unavailable': 'This app will be unavailable during the update.',
    'application.multiTimezoneSelected':
        'Commands will execute by the local time zone of the equipment. (when multi-timezone selected)',
    'application.selected': 'Selected',
    'application.applicationName': 'Apps name',
    'application.appVersion': 'Version',
    'application.appSize': 'Size',
    'application.searchTip': 'Search {val1}',
    'application.reset': 'Reset',
    'application.search': 'Search',
    'application.pleaseUpload': 'Please upload an APK',
    'application.file.location': 'File location',
    'application.file.tooltip':
        'This package does not support silent installation. Please install it manually.',
};
