export default {
    'cmdRecords.execHistory.recallSent': 'Recall command sent.',
    'cmdRecords.execHistory.unableSent': 'Unable to sent.',
    'cmdRecords.execHistory.unlockSent': 'Unlock command sent.',
    'cmdRecords.execHistory.cmdSent': 'Command sent',
    'cmdRecords.cmdInSchedule.timed': 'Timed',
    'cmdRecords.cmdInSchedule.recurring': 'Recurring',
    'cmdRecords.updateTime': 'Update time',
    'cmdRecords.cmdName': 'Command name',
    'cmdRecords.cmdOwner': 'Command owner',
    'cmdRecords.timeMode': 'Time mode',
    'cmdRecords.devices': 'Devices',
    'cmdRecords.cmdStatus': 'Command status',
    'cmdRecords.details': 'Details',
    'cmdRecords.executed': 'Executed',
    'cmdRecords.unexecuted': 'Unexecuted',
    'cmdRecords.recalled': 'Recalled',
    'cmdRecords.deviceCmdExecTable.settingFailed': 'Setting failed',
    'cmdRecords.deviceCmdExecTable.systemError': 'System error',
    'cmdRecords.deviceCmdExecTable.unknownError': 'Unknown error',
    'cmdRecords.deviceCmdExecTable.resetFail': 'Reset fail',
    'cmdRecords.deviceCmdExecTable.downloadError': 'Download error',
    'cmdRecords.deviceCmdExecTable.rejectByUser': 'Reject by user',
    'cmdRecords.deviceCmdExecTable.notImplemented': 'Function not implemented',
    'cmdRecords.deviceCmdExecTable.cmdCovered': 'Command covered',
    'cmdRecords.deviceCmdExecTable.notSupport': 'Not support in android',
    'cmdRecords.deviceCmdExecTable.unsupportResetWallpaper': 'Unsupport reset wallpaper',
    'cmdRecords.deviceCmdExecTable.alreadyExists': 'Already exists',
    'cmdRecords.deviceCmdExecTable.installConflict': 'Install conflict',
    'cmdRecords.deviceCmdExecTable.versionTooOld': 'Version too old',
    'cmdRecords.deviceCmdExecTable.insufficientStorage': 'Insufficient storage',
    'cmdRecords.deviceCmdExecTable.formatNotSupport': 'Format not supported',
    'cmdRecords.deviceCmdExecTable.userRestricted': 'User restricted',
    'cmdRecords.deviceCmdExecTable.installError': 'Install error',
    'cmdRecords.deviceCmdExecTable.channelNameEmpty': 'Channel name empty',
    'cmdRecords.deviceCmdExecTable.nonExist': 'Non-existent',
    'cmdRecords.deviceCmdExecTable.switchFailed': 'Switch failed',
    'cmdRecords.deviceCmdExecTable.timeout': 'time out',
    'cmdRecords.deviceCmdExecTable.deviceIsOff': 'Device is offline',
    'cmdRecords.deviceCmdExecTable.deviceNotExists': 'Device not exists',
    'cmdRecords.deviceCmdExecTable.virtualDeviceNotSupport': "Virtual device isn't support",
    'cmdRecords.deviceCmdExecTable.wolNotEnabled':'WOL not enabled',
    'cmdRecords.deviceCmdExecTable.withdrawal': 'Withdrawal',
    'cmdRecords.deviceCmdExecTable.waitForExecute': 'wait for execute',
    'cmdRecords.deviceCmdExecTable.deviceUnbound': 'Device unbound',
    'cmdRecords.deviceCmdExecTable.expired': 'expired',
    'cmdRecords.deviceCmdExecTable.noBinding': 'No binding',
    'cmdRecords.deviceCmdExecTable.wakeServerNotExists': 'Wake server not exists',
    'cmdRecords.deviceCmdExecTable.wakeServerIsOff': 'Wake server is off',
    'cmdRecords.deviceCmdExecTable.cmdNotSupported': 'command not supported',
    'cmdRecords.deviceCmdExecTable.unlocked': 'Unlocked',
    'cmdRecords.deviceCmdExecTable.reset': 'Reset',
    'cmdRecords.deviceCmdExecTable.ok': 'OK',
    'cmdRecords.deviceCmdExecTable.deviceName': 'Device name',
    'cmdRecords.deviceCmdExecTable.execTime': 'Execution time',
    'cmdRecords.deviceCmdExecTable.execResults': 'Execution results',
    'cmdRecords.deviceCmdExecTable.loading': 'Loading...',
    'cmdRecords.deviceCmdExecTable.resend': 'Resend',
    'cmdRecords.deviceCmdExecTable.unlock': 'Unlock',
    'cmdRecords.deviceCmdExecTable.recall': 'Recall',
    'cmdRecords.deviceCmdExecTable.wait': 'wait',
    'cmdRecords.deviceCmdExecTable.pending': 'pending',
    'cmdRecords.deviceCmdExecTable.recalled': 'recalled',
    'cmdRecords.deviceCmdExecTable.covered': 'covered',
    'cmdRecords.deviceCmdExecTable.success': 'success',
    'cmdRecords.deviceCmdExecTable.failed': 'failed',
    'cmdRecords.recordDetailDrawer.bells': 'Bells',
    'cmdRecords.recordDetailDrawer.text': 'Text',
    'cmdRecords.recordDetailDrawer.media': 'Media',
    'cmdRecords.recordDetailDrawer.file': 'File',
    'cmdRecords.recordDetailDrawer.soundMode': 'Sound mode',
    'cmdRecords.recordDetailDrawer.imageMode': 'Image mode',
    'cmdRecords.recordDetailDrawer.androidState': 'Android state',
    'cmdRecords.recordDetailDrawer.wallpaper': 'Wallpaper',
    'cmdRecords.recordDetailDrawer.logo': 'Logo',
    'cmdRecords.recordDetailDrawer.detail': 'Detail',
    'cmdRecords.recordDetailDrawer.switchTo': 'Switch to',
    'cmdRecords.recordDetailDrawer.cmdOwner': 'Command owner:',
    'cmdRecords.recordDetailDrawer.deviceNo': 'Devcie no.:',
    'cmdRecords.recordDetailDrawer.devices': 'devices',
    'cmdRecords.recordDetailDrawer.timeMode': 'Time mode:',
    'cmdRecords.recordDetailDrawer.cmdSetTime': 'Command Set time:',
    'cmdRecords.recordDetailDrawer.unlockAllTip': 'Unlock all devices under my control',
    'cmdRecords.recordDetailDrawer.unlockAll': 'Unlock all',
    'cmdRecords.recordDetailDrawer.seeRecurring': 'See recurring',
    'cmdRecords.recordDetailDrawer.recallAllTip': 'Recall all devices under my control',
    'cmdRecords.recordDetailDrawer.recallAll': 'Recall all',
    'cmdRecords.recordDetailDrawer.isNotManageTip':
        '{val1} devices not under my control, include {val2} executed',
    'cmdRecords.recordDetailDrawer.isManageTip': '{val1} devices not under my control',
    'cmdRecords.tableFilter.selectCmdName': 'Select command name',
    'cmdRecords.tableFilter.selectTimeMode': 'Select time mode',
    'cmdRecords.tableFilter.selectCmdStatus': 'Select command status',
    'cmdRecords.recurringTable.fold': 'Fold',
    'cmdRecords.recurringTable.expand': 'Expand',
    'cmdRecords.recurringTable.edit': 'Edit',
    'cmdRecords.recurringTable.sunday': 'Sun.',
    'cmdRecords.recurringTable.monday': 'Mon.',
    'cmdRecords.recurringTable.tuesday': 'Tues.',
    'cmdRecords.recurringTable.wednesday': 'Wed.',
    'cmdRecords.recurringTable.thursday': 'Thurs.',
    'cmdRecords.recurringTable.friday': 'Fri.',
    'cmdRecords.recurringTable.saturday': 'Sat.',
    'cmdRecords.recurringTable.deleteCommand': 'Delete Command',
    'cmdRecords.recurringTable.areYouSureDelCommand':
        'Are you sure you want to delete this command？',
    'cmdRecords.recurringTable.statusChangeSuc': 'Status changed',
    'cmdRecords.recurringTable.statusChangeFail': 'Unable to change',
    'cmdRecords.tableFilter.today': 'Today',
    'cmdRecords.tableFilter.dayRange': '{val1} {val2} days',
    'cmdRecords.recordDetailDrawer.updateVersion': 'Update version',
    'cmdRecords.recordDetailDrawer.livechannel': 'Channel name',
    'cmdRecords.deviceCmdExecTable.notsupport': "OS doesn't support",

    'cmdRecords.search.owner': 'Search owner email',
    'cmdRecords.deviceCmdExecTable.uninstall': 'App not exist',
    'cmdRecords.send.failed': 'send command failed',
};
