export default {
    'commandModal.pleaseSelectABell': 'Please select a bell.',
    'commandModal.bellList': 'Bell list',
    'commandModal.bellName': 'Bells name',
    'commandModal.size': 'Size',
    'commandModal.time': 'Time',
    'commandModal.pleaseUploadABell': 'Please upload a bell',
    'commandModal.fileSize10M': 'File size should within 10MB',
    'commandModal.bellFormat': 'File should be MP3、WAV、AAC、OGG format',
    'commandModal.selectUpto': 'Select up to {val1} at a time.',
    'commandModal.reachedMaxLimit': 'Reached the maximum limit.',
    'commandModal.fileNotSupport': 'The current file format does not support preview.',
    'commandModal.youHaveSelected': 'You have selected this file.',
    'commandModal.sureDelete': 'Are you sure to delete it?',
    'commandModal.deleteFile': 'Delete file?',
    'commandModal.bellForamtHint': 'Format: MP3、WAV、AAC、OGG',
    'commandModal.bellSize': 'Size: 10MB max',
    'commandModal.playWhole': 'Play whole',
    'commandModal.setAtLeastOneCycle': 'Set at least one cycle',
    'commandModal.lockDuration': 'Lock duration',
    'commandModal.now': 'Now',
    'commandModal.selectATimePeriod': 'Please select a time period',
    'commandModal.timeExpired': 'Time expired',
    'commandModal.endTimeCannotEarlier': "End time can't earlier than start time",
    'commandModal.timeCannotRepeat': "Time can't be repeat",
    'commandModal.periodNotRepeat': 'Time period cannot be repeated',
    'commandModal.selectMutimedia': 'Please select a mutimedia.',
    'commandModal.upTo50Uploads': 'Up to 50 uploads',
    'commandModal.annFileFormat': 'Format: MP4、AVI、JPG、PNG',
    'commandModal.annFileSize': 'Size: 200MB max',
    'commandModal.annTitle': 'Multimedia',
    'commandModal.selectAMutimedia': 'Select a mutimedia',
    'commandModal.pleaseUploadAMutim': 'Please upload a mutimedia',
    'commandModal.preiew': 'Preview',
    'commandModal.deviceWillPlayAuto': '(The device will play automatically when it executes)',
    'commandModal.mutimediaList': 'Mutimedia list',
    'commandModal.fileMultFormat': 'File should be MP4、AVI、JPG、PNG format',
    'commandModal.fileMultSizeLimit': 'File size should within 200MB',
    'commandModal.wallpaperFormat': 'File should be JPG format',
    'commandModal.pleaseUploadA': 'Please upload {val1}',
    'commandModal.wallTitle': 'Wallpaper',
    'commandModal.logoTitle': 'Logo',
    'commandModal.soundModeStandard': 'Standard',
    'commandModal.soundModeClassroom': 'Classroom',
    'commandModal.soundModeMetting': 'Meeting',
    'commandModal.soundModeCustom': 'Custom',
    'commandModal.imageModeStandard': 'Standard',
    'commandModal.imageModeBright': 'Bright Mode',
    'commandModal.imageModeSoft': 'Soft',
    'commandModal.imageModeCustom': 'Custom',
    'commandModal.switchAnd': 'Switch android enable',
    'commandModal.allowToSwitch': 'Allow devices to switch to Android channels.',
    'commandModal.NoSignalTimeNever': 'Never',
    'commandModal.NoSignalTime1min': '1 min',
    'commandModal.NoSignalTime3min': '3 min',
    'commandModal.NoSignalTime5min': '5 min',
    'commandModal.NoSignalTime10min': '10 min',
    'commandModal.NoSignalTime30min': '30 min',
    'commandModal.NoSignalTime45min': '45 min',
    'commandModal.NoSignalTime60hour': '60 min',
    'commandModal.NoSignalTime90hour': '90 min',
    'commandModal.NoSignalTime120hour': '120 min',
    'commandModal.remainPowerOff': 'Remain power off',
    'commandModal.autoPowerOn': 'Auto power on',
    'commandModal.returnPowerState': 'Return to the power state before power outage',
    'commandModal.noSignalShutdown': 'No signal shutdown',
    'commandModal.autoPowerOff': 'Auto power off when no signal input.',
    'commandModal.displayAfter': 'Display after power outage',
    'commandModal.deviceDisplayReconn': 'Device display reconnection after power outage.',
    'commandModal.wallpaper': 'wallpaper',
    'commandModal.logo': 'logo',
    'commandModal.useDefault': 'Use default',
    'commandModal.wallpaperCustom': 'Custom',
    'commandModal.returnToDefault': '(Return to the default {val1} of the devices)',
    'commandModal.pleaseSelect': 'Please select a {val1}.',
    'commandModal.pleaseUpload': 'Please upload a {val1}',
    'commandModal.pleaseSelectOne': 'please select one',
    'commandModal.upTo20Uploads': 'Up to 20 uploads',
    'commandModal.wallSizeLimit': 'Size: 3MB max(1920*1080)',
    'commandModal.list': 'list',
    'commandModal.selectedDevices': '{ num } devices selected',
    'commandModal.filePublish.pleaseSelect': 'Please select a file first',
    'commandModal.filePublish.selectUpTo': 'Select up to {val1} at a time.',
    'commandModal.filePublish.reachTheMaximum': 'Reached the maximum limit.',
    'commandModal.filePublish.fileNameTooLong': 'File name too long',
    'commandModal.filePublish.fileSize200': 'File size should within 200MB',
    'commandModal.filePublish.pleaseUpload': 'Please upload a file',
    'commandModal.filePublish.selectAFile': 'Select a file',
    'commandModal.filePublish.fileWillSave': '(File will save to finder)',
    'commandModal.filePublish.multiTimeZoneSelected':
        'Commands will execute by the local time zone of the equipment. (when multi-timezone selected)',
    'commandModal.filePublish.fileList': 'File list',
    'commandModal.filePublish.fileName': 'File name',
    'commandModal.filePublish.format': 'Format',
    'commandModal.filePublish.fileSize': 'Size',
    'commandModal.filePublish.selected': 'You have selected this file.',
    'commandModal.filePublish.deleteConfirmTip': 'Are you sure to delete it?',
    'commandModal.filePublish.deleteConfirmTip1': 'Delete file?',
    'commandModal.filePublish.delete': 'Delete',
    'commandModal.filePublish.upToFilesUploads': 'Up to {val1} files uploads',
    'commandModal.notification.times1': '1 Times',
    'commandModal.notification.times3': '3 Times',
    'commandModal.notification.times5': '5 Times',
    'commandModal.notification.times10': '10 Times',
    'commandModal.notification.times20': '20 Times',
    'commandModal.notification.canNotEmpty': 'Input cannot be empty',
    'commandModal.notification.text': 'Text',
    'commandModal.notification.preview': 'Preview',
    'commandModal.notification.displayArea': 'Display area',
    'commandModal.notification.loopTimes': 'Loop times',
    'commandModal.announcement.displayArea': 'Display area',
    'commandModal.turnOnTheSwitch': 'Turn on the switch to set time and recurring command.',
    'commandModal.setAsSchedule': 'Set as schedule',
    'commandModal.setTime': 'Set time',
    'commandModal.offlineMode': 'Offline mode',
    'commandModal.offlineTooltip':
        'Offline mode allows devices execute command without an internet connection.',
    'commandModal.timed': 'Timed',
    'commandModal.timeTooltip':
        'Commands will execute by the local time zone of the equipment. (when multi-timezone selected)',
    'commandModal.recurr': 'Recurring',
    'commandModal.recurrTooltip':
        'Only one set of recurring command for one device. New recurring com-mand will overwrite the old one.',
    'commandModal.selectATime': 'Select a time.',
    'commandModal.only10times': 'One cycle can only be set 10 times',
    'commandModal.addATime': 'Add a time',
    'commandModal.addARecurring': 'Add a recurring',
    'commandModal.multipleTimeZones':
        'Devices in multiple timezones are selected.\nDisplay date & time as UTC{val1}.',
    'commandModal.oneTimeZones':
        'Device(s) in UTC{val1} selected.\nDisplay date & time as UTC{val2}.',
    'commandModal.loading': 'L O A D I N G',
    'commandModal.videoNotPlayed':
        'If this video is not properly played,please download and watch.',

    'commandModal.playmode': 'Play mode',
    'commandModal.playmode.loop': 'Loop',
    'commandModal.playmode.duration': 'Play duration',
    'commandModal.playmode.right': 'Operation rights',
    'commandModal.playmode.turnoff':
        'Turn off the switch to let the user turn off the command at anytime.',
    'commandModal.playmode.times': '{value} times',
    'commandModal.playmode.throughtout': 'Throughout',
    'commandModal.playmode.min': '{value} min',
    'commandModal.powerOnHint':
        '{num} devices cannot execute Power on command due to the WOL server error',
    'commandModal.blockList.allowList': 'Allow list',
    'commandModal.blockList.closeHint': 'Close the existing whitelist or blocklist on the device',
    'commandModal.blockList.listManage': 'List manage',
    'commandModal.blockList.blockHint': 'URLs that are not allowed',
    'commandModal.blockList.allowHint': 'Specific URLs allowed',
    'commandModal.blockList.URL': 'URL',
    'commandModal.blockList.enterURL': 'Enter a URL',
    'commandModal.blockList.mustBeValidURL': 'Must be a valid url',
    'commandModal.blockList.URLExist': 'URL already exist',
    'commandModal.blockList.enterURLHere': 'Enter URL here',
    'commandModal.blockList.listType': 'List type',
    'commandModal.blockList.list': 'List',
    'commandModal.blockList.pleaseSelectAURL': 'Please select a URL',
    'commandModal.blockList.deleteUrl': 'Delete URL?',
    'commandModal.blockList.exist.url':'URL already exist'
};
