export default {
    'common.noData': 'No Data',
    'common.unknownError': 'Unknown error.',
    'common.agreementTitle': 'Bytello Device Management System User Agreement',
    'common.policyTitle': 'Bytello Device Management System Privacy Policy',
    'common.quitExpPlanTitle':
        'Notice for Quitting the [Bytello Device Management System] Product User Experience Plan',
    'common.userExpPlanTitle': 'Bytello Device Management System Product User Experience Plan',
    'common.filter.clear': 'Clear filters',
    'common.filter.apply': 'Apply filters',
    'common.pleaseSelectDevice': 'Please select devices!',
    'common.selectCmd': 'Select Command',
    'common.allTypes': 'All types',
    'common.soundBar': 'Sound bar',
    'common.ifp': 'IFP',
    'common.paginationTotal': 'Total {val1} items',
    'common.paginationTotal20Page': '20 / page',
    'common.paginationTotal40Page': '40 / page',
    'common.paginationTotal80page': '80 / page',
    'common.executeNow': 'Execute now',
    'common.recurring': 'Recurring',
    'common.timed': 'Timed',
    'common.powerOn': 'Power on',
    'common.powerOff': 'Power off',
    'common.reboot': 'Reboot',
    'common.bells': 'Bells',
    'common.screenLock': 'Screen lock',
    'common.blockList': 'Block list',
    'common.notification': 'Text',
    'common.announcement': 'Multimedia',
    'common.filePublish': 'File publish',
    'common.liveChannel': 'Live channel',
    'common.soundMode': 'Sound mode',
    'common.imageMode': 'Image mode',
    'common.powerState': 'Power state',
    'common.androidState': 'Android state',
    'common.wallpaper': 'Wallpaper',
    'common.logo': 'Boot logo',
    'common.emergency': 'Alert',
    'common.softwareUpdate': 'Software update',

    'common.applicationInstall': 'Application install',
    'common.applicationUninstall': 'Application uninstall',
    'common.applicationAble': 'Application (enable / disable)',
    'common.inputSwitch': 'Input switch',
    'common.actions': 'Actions',
    'common.selectGroup': 'Select group',
    'common.deviceControl': 'Device control',
    'common.message': 'Message',
    'common.deviceSetting': 'Device settings',
    'common.allGroup': 'All group',
};
