export default {
    'dashboard.title': 'Dashboard',
    'dashboard.activeTrend': 'Online trend',
    'dashboard.statisticsTheDaily': 'Statistics the daily online status of all devices',
    'dashboard.inactiveDevice': 'Offline device',
    'dashboard.devices': 'devices',
    'dashboard.deviceOffline': 'Devices offline for more than 7 days',
    'dashboard.deviceName': 'Device name',
    'dashboard.Tags': 'Tags',
    'dashboard.lastOnlineTime': 'Last online time',
    'dashboard.adminAccount': 'Admin account',
    'dashboard.organizationCode': 'Organization code',
    'dashboard.maxConnection': 'Max connection',
    'dashboard.connectedNum': 'Enrolled devices',
    'dashboard.onlineNum': 'Online devices',
    'dashboatd.date': 'Date',
    'dashboatd.onlineNumber': 'Online number',
    'dashboard.credits': 'Credits',
    'dashboard.daysRemain': 'Days remaining',
};
