export default {
    'deviceDetail.all': 'All',
    'deviceDetail.unbindDevice': 'Unenroll Device',
    'deviceDetail.allDeviceDataErased': 'All device data will be erased.',
    'deviceDetail.deviceWillUnbind': 'Device {deviceName} will be unenroll from { unitName }.',
    'deviceDetail.unbind': ' Unenroll',
    'deviceDetail.noData': 'No Data',
    'deviceDetail.group': 'Group: {val1}',
    'deviceDetail.deviceId': 'Device ID',
    'deviceDetail.model': 'Model',
    'deviceDetail.osVersion': 'OS Version',
    'deviceDetail.operationOs': 'Operating System',
    'deviceDetail.processerCPU': 'CPU',
    'deviceDetail.touchFrame': 'Touch Frame',
    'deviceDetail.DMSVersion': '{type} version',
    'deviceDetail.devicesInCommands': 'Device in scheduled commands',
    'deviceDetail.commands': ' Command in schedule',
    'deviceDetail.mode': 'Mode',
    'deviceDetail.commandOwner': 'Command owner',
    'deviceDetail.time': 'Time',
    'deviceDetail.ram': 'RAM',
    'deviceDetail.storage': 'Storage',
    'deviceDetail.deviceInGroup': 'Device in groups',
    'deviceDetail.groupName': 'Group name',
    'deviceDetail.tags': 'Tags',
    'deviceDetail.selectAtag': 'Select a tag or create one',
    'deviceDetail.add': 'Add',
    'deviceDetail.deviceName': 'Device name',
    'deviceDetail.deviceNameIsNull': 'Please enter device name',
    'deviceDetail.onlyLettersHint': 'Only letters, numbers and symbols - + / are allowed.',
    'deviceDetail.tagIsNull': 'Please enter a tag',
    'deviceDetail.lettersNumberAllowed': 'Only letters,numbers are allowed.',
    'deviceDetail.tagsExists': 'Tag exists',
    'deviceDetail.addNew': 'Add new',
    'deviceDetail.deviceInfomation': 'Device information',
    'deviceDetail.deviceDetails': 'Device details',
    'deviceDetail.application.enable': 'Enable',
    'deviceDetail.application.enableTip':
        'After enabling, the apps will be available in devices where it is already installed.',
    'deviceDetail.application.disable': 'Disable',
    'deviceDetail.application.disableTip':
        'After disabling, the apps will not be available in devices where it is already installed.',
    'deviceDetail.application.processing': 'Processing...',
    'deviceDetail.application.updateTip': 'The application will be unavailable during the update.',
    'deviceDetail.application.update': 'Update',
    'deviceDetail.application.uninstall': 'Uninstall',
    'deviceDetail.application.uninstallTip': 'The apps will uninstall from the device.',
    'deviceDetail.application.cmdSentWaitForExec':
        'Command sent, wait for device online to execute.',
    'deviceDetail.application.applicationManagement': 'Application management',
    'deviceDetail.application.refreshed': 'Refreshed',
    'deviceDetail.application.clickToRefresh': 'Click to refresh',
    'deviceDetail.application.thirdPartyApps': 'Third-party apps',
    'deviceDetail.application.nativeApps': 'Native apps',
    'deviceDetail.execTime': 'Execution time',

    'deviceDetail.deviceType': 'Device Type',
    'deviceDetail.SerialNo': 'Serial No.',
    'deviceDetail.useageDataForToday': 'Usage data for today',
    'deviceDetail.deviceUseage': 'Device usage data',
    'deviceDetail.appUseage': 'Application usage data',
    'deviceDetail.timeOfUse': 'Application usage count',
    'deviceDetail.countTheTime': 'Count the times of uses of each Application',
    'deviceDetail.useTime': 'Application used time',
    'deviceDetail.countTheTotal': 'Count the total time accumulated by each Application',

    'deviceDetail.bootTimes': 'Online frequency',
    'deviceDetail.bootTime': 'Device used time',
    'deviceDetail.tab.basic': 'Basic',
    'deviceDetail.tab.commands': 'Commands',
    'deviceDetail.tab.useage': 'Data',
    'deviceDetail.tab.application': 'Apps',
    'deviceDetail.onlineTime': 'Online time',
    'deviceDetail.noAppHint': `Haven't used`,
    'deviceDetail.online': 'Online',
    'deviceDetail.offline': 'Offline',
    'deviceDetail.notify': 'Real-time display notify',
    'deviceDetail.today': 'Today',
    'deviceDetail.yesterday': 'Yesterday',
    'deviceDetail.last7': 'Last 7 days',
    'deviceDetail.last30': 'Last 30 days',
    'deviceDetail.onlineTrends': 'Online trends',
    'deviceDetail.tooltipTime': 'Time',
    'deviceDetail.activeDays': 'Active days',
    'deviceDetail.onlineRate': 'Online rate',
    'deviceDetail.networkInterface': 'Network interface',
    'deviceDetail.macAdress': 'Mac Address',
    'deviceDetail.IPAdress': 'IP Address',
    'deviceDetail.disconnected': 'Disconnected',
    'deviceDetail.Fold': 'Fold',
    'deviceDetail.Expand': 'Expand',
    'deviceDetail.application.disable.hide.slider': 'Disable - Hide sidebar tools',
    'deviceDetail.application.disable.show.slider': 'Disable - Show sidebar tools',
};
