export default {
    'deviceList.ifpAll': 'IFP: All({val1})',
    'deviceList.soundbarAll': 'Sound bar: All({val1})',
    'deviceList.allTypeAll': 'All types: All({val1})',
    'deviceList.deviceErased': 'All device data will be erased.',
    'deviceList.unbindTip': 'Device "{val1}" will be unenroll from {val2}.',
    'deviceList.groupNameCannotEmpty': 'Group name can not be empty',
    'deviceList.allDevices': 'All devices',
    'deviceList.groupNameExists': 'Device Groups "All devices" already exists!',
    'deviceList.groupNameAlreadyExists': 'Device Groups "{val1}" already exists!',
    'deviceList.deviceGroupCreated': 'Device group created',
    'deviceList.filter.searchDeviceName': 'Search device name',
    'deviceList.filter.selectStatus': 'Select status',
    'deviceList.filter.selectTimezone': 'Select time zone',
    'deviceList.filter.selectTags': 'Select tags',
    'deviceList.table.deviceName': 'Device name',
    'deviceList.table.status': 'Status',
    'deviceList.table.tags': 'Tags',
    'deviceList.table.school': 'Organization',
    'deviceList.table.timezone': 'Time zone',
    'deviceList.table.nextCmd': 'Next command',
    'deviceList.table.coAdmin': 'Co-administrator',
    'deviceList.table.details': 'Details',
    'deviceList.table.searchName': 'Search {val1}',
    'deviceList.table.reset': 'Reset',
    'deviceList.table.search': 'Search',
    'deviceList.table.device': 'device',
    'deviceList.group': 'Group',
    'deviceList.hasTypeAll': '{val1}',
    'deviceList.tabel.all': 'Select all',
    'deviceList.tabel.list': 'List',
    'deviceList.tabel.grid': 'Grid',
    'deviceList.select.group': 'Group',
    "device.table.school": "School",
};
