export default {
    'menu.home': 'home',
    'menu.dashboard.dashboard': 'Dashboard',
    'menu.deviceManagement': 'Devices',
    'menu.deviceManagement.allTypes': 'All types',
    'menu.deviceManagement.ifp': 'IFP',
    'menu.deviceManagement.soundBar': 'Sound bar',
    'menu.deviceManagement.ledWall': 'Led wall',
    'menu.functions': 'Advanced',
    'menu.functions.profile': 'Profile',
    'menu.functions.appManage': 'Apps',
    'menu.functions.inputSwitch': 'Input switch',
    'menu.functions.firmwareUpdate': 'Firmware update',
    'menu.functions.softwareUpdate': 'Software update',
    'menu.commandRecords': 'Records',
    'menu.commandRecords.exeHistory': 'History',
    'menu.commandRecords.inSchedule': 'In schedule',
    'menu.user.userManagement': 'User Management',
    'menu.account.accountSettings': 'Account Settings',
    'menu.systemManage': 'System',
    'menu.systemManage.adminManage': 'Users',
    'menu.systemManage.schoolManage': 'Organization',
    'menu.systemManage.passwordManage': 'Password',
    'menu.systemManage.userSettings': 'Settings',
    'menu.resources.resources': 'Resources',
    'global.error.network': 'network error',
    'global.network.timeout': 'time out',
    'global.network.error': 'Internet error',
    'global.btn.ok': 'OK',
    'upload.getUploadPolicyError': 'Upload failed',
    'upload.networkError': 'Upload failed',
    'upload.cancelled': 'Cancel task upload!',
    'upload.formatError': 'file fomat error',
    'upload.fileNameError': 'file name is too long',
    'upload.parsing': 'Parsing…',
    'upload.fileExist': 'File already exist',
    'upload.fileNameTooLong': 'File name too long',
    'upload.fileJPG': 'File should be JPG format',
    'upload.file3M1920': 'File size should within 3MB（1920*1080）',
    'upload.formatJPG': 'Format: JPG',
    'upload.size3M': 'Size: 3MB max (1920x1080)',
    'global.cancel': 'Cancel',
    'global.save': 'Save',
    'global.confirm': 'Confirm',
    'global.send': 'Send',
    'global.delete': 'Delete',
    'global.close': 'Close',
    'global.commandSent': 'Command sent',
    'global.unableSend': 'Unable to send',
    'global.commandSave': 'Command saved',
    'global.unableSave': 'Unable to save',
    'global.commandDelete': 'Command deleted',
    'global.unableDelete': 'Unable to delete',
    'global.empty': 'Empty',
    'header.infoCenter': 'Info Center',
    'header.allSchool': 'All Organization',
    'header.sendAll': 'Send all',
    'header.todayCommand': 'Today’s command',
    'header.expired':'Expired',
    'header.admin': 'Admin',
    'header.trial': 'Trial',
    'header.feedback': 'Send Feedback',
    'header.inactive': 'Inactive',
    'header.emergency': 'Alert',
    'global.lockTip':
        'After that，the account will be locked and an activation code will be sent to your Email.',
    'global.loading': 'Loading',
    'global.accept': 'Accept',
    'global.reject': 'Reject',
    'global.protocplTip1': 'By signing up,I accept the ',
    'global.protocplTip2': 'and confirm acceptance of the ',
    'global.userAgreeement': 'User Agreement',
    'global.policy': 'Privacy Policy',
    'global.pleaseCheck': 'Please check User Agreement and Privacy Policy.',
    'global.switchDefaultTip': 'Turn on the switch to set time and recurring command.',
    'global.noResults': 'No results',
    'global.off': 'Offline',
    'global.on': 'Online',
    'global.language': 'Language',
    'global.enroll': 'Enroll',
    'global.last': 'Last',
    'global.next': 'Next',
    'global.continue': 'Continue',
    'global.saveChanges': 'Save Changes',
    'global.mode': 'Mode',
    'global.tags': 'Tags',
    'global.detail': 'Details',
    'global.update.time': 'Update time',
    'global.not.configured': 'Not configured',
    'global.save.and.sync': 'Save and Sync',
    'global.license': 'License',
    'global.day.remaing': 'Day remaing',
    'global.linces.records': 'Records',
    'global.license.helper.title':
        'Days remaining is the time length that this account have to access to the product.',
    'global.license.helper.tip1':
        'Access time length = The minimum between [Expire time] and [Credits/enrolled devices]',
    'global.license.helper.tip2':
        '[Expire time] is the number of days that can be used up to the expiration date.',
    'global.license.helper.tip3':
        '[Credits/enrolled devices] is the number of days that the remaining credits support has been used by enrolled device.',
    'global.uploading':'Uploading',
    'global.leave': 'Leave',
    "global.change":"Change",
    "global.sending":"Sending",
    "global.get.code":"Get code",
    "global.resend.code":"Resend code",
    "global.change.email":"Change email",
    "global.unknow.error":"Unknow error"
};
