export default {
    'group.deviceName': 'Device name',
    'group.timezone': 'Time zone',
    'group.groupManagement': 'Group management',
    'group.delGroupTip': 'Delete this group?',
    'group.del': 'Delete',
    'group.quit': 'Quit',
    'group.popBtnText': 'Quit {val1} a group?',
    'group.create': 'Create',
    'group.save': 'Save',
    'group.enterGroupName': 'Enter group name here',
    'group.creating': 'creating',
    'group.modify': 'modify',
    'group.addNew': 'Add new group',
    'group.all': 'All',
    'group.allDevices': 'All device {val1}/{val2}',
    'group.selectedDevices': 'Selected devices {val1}',
    'group.conditionLimit': 'Condition limit reached',
    'group.addCondition': 'Add condition',
    'group.autoAllocation': 'Auto-allocation',
    'group.manualSelection': 'Manual selection',
    'group.enterConditionHere': 'Enter condition here',
    'group.enterCondition': 'Enter condition',
    'group.select': 'Select',
};
