export default {
    'channel.message.error': 'Please select a channel',
    'channel.select.placehoder': 'Select a channel',
    'channel.live.name': 'Channel name',
    'channel.live.title': 'Live channel list',
    'channel.modal.title': 'Delete Channel?',
    'channel.modal.content': 'Do you want to delete this channel?',
    'channel.modal.oktext': 'Delete',
    'channel.form.nameerror': 'Name cannot be empty.',
    'channel.form.addresserror': 'Address cannot be empty.',
    'channel.form.formaterror': 'Address format is error.',
    'channel.btn.create': 'Create',
    'channel.btn.span': 'Supported live stream protocal:RTMP,RTSP and HTTP Live Streaming',
    'channel.form.title': 'Creating live channel',
    'channel.form.labelname': 'Channel name',
    'channel.form.labeladdress': 'Address',
    'channel.live.label': 'Live channel',
    'channel.btn.channellist': 'Live channel list',
    'channel.form.addressholder': 'Channel url',
    'channel.name.exist': 'Channel already exists!',
    'channel.preview.notsupport': 'Preview is not supported for this live channel',
    'channel.btn.newcreate': 'Please create a live channel',
    'channel.edit.livechannel': 'Edit live channel',
    'channel.edit.save': 'Save',
};
