export default {
    'noDevice.deviceManagement': 'Device Management',
    'noDevice.enrollDevice': 'Device Binding',
    'noDevice.deviceEnrollment': 'Devices enrollment',
    'noDevice.bindThrough': 'Binding through the {type} app on the device',
    'noDevice.adminAccIs': 'Admin account:',
    'noDevice.schoolCodeIs': 'Organization code:',
    'noDevice.seeMore': 'You can view more information in ',
    'noDevice.option1': 'Option 1',
    'noDevice.enterConnInfo': 'Enter connection info',
    'noDevice.option2': 'Option 2',
    'noDevice.enrollmentUsingUSB': 'Enrollment using USB',
    'noDevice.download': 'Download',
    'noDevice.inUDisk': `in U disk, don't modify.`,
    'noDevice.makeSureTheApp': 'Make sure the application is installed.',
    'noDevice.insertUDisk': 'Inset the U disk in to the device.',
    'noDevice.clickBind': 'Click bind the information is automatically filled.',
    'noDevice.allSchoolHint': 'Select the organization to view more information in Enroll',
    'noDevice.netErr': 'Network error.Please download again',
};
