export default {
    'profile.createNew': 'Create new',
    'profile.time': 'Created on {createTime}, last modified on {modifyTime}',
    'profile.set': 'Set as default',
    'profile.apply': 'Apply',
    'profile.type': 'Type',
    'profile.applied': 'Applied',
    'profile.remove': 'Remove default',
    'profile.modal.apply': 'Apply profile',
    'profile.modal.profilename': 'Profile name',
    'profile.detail.delete': 'Delete profile',
    'profile.detail.seeprofile': 'See profile',
    'profile.create.new': 'Create {os} profile',
    'profile.create.edit': 'Edit {os} profile',
    'profile.create.security': 'Security',
    'profile.create.app': 'Apps management',
    'profile.create.securitydes':
        'Blocking：Block list a website to block users from accessing the website. Allowlisting a website to block users from accessing any website other than the Allowlisted ones',
    'profile.create.appdes': 'Support for silent installation of apps',
    'profile.create.appsettingdes': 'Set the status of the device such as power and display',
    'profile.create.config': 'Configure',
    'profile.create.checkprofilename': 'Profile name cannot be empty',
    'profile.create.checkurl': 'Url cannot be empty',
    'profile.create.whiteblack': 'Blocking',
    'profile.create.addurl': 'Add URL',
    'profile.create.urls': 'URLs',
    'profile.create.appremove': 'Remove apps from the device on profile removal',
    'profile.create.appsmanagement': 'Apps management',
    'profile.create.installapps': 'Install apps',
    'profile.create.addapps': 'Add apps',
    'profile.create.appname': 'Apps name',
    'profile.create.sleep': 'Auto sleep time',
    'profile.create.sleepdes':
        'Auto enter sleep model when no operation for a specified period of time',
    'profile.create.poweroff': 'Auto power off',
    'profile.create.poweroffdes':
        'Automatically shut down without operating equipment for a period of time',
    'profile.create.signal': 'No signal shutdown',
    'profile.create.signaldes': 'Auto power off when no signal input',
    'profile.create.powersetting': 'Power outage setting',
    'profile.create.powersettingdes': 'Device display reconnection after power outage',
    'profile.create.wakeon': 'Enable Wake on LAN',
    'profile.create.andriodchannel': 'Android channel',
    'profile.create.andriodchanneldes': 'Allow devices to switch to Android channels',
    'profile.create.soundmode': 'Sound mode',
    'profile.create.imagemode': 'Image mode',
    'profile.create.imagemodedes': 'Image mode is only supported for non-Android channels',
    'profile.create.autoturnoff': 'Auto turn off screen',
    'profile.create.autoturnoffdes':
        'Auto turn off screen when no operation for a specified period of time',
    'profile.create.sleepmode': 'Auto put devices to sleep mode',
    'profile.create.sleepmodedes':
        'Auto put devices to sleep mode when no operation for a specified period of time',
    'profile.create.poweroffopt': 'Off',
    'profile.create.poweronopt': 'On',
    'profile.create.powerlastopt': 'Last',
    'profile.create.none': 'None',
    'profile.create.warning': 'Only clients with V1.9.0 or higher support the use of profile',
    'profile.create.default': 'Default',
    'profile.create.savesuccess': 'Save successfully',
    'profile.create.savefailed': 'Save failed',
    'profile.modal.deletetitle': 'Delete the profile',
    'profile.modal.deletecontent': 'Are you sure you want to delete the profile?',
    'profile.create.enterurl': 'Enter url',

    'profile.create.deletewhiteblack': 'Delete Block list / Allow list',
    'profile.create.uninstallapps': 'Uninstall apps',
    'profile.create.wakeonopt': 'Wake on LAN',
    'profile.create.autochannelopt': 'Android channel',
    'profile.create.sleepmodeopt': 'Sleep mode',
    'profile.route.title': 'Profile not saved',
    'profile.route.content': 'The profile is not saved,are you sure you want to leave this page?',
    'profile.app.size': 'Size: 300MB max',
    'profile.app.upfiles': 'Up to 50 files uploads',
    'profile.create.hidesidebar': 'Hide sidebar tools',
    'profile.data.and.time.format.automatically': 'Automatically',
    'profile.data.and.time.format.matically': 'Manually',
    'profile.12.hour.time': '12-Hour Time',
    'profile.24.hour.time': '24-Hour Time',
    'profile.save.failed': 'Saved failed',
    'profile.save.failed.tip':
        'Please fill all required fields or close configurtions to save profile',
    'profile.no.dont.change': "Don't change",
    'profile.device.general.settings': 'General settings',
    'profile.update.software': 'Update software',
    'profile.associated.devices': 'Associated devices',
    'profile.not-compliant.num': 'Non-Compliant',
    'profile.bytello.devices': 'Settings supported by devices that only work with Bytello',
    'profile.date.and.time.label': 'Date & time',
    'profile.date.and.time.helper': 'Use network-provided time',
    'profile.devices.time.zone': 'Time zone',
    'profile.devices.time.format': 'Time format',
    'profile.devices.non.compliant': 'Non-Compliant',
    'profile.devices.compliant': 'Compliant',
    'profile.action.sync': 'Sync',
    'profile.devices.compoliant.status': 'Devices - Compliant status',
    'profile.details': 'Details',
    'profile.applied.devices': 'Applied devices',
    'profile.create.brief1':
        'A policy is a set of configurations and restrictions designed to manage and secure devices enrolled in DMS. ',
    'profile.create.brief2':
        'After setting a profile as a default, when a device enrolled to your organization, it will automatically receive and execute the default profile.',
    'profile.default.time.zone': "Don't change",
    'profile.set.default': 'Set default',
    'profile.associated.status': 'Select Devices-Compliant status',
    'profile.associate': 'Associate',
    'profile.devices': 'Devices',
    'profile.add.devices': 'Add devices',
    'profile.associate.devices': 'Associate devices',
    'profile.edit.savesuccess': 'Save and sync successfully',
};
