export default {
    'register.activateSchool': 'Activate organization',
    'register.hasoOpenPer': ' has opened {type} permission for you.',
    'register.licenseInfo': 'License information',
    'register.licenseType': 'License type',
    'register.maxPanel': 'Maximum panels',
    'register.avaTime': 'Available time',
    'register.schoolInfo': 'Organization information',
    'register.schoolCode': 'Organization code',
    'register.adminAccount': 'Admin account',
    'register.schoolName': 'Organization Name',
    'register.location': 'Location',
    'register.hint': 'If you have any questions, please contact ',
    'register.maxPanelHint': 'If you need to increase the number, please contact ',
    'register.selectLocation': 'Choose Your Country or Region',
    'register.typeSchoolName': 'type organization name',
    'register.schoolNameCannotRepeat': 'Organization name cannot be repeated within a region.',
    'register.selectLocationHint': 'Please select organization location.',
    'register.inputNoEmpty': 'input cannot be empty.',
    'register.4Digit': 'At least 4 digit',
    'register.quantity': 'Quantity',
    'register.credits': 'credits',
};
