export default {
  'remote.detail.control': 'Screen control',
  'remote.detail.realtime': 'Real-time display',
  'remote.full.turnon':'Screen control turned on',
  'remote.full.turnoff':'Screen control turned off',
  'remote.full.control':'Screen control',
  'remote.full.exitcontrol':'Exit screen control',
  'remote.remote.control':'Remote Control: ',
  'remote.preview.off':'Device is offline',
  'remote.preview.getscreen':'Getting screen...',
  'remote.video.offline':'This device is offline,try to check device status or network status',
  'remote.video.error':'This device is being connected by another user. Please try again later',
  'remote.video.failedtitle':'This device is offline.',
  'remote.video.try':'try',
  'remote.video.checkpower':'·Check the power and network status of the device',
  'remote.video.buttonreconnect':'·Click the button below to try to reconnect',
  'remote.video.button':'Reconnect',
  'remote.video.loading':'Loading',
  'remote.command.tooltip':'Executed now',
  'remote.command.poweron':'Power on',
  'remote.command.poweroff':'Power off',
  'remote.command.reboot':'Reboot',
  'remote.command.lock':'Screen lock',
  'remote.command.unlock':'Screen unlock',
  'remote.pop.power':'Device power',
  'remote.pop.lock':'Screen lock',
  'remote.reject.title':'Device user rejected',
  'remote.reject.conent':'Require users permission for remote control,please consult with the user before using it.',
  'remote.reject.okexit':'Exit',
  'remote.reject.ok':'OK',
  'remote.device.touch':'Device touch',
  'remote.tooltip.waiting':'Waiting for permission',
};
