export default {
    'userDetail.pwdPermission': 'Password permission',
    'userDetail.authCommands': 'Authorized commands',
    'userDetail.manage': 'Manage',
    'userDetail.authCommandsSave': 'Authorized commands saved.',
    'userDetail.unableSave': 'Unable to save.',
    'userDetail.authDevicesSave': 'Authorized commands saved.',
    'userDetail.commandAuthFor': 'Command authorization for ',
    'userDetail.device': 'Device',
    'userDetail.label': 'Label',
    'userDetail.deviceAuthFor': 'Device authorization for',
    'userDetail.authDevices': 'Authorized devices',
    'userDetail.deviceNo': 'Device No.',
    'userDetail.authGroup': 'Authorized groups',

    'userDetail.roleCannotDel': 'The role cannot be deleted.',
    'userDetail.userIsUsing': 'The user who is using this role:',
    'userDetail.deleteRole': 'Delete role?',
    'userDetail.roleName': 'Role name',
    'userDetail.customRole': 'Custom role',
    'userDetail.roleList': 'Role list',
    'userDetail.allDevicesAndGroup': 'All devices and groups',
    'userDetail.createDeviceGroup': 'Create device group',
    'userDetail.deleteGroup': 'Delete this group from {username}?',
    'userDetail.switchRoleHint': 'Are you sure to switch the {role} role ?',
    'userDetail.userInfomation': 'User information',
    'userDetail.switchRole': 'Switch Role',
    'userDetail.createSucc': 'Create successfully',
    'userDetail.operatorHint':
        'Operator ：This user has full authority to act on every aspect of the platform.',
    'userDetail.viewerHint': `Viewer：This user can only views device, user, enrollment and application information. Can't make changes to Intune.`,
    'userDetail.customHint': 'Custom role：Creating roles with custom permissions.',
    'userDetail.roleNameExists': 'Role name {name} already exists',
    'userDetail.createAGroup': 'Create a group',
};
