export default {
    'user.title': 'Admin Manage',
    'user.username': 'Username',
    'user.account': 'Account',
    'user.role': 'Role',
    'user.latestOperation': 'Latest operation',
    'user.deviceNum': 'Device no.',
    'user.commandNum': 'Command no.',
    'user.remotePwd': '{type} password',
    'user.screenLockPwd': 'Screen lock password',
    'user.details': 'Details',
    'user.remotePwdStatus.disabled': 'Disabled',
    'user.remotePwdStatus.visible': 'Visible',
    'user.remotePwdStatus.invisible': 'Invisible',
    'user.createSubAccount': 'Add user',
    'user.noAccountHint': 'Please create a sub-accout first',
    'user.deleteSucHint': 'Sub-account {account} deleted from {unitName}.',
    'user.delete': 'Delete',
    'user.deleteSubAccount': 'Delete Sub-account',
    'user.deleteConfirm': 'Do you want to delete {account} from {unitName}? ',
    'user.anEmailWillSent': 'An email will be sent to {account}.',
    'user.addAccountSucHint': '{email} added to {unitName}.',
    'user.addAccountErrHint': 'Failed to create sub-account.',
    'user.information': 'Information',
    'user.device': 'Device',
    'user.permission': 'Permission',
    'user.prev': 'Prev',
    'user.create': 'Create',
    'user.next': 'Next',
    'user.createAPwd': 'Create a password that:',
    'user.816Characters': '8-16 characters',
    'user.twoCategories': 'Two categories from below:numbers/letters/special',
    'user.cannotMatchEmail': `Can't match your email address`,
    'user.accountAlreayHas': 'This account is already  a user of the organization.',
    'user.emailCheckEmpty': 'Please enter your email address.',
    'user.emailCheckHasSpecialSymbol':
        'Sorry, Only letters(a-z),numbers(0-9),and symbols(@._-) are allowed.',
    'user.emailCheckFormat': 'Sorry, this email is invalid.',
    'user.pwdCheckEmpty': 'Please enter a password.',
    'user.pwdCheckMatch': 'Sorry,password can’t match your email address.',
    'user.pwdCheckLength': 'Passwords must have at least 8 characters.',
    'user.pwdCheckHasSpecialSymbol':
        'Sorry, Only letters(a-z),number(0-9),and special character(~!@#$%^&*()+-=,./;\\|<>?) are allowed',
    'user.pwdCheckFormat':
        'Passwords must include at least two of the following: numbers/letters/special characters.',
    'user.usernameCheckEmpty': 'Please enter username',
    'user.usernameCheckFormat': 'Sorry, Only letters(a-z),number(0-9) are allowed',
    'user.password': 'Password',
    'user.accountMatched': 'Account matched',
    'user.enterAnEmail': 'Enter an email address',
    'user.modify': 'Modify',
    'user.verify': 'Verify',
    'user.deviceName': 'Device name',
    'user.coAdministrator': 'Co-administrator',
    'user.selected': 'Selected',
    'user.allDevices': 'All devices',
    'user.permissionAuth': 'Permission authorized for',
    'user.pwdPermission': 'Password permission',
    'user.allCommands': 'All devices',
    'user.emerHint': 'Send an alert message to the device.',
    'user.notificationHint': 'Send scroll message to device.',
    'user.announcementHint': 'Push video/picture messages to the device.',
    'user.filePublishHint': 'Send files to the device.',
    'user.powerStateHint': 'Set the status display after the device is power on.',
    'user.androidStateHint': 'Set the visibility of the Android channel.',
    'user.wallpaperHint': 'Remotely change device wallpaper.',
    'user.logoHint': 'Remotely change the boot logo.',
    'user.input': 'Input',
    'user.hours': 'Expire in { time } hours',
    'user.days': 'Expire in { time } days',
    'user.yearsDays': 'Expire in { year } years { days } days',
    'user.years': 'Expire in { year } years',

    'user.hoursLeft': '{ time } hours left',
    'user.daysLeft': '{ time } days left',
    'user.yearsDaysLeft': '{ year } years { days } days left',
    'user.yearsLeft': '{ year } years left',
    'user.addUser': 'Add user',
    'user.allDevicesAndGroups': 'All groups and devices',
    'user.enterRoleName': 'Enter role name here',
    'user.standard':'Standard',
    'user.email.change.title1':'Change account email',
    'user.email.change.tip1':'We will send you a verify code link to change account email.',
    'user.email.change.title2':"Verify to continue",
    "user.email.change.tip2":"Need help? please contact {val1}",
    "user.email.change.title3":"Change account email",
    "user.email.change.tip3":"Change organization admin will logout. Login password remains the same after changing.",
    "user.email.change.new.input.tip":"New email",
    "user.email.change.input.placeholder":"Enter new email here",
    "user.email.change.success.tip":"Successfully changed account email.",
    "user.email.change.fail.txt":"Sorry, this email has been registered."
};
