export default {
    'account.accountInfo': 'アカウント管理',
    'account.account': 'アカウント',
    'account.username': 'ユーザー名',
    'account.resetPswd': 'パスワードを再設定する',
    'account.resetPswdTip1':
        'パスワードをリセットすると、このアカウントは自動的にログアウトされます。 ',
    'account.resetPswdTip2':
        '注意：他のユーザーセンター製品を使用している場合、パスワードは同時に更新されます。',
    'account.pswdManagement': 'パスワード管理',
    'account.password': 'パスワード',
    'account.remoteLock': '{type}ロック',
    'account.password.remoteLock.desc':'xxxxx',
    'account.remoteLockDesc':
        '設定で{type}をロックします。パスワードを入力してロックを解除します。',
    'account.deviceSettingLock': 'デバイス設定ロック',
    'account.deviceSettingLockDesc':
        'デバイスの設定をロックします。パスワードを入力してロックを解除します。',
    'account.screenLock': 'スクリーンロック',
    'account.screenLockDesc':
        'デバイス画面を一定期間ロックします。パスワードを入力してロックを解除します。',
    'account.school': '学校',
    'account.schoolName': '学校名',
    'account.state': '状態',
    'account.admin': '管理マネージャー',
    'account.email': 'Eメール',
    'account.schoolCode': '学校コード',
    'account.serverManagement': 'サーバー管理',
    'account.serverName': 'サーバー名',
    'account.powerState': '電源状態',
    'account.connectNum': '接続デバイス台数',
    'account.delete': '削除',
    'account.deleteServer': 'サーバーの削除',
    'account.delServerTip': 'xxxx',
    'account.delServerSuc': 'サーバー{serverName}が{unitName}から削除されました。',
    'account.serverOff': 'オフ',
    'account.serverOn': 'オン',
    'account.about': 'アカウント情報',
    'account.legalInfo': '法律情報',
    'account.userExpPlan': 'ユーザーエクスペリエンスプラン',
    'account.userExpPlan1': 'ユーザーエクスペリエンスプラン>',
    'account.OK': 'OK',
    'account.accept': '許可する',
    'account.quit': '終了する',
    'account.userArgeement': 'ユーザー規約>',
    'account.privacyPolicy': 'プライバシーポリシー>',
    'account.openLicense': 'オープンソースライセンス >',
    'account.pleaseEnterPswd': 'パスワードを入力してください。',
    'account.pswdLen6': 'パスワードは6文字で入力する必要があります。',
    'account.pswdOnlyNumber': '申し訳ありませんが、数字（0〜9）のみ使用できます。',
    'account.userNameValidateInfo':
        '申し訳ありませんが、半角英字（a-z）、数字（0-9）、記号（@、_）のみ使用できます。',
    'account.logout': 'ログアウト',
    'account.userName': 'ユーザー名',
    'account.edit': '編集',
    'account.pswd': 'パスワード',
    'account.reset': 'リセット',
    'account.location': 'ロケーション',
    'account.adminUserName': '管理者',
    'account.adminAccount': '管理者アカウント',
    'account.schoolInfoMod': '組織情報の変更',
    'account.deleteConfirm': '{unitName}から{account}を削除しますか？',
    'account.anEmailWillSent': '{account}にメールが送信されます。',
    'account.serverManagement.hint':
        'Wake-on-LAN（WoL）は、イーサネットまたはトークンリングのコンピューターネットワーク標準であり、ネットワークメッセージによってコンピューターの電源をオンにしたり、目覚めさせたりすることができます。',
    'account.notConnectHint': '{num} どのサーバーにも接続されていないデバイス',
    'account.connectedDeivces': '接続機器',
    'account.two.factor.authentication': '2要素認証',
    'account.2FATip':
        '二要素認証が有効になっている場合、BytelloDMSにログインするための確認コードを提供する必要があります',
    'account.error.twoFA.isEmpty': '6桁の確認コードを入力してください',
    'account.Authenticate.password.title': '続行するために認証する',
    'account.disable.2FA.title': '2要素認証を無効にする',
    'account.Authenticate.password.label': 'アカウントのパスワードを入力してください',
    'account.Authenticate.password.confirm': '認証する',
    'account.enable.2FA.title': '2要素認証を有効にする',
    'account.Authenticate.tip':
        '2要素認証を有効にして、アカウントのセキュリティが強化されていることを確認します。 GoogleAuthenticatorまたはMicrosoftAuthenticatorをインストールしてください',
    'account.Authenticate.ScanCode.title': '1 /検証アプリでこのORコードをスキャンします',
    'account.Authenticate.ScanCode.cannotScan': 'このORコードをスキャンできませんか？',
    'account.Authenticate.code.text.title': 'オーセンティケーターアプリに次のコードを入力します。',
    'account.Authenticate.input.title': '2 /検証アプリから6桁の検証コードを入力します',
    'account.error.faInvalid': '無効な検証コード',
    'account.Authenticate.2fa.enable': '有効にする',
    'account.success.enable.fa': '2要素認証を正常に有効にする',
    'account.success.disable.fa': '2要素認証が無効になっています',
    'account.disable.2FA': '2FAを無効にする',
};
