export default {
    'application.uploading': 'アップロード',
    'application.uploadingTip':
        'アプリケーションのアップロード、終了の操作ではアプリケーションは保存されません。',
    'application.exit': '終了',
    'application.cancel': 'キャンセル',
    'application.pleaseWait': '現在のAPKアップロードが完了するまでお待ちください。',
    'application.fileNameTooLong': 'ファイル名が長すぎます',
    'application.support100Mb': '最大100MBまでサポート',
    'application.alreadyHasNewer': 'このアプリの新しいバージョンが利用できます。',
    'application.internetFailed': 'インターネットにエラーが発生しました。',
    'application.uploadSuc': '正常にアップロードされました。',
    'application.deleteApk': 'APKを削除',
    'application.deleteApkTip': '削除後、{val1}はアプリケーション管理リストから削除されます。',
    'application.delete': '削除',
    'application.deleteSuc': 'アプリケーションが正常に削除されました。',
    'application.pleaseSelectDevice': 'デバイスを選択してください。',
    'application.uploadApk': 'APKをアップロード',
    'application.installApp': 'アプリケーションをインストール',
    'application.install': 'に装う',
    'application.uninstallFromDevice': 'デバイスからアンインストール',
    'application.uninstall': '取り外し',
    'application.uninstallTip': 'アンインストール後、このアプリはデバイスから削除されます。',
    'application.disableInDevice': 'デバイス上で無効にする',
    'application.disable': '無効',
    'application.disableTip':
        '無効にすると、このアプリはアンインストールされませんが、デバイスでは使用できなくなります。',
    'application.enableInDevice': 'デバイス上で有効にする',
    'application.enable': '使用可能',
    'application.enableTip':
        'このアプリは維持されるか、デバイス上で利用可能な状態に切り替えられます。',
    'application.unavailable': 'このアプリはアップデート中は利用できなくなります。',
    'application.multiTimezoneSelected':
        'コマンドは、機器のローカルタイムゾーンで実行されます。（マルチタイムゾーンを選択した場合）',
    'application.selected': '選択済み',
    'application.applicationName': 'アプリ名',
    'application.appVersion': 'バージョン',
    'application.appSize': 'サイズ',
    'application.searchTip': '{val1}を検索',
    'application.reset': 'リセット',
    'application.search': '探す',
    'application.pleaseUpload': 'APKをアップロードしてください',
    'application.file.location': 'ファ場所',
    'application.file.tooltip':
        'このパッケージは、サイレントインストールをサポートしません。手動でインストールしてください。',
};
