export default {
    
        'common.noData': 'データなし',
        'common.unknownError': '不明なエラー。',
        'common.agreementTitle': 'Bytello DMS デバイス管理システムユーザー規約',
        'common.policyTitle': 'Bytello DMS デバイス管理システムのプライバシーポリシー',
        'common.quitExpPlanTitle': '[Bytello DMS デバイス管理システム]製品のユーザーエクスペリエンスプランを終了するための通知',
        'common.userExpPlanTitle': 'Bytello DMS デバイス管理システム製品のユーザーエクスペリエンスプラン',
        'common.filter.clear': 'フィルターをクリアする',
        'common.filter.apply': 'フィルタを適用する',
        'common.pleaseSelectDevice': 'デバイスを選択してください！',
        'common.selectCmd': 'コマンドを選択',
        'common.allTypes': 'すべてのタイプ',
        'common.soundBar': 'サウンドバー',
        'common.ifp': '電子黒板',
        'common.paginationTotal': '合計{val1}アイテム',
        'common.paginationTotal20Page': '20 /ページ',
        'common.paginationTotal40Page': '40 /ページ',
        'common.paginationTotal80page': '80 /ページ',
        'common.executeNow': '今すぐ実行',
        'common.recurring': '繰り返し',
        'common.timed': '時限',
        'common.powerOn': '電源オン',
        'common.powerOff': '電源を切る',
        'common.reboot': 'リブート',
        'common.bells': 'ベル',
        'common.screenLock': 'スクリーンロック',
        'common.blockList': 'ブロックリスト',
        'common.notification': 'テキスト',
        'common.announcement': 'マルチメディア',
        'common.filePublish': 'これを送信',
        'common.liveChannel': 'ライブチャンネル',
        'common.soundMode': 'サウンドモード',
        'common.imageMode': '画像モード',
        'common.powerState': '電源状態',
        'common.androidState': 'Androidの状態',
        'common.wallpaper': '壁紙',
        'common.logo': 'ブートロゴ',
        'common.emergency': 'アラート',
        'common.softwareUpdate': 'ソフトウェアの更新',
        'common.applicationInstall': 'アプリケーションのインストール',
        'common.applicationUninstall': 'アプリケーションのアンインストール',
        'common.applicationAble': 'アプリケーション（有効化/無効化）',
        'common.inputSwitch': '入力スイッチ',
        'common.actions': '行動',
        'common.selectGroup': 'グループを選択',
        'common.deviceControl': 'デバイス制御',
        'common.message': 'メッセージ',
        'common.deviceSetting': 'デバイスの設定',
        'common.allGroup': 'すべてのグループ'
      
};
