export default {
    'dashboard.title': 'ダッシュボード',
    'dashboard.activeTrend': 'オンライントレンド',
    'dashboard.statisticsTheDaily': 'すべてのデバイスの毎日のオンラインステータスを統計します',
    'dashboard.inactiveDevice': 'オフラインデバイス',
    'dashboard.devices': 'デバイス',
    'dashboard.deviceOffline': 'デバイスが7日以上オフライン',
    'dashboard.deviceName': '装置名',
    'dashboard.Tags': 'タグ',
    'dashboard.lastOnlineTime': '最後のオンライン時間',
    'dashboard.adminAccount': '管理者アカウント',
    'dashboard.organizationCode': '組織コード',
    'dashboard.maxConnection': '最大接続',
    'dashboard.connectedNum': '登録済みのデバイス',
    'dashboard.onlineNum': 'オンラインデバイス',
    'dashboatd.date': '日付',
    'dashboatd.onlineNumber': 'オンライン番号',
    'dashboard.credits': 'クレジット',
    'dashboard.daysRemain': '残存日数',
};
