export default {
    'deviceDetail.all': 'すべて',
    'deviceDetail.unbindDevice': 'デバイスのグループ化を解除',
    'deviceDetail.allDeviceDataErased': 'すべてのデバイスデータが消去されます。',
    'deviceDetail.deviceWillUnbind': 'デバイス{deviceName}は{unitName}からグループ化解除されます。',
    'deviceDetail.unbind': 'グループ化解除',
    'deviceDetail.noData': 'データなし',
    'deviceDetail.group': 'グループ：{val1}',
    'deviceDetail.deviceId': 'デバイスID',
    'deviceDetail.model': 'モデル',
    'deviceDetail.osVersion': 'OSバージョン',
    'deviceDetail.operationOs': 'OS',
    'deviceDetail.processerCPU': 'ProcesserCPU',
    'deviceDetail.touchFrame': 'タッチフレーム',
    'deviceDetail.DMSVersion': '{type} バージョン',
    'deviceDetail.devicesInCommands': 'スケジュールされたコマンドのデバイス',
    'deviceDetail.commands': 'コマンド',
    'deviceDetail.mode': 'モード',
    'deviceDetail.commandOwner': 'コマンド所有者',
    'deviceDetail.time': '時間',
    'deviceDetail.ram': 'RAM',
    'deviceDetail.storage': 'ストレージ',
    'deviceDetail.deviceInGroup': 'グループ内のデバイス',
    'deviceDetail.groupName': 'グループ名',
    'deviceDetail.tags': 'タグ',
    'deviceDetail.selectAtag': 'タグを選択するか、作成します',
    'deviceDetail.add': '追加',
    'deviceDetail.deviceName': 'デバイス名',
    'deviceDetail.deviceNameIsNull': 'デバイス名を入力してください',
    'deviceDetail.onlyLettersHint': '半角英数字と記号-/のみが許可されます。',
    'deviceDetail.tagIsNull': 'タグを入力してください',
    'deviceDetail.lettersNumberAllowed': '半角英数字のみが許可されます。',
    'deviceDetail.tagsExists': 'タグが存在します！',
    'deviceDetail.addNew': '新しく追加する',
    'deviceDetail.deviceInfomation': 'デバイス情報',
    'deviceDetail.deviceDetails': 'デバイスの詳細',
    'deviceDetail.application.enable': '有効にする',
    'deviceDetail.application.enableTip':
        '有効にすると、このアプリはデバイスで利用できるようになります。',
    'deviceDetail.application.disable': '無効にする',
    'deviceDetail.application.disableTip':
        '無効にすると、このアプリはアンインストールされますが、デバイスで利用できます。',
    'deviceDetail.application.processing': '処理中...',
    'deviceDetail.application.updateTip': '更新中はアプリケーションを利用できなくなります。',
    'deviceDetail.application.update': '更新',
    'deviceDetail.application.uninstall': 'アンインストール',
    'deviceDetail.application.uninstallTip':
        'アプリケーションはデバイスからアンインストールされます。',
    'deviceDetail.application.cmdSentWaitForExec':
        'コマンドが送信され、デバイスがオンラインで実行されるのを待ちます。',
    'deviceDetail.application.applicationManagement': 'アプリケーション管理',
    'deviceDetail.application.refreshed': '更新',
    'deviceDetail.application.clickToRefresh': 'クリックして更新',
    'deviceDetail.application.thirdPartyApps': 'サードパーティのアプリ',
    'deviceDetail.application.nativeApps': 'ネイティブアプリ',
    'deviceDetail.execTime': '実行時間',
    'deviceDetail.deviceType': 'デバイスタイプ',
    'deviceDetail.SerialNo': 'シリアル番号.',
    'deviceDetail.useageDataForToday': '今日の使用状況データ',
    'deviceDetail.deviceUseage': 'デバイス使用状況データ',
    'deviceDetail.appUseage': 'アプリケーション使用状況データ',
    'deviceDetail.timeOfUse': 'アプリケーション使用回数',
    'deviceDetail.countTheTime': '各アプリケーションの使用回数を数える',
    'deviceDetail.useTime': 'アプリケーションの使用時間',
    'deviceDetail.countTheTotal': '各アプリケーションによって累積された合計時間をカウントします',
    'deviceDetail.bootTimes': 'オンライン頻度',
    'deviceDetail.bootTime': 'デバイスの使用時間',
    'deviceDetail.tab.basic': '基本',
    'deviceDetail.tab.commands': 'コマンド',
    'deviceDetail.tab.useage': 'データ',
    'deviceDetail.tab.application': 'アプリ',
    'deviceDetail.onlineTime': 'オンライン時間',
    'deviceDetail.noAppHint': '使用したことがない',
    'deviceDetail.online': 'オンライン',
    'deviceDetail.offline': 'オフライン',
    'deviceDetail.notify': 'リアルタイム表示通知',
    'deviceDetail.today': '今日',
    'deviceDetail.yesterday': '昨日',
    'deviceDetail.last7': '過去7日間',
    'deviceDetail.last30': '過去30日間',
    'deviceDetail.onlineTrends': 'オンライントレンド',
    'deviceDetail.tooltipTime': '時間',
    'deviceDetail.activeDays': '活動日',
    'deviceDetail.onlineRate': 'オンライン料金',
    'deviceDetail.networkInterface': 'ネットワークインターフェース',
    'deviceDetail.macAdress': 'Macアドレス',
    'deviceDetail.IPAdress': 'IPアドレス',
    'deviceDetail.disconnected': '切断された',
    'deviceDetail.Fold': '折る',
    'deviceDetail.Expand': '拡大する',
    'deviceDetail.application.disable.hide.slider': '無効-サイドバーツールを非表示',
    'deviceDetail.application.disable.show.slider': '無効-サイドバーツールを表示',
};
