export default {
    'menu.home': 'ホーム',
    'menu.dashboard.dashboard': 'ダッシュボード',
    'menu.deviceManagement': 'デバイス',
    'menu.deviceManagement.allTypes': 'いろんなタイプ',
    'menu.deviceManagement.ifp': 'IFP',
    'menu.deviceManagement.soundBar': 'Sound bar',
    'menu.deviceManagement.ledWall': 'Led wall',
    'menu.functions': '高度な',
    'menu.functions.profile': 'プロフィール',
    'menu.functions.appManage': 'アプリケーション',
    'menu.functions.inputSwitch': '入力スイッチ',
    'menu.functions.firmwareUpdate': 'ファームウェアの更新',
    'menu.functions.softwareUpdate': 'アップデート',
    'menu.commandRecords': '記録',
    'menu.commandRecords.exeHistory': '歴史',
    'menu.commandRecords.inSchedule': 'スケジュール中',
    'menu.user.userManagement': 'ユーザー管理',
    'menu.account.accountSettings': 'アカウント設定',
    'menu.systemManage': 'システム',
    'menu.systemManage.adminManage': 'ユーザー',
    'menu.systemManage.schoolManage': '組織',
    'menu.systemManage.passwordManage': 'パスワード',
    'menu.systemManage.userSettings': '設定',
    'menu.resources.resources': '資源',
    'global.error.network': 'ネットワークエラー',
    'global.network.timeout': 'タイムアウト',
    'global.network.error': 'インターネットエラー',
    'global.btn.ok': 'OK',
    'upload.getUploadPolicyError': 'アップロードに失敗しました',
    'upload.networkError': 'アップロードに失敗しました',
    'upload.cancelled': 'タスクのアップロードをキャンセルしてください！',
    'upload.formatError': 'ファイル形式エラー',
    'upload.fileNameError': 'ファイル名が長すぎます',
    'upload.parsing': '解析中…',
    'upload.fileExist': 'ファイルはすでに存在します',
    'upload.fileNameTooLong': 'ファイル名が長すぎます',
    'upload.fileJPG': 'ファイルはJPG形式である必要があります',
    'upload.file3M1920': 'ファイルサイズは3MB以内（1920 * 1080）である必要があります',
    'upload.formatJPG': 'フォーマット：JPG',
    'upload.size3M': 'サイズ：最大3MB（1920x1080）',
    'global.cancel': 'キャンセル',
    'global.save': '保存する',
    'global.confirm': '確認',
    'global.send': '送信',
    'global.delete': '削除',
    'global.close': '閉じる',
    'global.commandSent': 'コマンドが送信されました',
    'global.unableSend': '送信できません',
    'global.commandSave': 'コマンドを保存しました',
    'global.unableSave': '保存できません',
    'global.commandDelete': 'コマンドが削除されました',
    'global.unableDelete': '削除できません',
    'global.empty': '空の',
    'header.infoCenter': '情報センター',
    'header.allSchool': '全校',
    'header.sendAll': '全て送る',
    'header.todayCommand': '今日のコマンド',
    'header.admin': '管理者',
    'header.expired':'期限切れ',
    'header.trial': 'トライアル',
    'header.feedback': 'フィードバックを送信する',
    'header.inactive': '非活性',
    'header.emergency': '緊急',
    'global.lockTip':
        'その後、アカウントがロックされ、アクティベーションコードがメールに送信されます。',
    'global.loading': '読み込み中',
    'global.accept': '受け入れる',
    'global.reject': '拒否する',
    'global.protocplTip1': 'サインアップすることで、私は ',
    'global.protocplTip2': 'の受け入れを確認します ',
    'global.userAgreeement': 'ユーザー規約',
    'global.policy': '個人情報保護方針',
    'global.pleaseCheck': 'ユーザー契約とプライバシーポリシーを確認してください。',
    'global.switchDefaultTip': 'スイッチをオンにして、時間と繰り返しコマンドを設定します。',
    'global.noResults': '結果がありません',
    'global.off': 'オフライン',
    'global.on': 'オンライン',
    'global.language': '言語',
    'global.enroll': '登録する',
    'global.last': 'ラスト',
    'global.next': '次',
    'global.continue': '続行',
    'global.saveChanges': '変更を保存',
    'global.mode': 'モード',
    'global.tags': 'タグ',
    'global.detail': '詳細',
    'global.update.time': '更新時間',
    'global.not.configured': '構成されていません',
    'global.save.and.sync': '保存して同期',
    'global.license': 'ライセンス',
    'global.day.remaing': '残り日',
    'global.linces.records': '記録',
    'global.license.helper.title':
        '残り日数は、このアカウントが製品にアクセスする必要がある時間の長さです。',
    'global.license.helper.tip1':
        'アクセス時間長= [期限切れ時間]と[クレジット/登録デバイス]の間の最小値',
    'global.license.helper.tip2': '[期限切れ]有効期限までに使用できる日の数です。',
    'global.license.helper.tip3':
        '[クレジット/登録デバイス]は、残りのクレジットサポートが登録されたデバイスで使用されている日の数です。',
    'global.uploading':'アップロード',
    'global.leave': '離れる',
    "global.change":"変化する",
    "global.sending":"送信",
    "global.get.code":"コードを取得",
    "global.resend.code":"コードを再送する",
    "global.change.email":"メールアドレスを変更",
    "global.unknow.error":"不明なエラー"
};
