export default {
    'group.deviceName': 'デバイス名',
    'group.timezone': 'タイムゾーン',
    'group.groupManagement': 'グループ管理',
    'group.delGroupTip': 'このグループを削除しますか？',
    'group.del': '削除',
    'group.quit': '終了する',
    'group.popBtnText': '{val1}グループを終了しますか？',
    'group.create': '作成する',
    'group.save': '保存',
    'group.enterGroupName': 'ここにグループ名を入力してください',
    'group.creating': '作成',
    'group.modify': '変更する',
    'group.addNew': '新しいグループを追加する',
    'group.all': 'すべて',
    'group.allDevices': 'すべてのデバイス{val1} / {val2}',
    'group.selectedDevices': '選択したデバイス{val1}',
    'group.conditionLimit': '条件制限に達しました',
    'group.addCondition': '条件を追加',
    'group.autoAllocation': '自動割り当て',
    'group.manualSelection': '手動選択',
    'group.enterConditionHere': 'ここに条件を入力してください',
    'group.enterCondition': '条件を入力してください',
    'group.select': '選択する'
  };
