export default {
    'channel.message.error': 'チャンネルを選択してください ',
    'channel.select.placehoder': 'チャネルを選択します',
    'channel.live.name': 'チャンネル名',
    'channel.live.title': 'ライブチャンネルリスト',
    'channel.modal.title': 'チャネルを削除?',
    'channel.modal.content': 'このチャンネルを削除しますか？',
    'channel.modal.oktext': '削除',
    'channel.form.nameerror': '名前を空にすることはできません',
    'channel.form.addresserror': 'アドレスを空にすることはできません。',
    'channel.form.formaterror': 'アドレス形式がエラーです。',
    'channel.btn.create': '作成する',
    'channel.btn.span': 'サポートされているプロトコル：RTMP、RTSP、およびHTTPライブストリーミング',
    'channel.form.title': 'ライブチャンネルの作成',
    'channel.form.labelname': 'チャンネル名',
    'channel.form.labeladdress': 'アドレス',
    'channel.live.label': 'ライブチャンネル',
    'channel.btn.channellist': 'チャンネルリスト',
    'channel.form.addressholder': 'チャネルのURL',
    'channel.name.exist': 'チャネルはすでに存在します！',
    'channel.preview.notsupport': 'このライブチャンネルではプレビューはサポートされていません',
    'channel.btn.newcreate': 'ライブチャンネルを作成してください',
    'channel.edit.livechannel': 'ライブチャンネル',
    'channel.edit.save': '保存',
};
