export default {
    'login.error.emailEmpty': 'メールアドレスを入力してください。',
    'login.error.emailInvalid': '申し訳ありませんが、このメールアドレスは無効です。',
    'login.error.emailLetterInvalid': '申し訳ありませんが、半角英数字と記号（@ ._）のみが許可されています。',
    'login.error.emailNotFound': 'このメールでアカウントが見つかりません。',
    'login.error.createWidthAccount': 'このアカウントで作成しますか？',
    'login.error.pwdEmpty': 'パスワードを入力してください。',
    'login.error.pwdInvalid': '申し訳ありませんが、このパスワードは正しくありません。',
    'login.error.pwdEqualMail': '申し訳ありませんが、パスワードはあなたのメールアドレスと一致しません',
    'login.error.pwdLength': 'パスワードは8〜16文字である必要があります。',
    'login.error.pwdFormat': 'パスワードには、以下の2つのカテゴリが必要です：数字/文字/特殊文字',
    'login.error.specialSymbol': '申し訳ありませんが、半角英数字、および特殊文字（〜！@ ＃$％^＆*（）+-=、。/; | <>？）のみが許可されます',
    'login.error.pwdNotEqual': 'パスワードが一致しませんでした',
    'login.error.notLogin': 'ログインしていません。ログインしてください。',
    'login.error.verify': '確認してください',
    'login.label.forgotPwd': 'パスワードをお忘れですか？',
    'login.label.email': 'Eメール',
    'login.label.notAccount': 'アカウントがありませんか？',
    'login.label.createAccount': '作成する',
    'login.label.pwd': 'パスワード',
    'login.title.account': 'アカウント',
    'login.title.login': 'ログインする',
    'login.title.tips': 'ヒント',
    'login.btn.login': 'ログインする',
    'login.btn.confirm': '確定',
    'login.btn.ok': 'OK',
    'login.placeHolder.email': 'メールアドレスを入力してください',
    'login.placeHolder.pwd': 'パスワードを入力してください',
    'login.logout': 'ログアウト',
    'login.error.noAuth': 'アカウントが承認されていません。',
    'login.forgetPwd': 'パスワードをお忘れですか',
    'login.forgetTip': 'メールアドレスを入力すると、パスワードをリセットするための確認コードのリンクが送信されます。',
    'login.verifyAgain': 'エラーが発生しました。もう一度確認してください。',
    'login.next': '次',
    'login.backToLogin': 'ログインに戻る',
    'login.loginFailed': 'ログインに失敗しました',
    'login.accountExpired': 'アカウントの有効期限が切れています。親アカウントにお問い合わせください',
    'login.accountNoAuth': 'アカウントが承認されていません',
    'login.lockChances': '{val1}チャンス残っています',
    'login.resetSuc': 'リセットされました！ログインします…',
    'login.reset.characters816': '8〜16文字',
    'login.reset.charactersCategories': '以下から2つのカテゴリ：数字/文字/特殊文字',
    'login.reset.canNotMatch': 'メールアドレスが一致しません',
    'login.reset.curPwd': '現在のパスワード',
    'login.reset.newPwd': '新しいパスワード',
    'login.reset.confirmPwd': 'パスワードを確定する',
    'login.modifyPwd': 'パスワードの変更',
    'login.title.2FA': '2要素認証',
    'login.2FA.input.tip':'サードパーティのアプリから確認コードを入力します',
    "logout.text.tip":"ログアウトします"
  };
  