
export default {
    'noDevice.deviceManagement': '端末管理',
    'noDevice.enrollDevice': 'デバイスバインディング',
    'noDevice.deviceEnrollment': 'デバイスの登録',
    'noDevice.bindThrough': 'デバイス上の {type} アプリを介したバインド',
    'noDevice.adminAccIs': '管理者アカウント：',
    'noDevice.schoolCodeIs': '組織コード：',
    'noDevice.seeMore': 'あなたはでより多くの情報を見ることができます ',
    'noDevice.option1': 'オプション1',
    'noDevice.enterConnInfo': '接続情報を入力してください',
    'noDevice.option2': 'オプション2',
    'noDevice.enrollmentUsingUSB': 'USBを使用した登録',
    'noDevice.download': 'ダウンロード',
    'noDevice.inUDisk': `Uディスクでは、変更しないでください。`,
    'noDevice.makeSureTheApp': 'アプリケーションがインストールされていることを確認してください。',
    'noDevice.insertUDisk': 'Uディスクをデバイスに挿入します。',
    'noDevice.clickBind': 'バインドをクリックすると、情報が自動的に入力されます。',
    'noDevice.allSchoolHint': '登録で詳細情報を表示するには、組織を選択してください',
    'noDevice.netErr': 'ネットワークエラー。もう一度ダウンロードしてください',
};