export default {
    'profile.createNew': '新しい',
    'profile.time': 'で作成され {createTime}、で最後に変更されました {modifyTime}',
    'profile.set': 'デフォルトとして設定',
    'profile.apply': '応用',
    'profile.type': 'タイプ',
    'profile.applied': '適用',
    'profile.remove': '値を削除します',
    'profile.modal.apply': 'ション構成',
    'profile.modal.profilename': '構成名',
    'profile.detail.delete': '消去構成',
    'profile.detail.seeprofile': 'チェック',
    'profile.create.new': '{os}構成を作成する',
    'profile.create.edit': '{os}構成を編集する',
    'profile.create.security': '安全',
    'profile.create.app': 'アプリ管理',
    'profile.create.securitydes':
        'ブロッキング：ユーザーがWebサイトにアクセスできないように、リストWebサイトをブロックします。 許可リストにWebサイトを追加して、ユーザーが許可リスト以外のWebサイトにアクセスできないようにします。',
    'profile.create.appdes': 'アプリケーションのサイレントインストールをサポートします',
    'profile.create.appsettingdes': '電源、ディスプレイ、その他のデバイスステータスを設定します',
    'profile.create.config': '構成',
    'profile.create.checkprofilename': '構成名を空にすることはできません',
    'profile.create.checkurl': 'URLを空にすることはできません',
    'profile.create.whiteblack': 'ブロッキング',
    'profile.create.addurl': 'URLを追加',
    'profile.create.urls': 'URL',
    'profile.create.appremove': 'プロファイルの削除時にデバイスからアプリを削除します',
    'profile.create.appsmanagement': 'アプリ管理',
    'profile.create.installapps': 'トールします',
    'profile.create.addapps': 'アプリを追加',
    'profile.create.appname': '名前',
    'profile.create.sleep': '自動スリープ時間',
    'profile.create.sleepdes': '指定時間内に操作がない場合、自動的にスリープモードになります',
    'profile.create.poweroff': '自動シャットダウン',
    'profile.create.poweroffdes':
        'デバイスが一定期間操作されない場合、自動的にシャットダウンします',
    'profile.create.signal': '信号シャットダウンなし',
    'profile.create.signaldes': '信号入力がない場合の自動シャットダウン',
    'profile.create.powersetting': '停電設定',
    'profile.create.powersettingdes': '停電後にデバイスが再接続されたことが表示されます',
    'profile.create.wakeon': 'ウェイク',
    'profile.create.andriodchannel': 'Androidチャンネルを',
    'profile.create.andriodchanneldes': 'デバイスがAndroidチャネルに切り替えることを許可する',
    'profile.create.soundmode': 'サウンドモード',
    'profile.create.imagemode': '画像モード',
    'profile.create.imagemodedes': '画像モードはAndroid以外のチャンネルのみをサポートします',
    'profile.create.autoturnoff': '画面を自動的にオフにします',
    'profile.create.autoturnoffdes': '指定時間内に何も操作せずに自動的に画面をオフにします',
    'profile.create.sleepmode': 'デバイスを自動的にスリープモードにします',
    'profile.create.sleepmodedes':
        '指定された時間内に操作がない場合、デバイスを自動的にスリープモードにします',
    'profile.create.poweroffopt': '離れる',
    'profile.create.poweronopt': 'オンにする',
    'profile.create.powerlastopt': '最後',
    'profile.create.none': '一度もない',
    'profile.create.warning': 'V1.9.0以降のクライアントのみが構成ファイルの使用をサポートします',
    'profile.create.default': 'ディフォルト',
    'profile.create.savesuccess': '正常に保存',
    'profile.create.savefailed': '保存に失敗しました',
    'profile.modal.deletetitle': 'プロファイルを削除します',
    'profile.modal.deletecontent': 'プロファイルを削除してもよろしいですか？',
    'profile.create.enterurl': 'URLを入力',

    'profile.create.deletewhiteblack': 'ブロックの削除/許可',
    'profile.create.uninstallapps': 'アンインストール',
    'profile.create.wakeonopt': 'ウェイク',
    'profile.create.autochannelopt': 'Androidチャンネル',
    'profile.create.sleepmodeopt': 'スリープモード',
    'profile.route.title': 'プロファイルが保存されていません',
    'profile.route.content': 'プロファイルは保存されません。このページを離れてもよろしいですか？',
    'profile.app.size': 'サイズ：最大300MB',
    'profile.app.upfiles': '最大50個の',
    'profile.create.hidesidebar': 'サイドバーを非表示',
    'profile.data.and.time.format.automatically': '自動的',
    'profile.data.and.time.format.matically': '手動で',
    'profile.12.hour.time': '12時間制',
    'profile.24.hour.time': '24時間制',
    'profile.save.failed': '保存に失敗しました',
    'profile.save.failed.tip':
        'プロファイルを保存するには、すべての必須フィールドに入力するか、構成を閉じてください',
    'profile.device.general.settings': '一般設定',
    'profile.update.software': 'ソフトウェアの更新',
    'profile.associated.devices': '関連するデバイス',
    'profile.devices.num': 'デバイス',
    'profile.not-compliant.num': '非準拠',
    'profile.bytello.devices': 'Bytelloでのみ動作するデバイスでサポートされる設定',
    'profile.date.and.time.label': '日にち & 時間',
    'profile.date.and.time.helper': 'ネットワークが提供する時間を使用する',
    'profile.devices.time.zone': 'タイムゾーン',
    'profile.devices.time.format': '時間形式',
    'profile.devices.non.compliant': '非準拠',
    'profile.devices.compliant': '準拠',
    'profile.action.sync': '同期',
    'profile.devices.compoliant.status': 'デバイス-準拠ステータス',
    'profile.details': '詳細',
    'profile.applied.devices': '応用デバイス',
    'profile.create.brief1':
        'ポリシーは、DMSに登録されているデバイスを管理および保護するために設計された一連の構成と制限です。',
    'profile.create.brief2':
        'プロファイルをデフォルトとして設定した後、デバイスが組織に登録されると、デバイスは自動的にデフォルトのプロファイルを受信して実行します。',
    'profile.default.time.zone': '変更しないでください',
    'profile.set.default': 'デフォルトに設定',
    'profile.associated.status': 'デバイスの選択-準拠ステータス',
    'profile.associate': '仲間',
    'profile.devices': 'デバイス',
    'profile.add.devices': 'デバイスを追加する',
    'profile.associate.devices': 'デバイスを関連付ける',
    'profile.edit.savesuccess': '保存して正常に同期する',
};
