export default {
    'register.activateSchool': '組織を活性化する',
    'register.hasoOpenPer': ' {type} の許可を開きました。',
    'register.licenseInfo': 'License 情報',
    'register.licenseType': 'License タイプ',
    'register.maxPanel': '最大パネル',
    'register.avaTime': '利用可能な時間',
    'register.schoolInfo': '組織情報',
    'register.schoolCode': '組織コード',
    'register.adminAccount': '管理者アカウント',
    'register.schoolName': '組織名',
    'register.location': 'ロケーション',
    'register.hint': 'ご不明な点がございましたら、お問い合わせください ',
    'register.maxPanelHint': '数を増やす必要がある場合は、お問い合わせください ',
    'register.selectLocation': '国または地域を選択してください',
    'register.typeSchoolName': 'タイプの組織名',
    'register.schoolNameCannotRepeat': '地域内で組織名を繰り返すことはできません。',
    'register.selectLocationHint': '組織の場所を選択してください。',
    'register.inputNoEmpty': '入力を空にすることはできません。',
    'register.4Digit': '少なくとも4桁',
    'register.quantity': '量',
    'register.credits': 'クレジット',
};
