export default {
  'remote.detail.control': '画面制御',
  'remote.detail.realtime': 'リアルタイム表示',
  'remote.full.turnon':'画面制御がオンになっている',
  'remote.full.turnoff':'画面制御がオフになりました',
  'remote.full.control':'画面制御',
  'remote.full.exitcontrol':'出口制御',
  'remote.remote.control':'リモコン: ',
  'remote.preview.off':'デバイスがオフになっています',
  'remote.preview.getscreen':'画面の取得...',
  'remote.video.offline':'このデバイスはオフラインです。デバイスのステータスまたはネットワークのステータスを確認してください',
  'remote.video.error':'このデバイスは別のユーザーによって接続されています。 後でもう一度やり直してください',
  'remote.video.failedtitle':'このデバイスはオフラインです。',
  'remote.video.try':'試してみてください',
  'remote.video.checkpower':'·デバイスの電源とネットワークステータスを確認します',
  'remote.video.buttonreconnect':'·下のボタンをクリックして、再接続を試みてください',
  'remote.video.button':'再接続',
  'remote.video.loading':'読み込み中',
  'remote.command.tooltip':'今すぐ実行',
  'remote.command.poweron':'電源オン',
  'remote.command.poweroff':'電源を切る',
  'remote.command.reboot':'リブート',
  'remote.command.lock':'ロック',
  'remote.command.unlock':'解除する',
  'remote.pop.power':'デバイスの電力',
  'remote.pop.lock':'ロック',
  'remote.reject.title':'デバイスユーザーが拒否しました',
  'remote.reject.conent':'リモコンにはユーザーの許可が必要です。使用する前にユーザーに相談してください。',
  'remote.reject.okexit':'出口',
  'remote.reject.ok':'いいです',
  'remote.device.touch':'デバイスタッチ',
  'remote.tooltip.waiting':'許可を待っています',
};
