export default {
    'user.title': 'アカウント管理',
    'user.username': 'ユーザー名',
    'user.account': 'アカウント',
    'user.role': '役割',
    'user.latestOperation': '最近の操作',
    'user.deviceNum': 'デバイス番号',
    'user.commandNum': 'コマンド番号',
    'user.remotePwd': '{type}パスワード',
    'user.screenLockPwd': '画面ロックパスワード',
    'user.details': '詳細',
    'user.remotePwdStatus.disabled': '無効',
    'user.remotePwdStatus.visible': '表示',
    'user.remotePwdStatus.invisible': '非表示',
    'user.createSubAccount': 'サブアカウントを作成する',
    'user.noAccountHint': '最初にサブアカウントを作成してください',
    'user.deleteSucHint': 'サブアカウント{account}が{unitName}から削除されました。',
    'user.delete': '削除',
    'user.deleteSubAccount': 'サブアカウントを削除する',
    'user.deleteConfirm': '{unitName}から{account}を削除しますか？ ',
    'user.anEmailWillSent': '{account}にメールが送信されます。',
    'user.addAccountSucHint': '{email}が{unitName}に追加されました。',
    'user.addAccountErrHint': 'サブアカウントの作成に失敗しました。',
    'user.information': '情報',
    'user.device': 'デバイス',
    'user.permission': '許可',
    'user.prev': '前へ',
    'user.create': '作成する',
    'user.next': '次',
    'user.createAPwd': '次のようなパスワードを作成します。',
    'user.816Characters': '8〜16文字',
    'user.twoCategories': '以下から2つのカテゴリー：数字/文字/特殊文字',
    'user.cannotMatchEmail': 'メールアドレスが一致しません',
    'user.accountAlreayHas': 'このアカウントはすでに学校のサブアカウントとして存在します。',
    'user.emailCheckEmpty': 'メールアドレスを入力してください。',
    'user.emailCheckHasSpecialSymbol': '申し訳ありませんが、半角英数字と記号（@ ._）のみが許可されています。',
    'user.emailCheckFormat': '申し訳ありませんが、このメールは無効です。',
    'user.pwdCheckEmpty': 'パスワードを入力してください。',
    'user.pwdCheckMatch': '申し訳ありませんが、パスワードがメールアドレスと一致しません。',
    'user.pwdCheckLength': 'パスワードは8文字以上である必要があります。',
    'user.pwdCheckHasSpecialSymbol': '申し訳ありませんが、半角英数字、および特殊文字（〜！@ ＃$％^＆*（）+-=、。/; \\ | <>？）のみが許可されます',
    'user.pwdCheckFormat': 'パスワードには、以下の2つのカテゴリが必要です：数字/文字/特殊文字。',
    'user.usernameCheckEmpty': 'ユーザー名を入力してください。',
    'user.usernameCheckFormat': '申し訳ありませんが、半角英数字のみが許可されています',
    'user.password': 'パスワード',
    'user.accountMatched': 'アカウントが一致しました',
    'user.enterAnEmail': 'メールアドレスを入力',
    'user.modify': '変更',
    'user.verify': '確認',
    'user.deviceName': 'デバイス名',
    'user.coAdministrator': '共同管理者',
    'user.selected': '選択済み',
    'user.allDevices': 'すべてのデバイス',
    'user.permissionAuth': '以下に承認された許可：',
    'user.pwdPermission': 'パスワードの許可',
    'user.allCommands': 'すべてのデバイス',
    'user.emerHint': 'デバイスに緊急メッセージを送信します。',
    'user.notificationHint': 'スクロールメッセージをデバイスに送信します。',
    'user.announcementHint': 'ビデオ/画像メッセージをデバイスにプッシュします。',
    'user.filePublishHint': 'デバイスにファイルを送信します。',
    'user.powerStateHint': 'デバイスの電源を入れた後、ステータス表示を設定します。',
    'user.androidStateHint': 'Androidチャンネルの表示を設定します。',
    'user.wallpaperHint': 'デバイスの壁紙をリモートで変更します。',
    'user.logoHint': '起動時のロゴをリモートで変更します。',
    'user.input': '入力',
    'user.hours': '{time}時間で期限切れ',
    'user.days': '{time}日で期限切れ',
    'user.yearsDays': '{year}年{days}日で期限切れ',
    'user.years': '{year}年で期限切れ',
    'user.hoursLeft': '{time}残り時間',
    'user.daysLeft': '{time}残り日数',
    'user.yearsDaysLeft': '{year}年{days}残り日',
    'user.yearsLeft': '{year}残り年',
    'user.addUser': 'ユーザーを追加する',
    'user.allDevicesAndGroups': 'すべてのグループとデバイス',
    'user.enterRoleName': 'ここに役割名を入力してください',
    'user.standard':'標準',
    'user.email.change.title1':'アカウントのメールアドレスを変更する',
    'user.email.change.tip1':'アカウントのメールアドレスを変更するための確認コードのリンクをお送りします。',
    'user.email.change.title2':"続行することを確認します",
    "user.email.change.tip2":"助けが必要？ {val1}に連絡してください",
    "user.email.change.title3":"アカウントのメールアドレスを変更する",
    "user.email.change.tip3":"変更組織の管理者はログアウトします。 ログインパスワードは変更後も変わりません。",
    "user.email.change.new.input.tip":"新しいメール",
    "user.email.change.input.placeholder":"ここに新しいメールアドレスを入力してください",
    "user.email.change.success.tip":"アカウントのメールアドレスが正常に変更されました。",
    "user.email.change.fail.txt":"申し訳ありませんが、このメールは登録されています。"

  };
