export default {
    'userDetail.pwdPermission': 'パスワードの許可',
    'userDetail.authCommands': '許可されたコマンド',
    'userDetail.manage': '管理する',
    'userDetail.authCommandsSave': '許可されたコマンドが保存されました。',
    'userDetail.unableSave': '保存できません。',
    'userDetail.authDevicesSave': '許可されたコマンドが保存されました。',
    'userDetail.commandAuthFor': '以下のコマンド許可 ：',
    'userDetail.device': 'デバイス',
    'userDetail.label': 'ラベル',
    'userDetail.deviceAuthFor': '以下のデバイス許可:',
    'userDetail.authDevices': '許可されたデバイス',
    'userDetail.deviceNo': 'デバイス番号',
    'userDetail.authGroup': '許可されたグループ',
    'userDetail.roleCannotDel': 'ロールは削除できません。',
    'userDetail.userIsUsing': 'このロールを使用しているユーザー：',
    'userDetail.deleteRole': '役割を削除しますか？',
    'userDetail.roleName': '役割名',
    'userDetail.customRole': 'カスタムロール',
    'userDetail.roleList': '役割リスト',
    'userDetail.allDevicesAndGroup': 'すべてのデバイスとグループ',
    'userDetail.createDeviceGroup': 'デバイスグループを作成する',
    'userDetail.deleteGroup': 'このグループをから削除します {username}?',
    'userDetail.switchRoleHint': '{role}の役割を切り替えてもよろしいですか ?',
    'userDetail.userInfomation': 'ユーザー情報',
    'userDetail.switchRole': '役割の切り替え',
    'userDetail.createSucc': '正常に作成',
    'userDetail.operatorHint': 'オペレーター：このユーザーは、プラットフォームのあらゆる側面で行動する完全な権限を持っています。',
    'userDetail.viewerHint': '閲覧者：このユーザーは、デバイス、ユーザー、登録、およびアプリケーション情報のみを表示できます。 Intuneに変更を加えることはできません。',
    'userDetail.customHint': 'カスタムロール：カスタム権限を持つロールを作成します。',
    'userDetail.roleNameExists': 'ロール名{name}はすでに存在します',
    'userDetail.createAGroup': 'グループを作成する'
  };
