export default {
    'account.accountInfo': 'Konto-Verwaltung',
    'account.account': 'Konto',
    'account.username': 'Benutzername',
    'account.resetPswd': 'Passwort zurücksetzen',
    'account.resetPswdTip1':
        'Nach dem Zurücksetzen des Passworts wird dieses Konto automatisch abgemeldet. ',
    'account.resetPswdTip2':
        'Vorsicht: Fall Sie andere Benutzerzentrums-Produkte genutzt haben, wird das Passwort synchron aktualisiert.',
    'account.pswdManagement': 'Passwort-Verwaltung',
    'account.password': 'Passwort',
    'account.remoteLock': 'Passwort für {type}-Sperre',
    'account.password.remoteLock.desc':'Geben Sie das Passwort ein, um das Gerät abzumelden.',
    'account.remoteLockDesc':
        'Sperren Sie {type} in den Einstellungen. Das Passwort zum Entsperren eingeben.',
    'account.deviceSettingLock': 'Sperrung der Geräteeinstellungen',
    'account.deviceSettingLockDesc':
        'Die Einstellungen auf dem Gerät sperren. Das Passwort zum Entsperren eingeben.',
    'account.screenLock': 'Passwort für die Bildschirmsperre',
    'account.screenLockDesc':
        'Den Gerätebildschirm für einen bestimmten Zeitraum sperren. Das Passwort zum Entsperren eingeben.',
    'account.school': 'Organisation',
    'account.schoolName': 'Organisationsname',
    'account.state': 'Status',
    'account.admin': 'Administrations-Manager',
    'account.email': 'E-Mail',
    'account.schoolCode': 'Organisationscode',
    'account.serverManagement': 'WOL-Server',

    'account.serverName': 'Servername',
    'account.powerState': 'Server Status',
    'account.connectNum': 'Verbundene Nr.',
    'account.delete': 'Löschen',
    'account.deleteServer': 'Server löschen',
    'account.delServerTip': 'Möchten Sie {serverName} von {unitName} löschen?',
    'account.delServerSuc': 'Server {serverName} von {unitName} gelöscht.',
    'account.serverOff': 'Nicht verfügbar',
    'account.serverOn': 'Verfügbar',
    'account.about': 'Über',
    'account.legalInfo': 'Rechtshinweis',
    'account.userExpPlan': 'Benutzererfahrungsplan',
    'account.userExpPlan1': 'Benutzererfahrungsplan >',
    'account.OK': 'OK',
    'account.accept': 'Annehmen',
    'account.quit': 'Beenden',
    'account.userArgeement': 'Nutzervereinbarung >',
    'account.privacyPolicy': 'Datenschutzrichtlinie >',
    'account.openLicense': 'Opensource-Lizenz >',
    'account.pleaseEnterPswd': 'Bitte geben Sie Ihr Passwort ein.',
    'account.pswdLen6': 'Passwörter müssen 6 Zeichen enthalten.',
    'account.pswdOnlyNumber': 'Es sind leider nur Zahlen (0-9) erlaubt.',
    'account.userNameValidateInfo':
        'Leider sind nur Buchstaben (a-z), Zahlen (0-9) und Zeichen (@,_) erlaubt.',
    'account.logout': 'Abmelden',
    'account.userName': 'Benutzername',
    'account.edit': 'Bearbeiten',
    'account.pswd': 'Passwort',
    'account.reset': 'Zurücksetzen',
    'account.location': 'Ort',
    'account.adminUserName': 'Admin',
    'account.adminAccount': 'Administrator-Konto',
    'account.schoolInfoMod': 'Änderung der Organisationsdaten',
    'account.deleteConfirm': 'Möchten Sie das {account} von {unitName} löschen?',
    'account.anEmailWillSent': 'Es wird eine E-Mail an {Konto} gesendet.',
    'account.serverManagement.hint':
        'Wake-on-LAN (WoL) ist ein Ethernet- oder Token Ring-Computernetzwerkstandard, mit dem ein Computer durch eine Netzwerknachricht eingeschaltet oder aktiviert werden kann.',
    'account.notConnectHint': '{num} Geräte, die mit keinem Server verbunden sind',
    'account.connectedDeivces': 'Verbundene Geräte',
    'account.two.factor.authentication': '2-Faktor-Authentifizierung',
    'account.2FATip':
        'Wenn die Zwei-Faktor-Authentifizierung aktiviert ist, müssen Sie einen Bestätigungscode eingeben, um sich bei Bytelo DMS anzumelden',
    'account.error.twoFA.isEmpty': 'Bitte geben Sie den 6-stelligen Bestätigungscode ein',
    'account.Authenticate.password.title': 'Authentifizieren, um fortzufahren',
    'account.disable.2FA.title': '2-Faktor-Authentifizierung deaktivieren',
    'account.Authenticate.password.label': 'Geben Sie Ihr Kontopasswort ein',
    'account.Authenticate.password.confirm': 'Authentifizieren',
    'account.enable.2FA.title': '2-Faktor-Authentifizierung aktivieren',
    'account.Authenticate.tip':
        'Aktivieren Sie die 2-Faktor-Authentifizierung, um sicherzustellen, dass Ihr Konto mehr Sicherheit bietet. Bitte installieren Sie Google Authenticator oder Microsoft Authenticator',
    'account.Authenticate.ScanCode.title':
        '1 / Scannen Sie diesen ODER-Code mit Ihrer Verifizierungs-App',
    'account.Authenticate.ScanCode.cannotScan': 'Sie können diesen ODER-Code nicht scannen?',
    'account.Authenticate.code.text.title':
        'Geben Sie diesen Code in die Authentifizierungs-App ein:',
    'account.Authenticate.input.title':
        '2 / Geben Sie den 6-stelligen Verifizierungscode von Ihrer Verifizierungs-App ein',
    'account.error.faInvalid': 'Ungültiger Bestätigungscode',
    'account.Authenticate.2fa.enable': 'Aktivieren',
    'account.success.enable.fa': '2-Faktor-Authentifizierung erfolgreich aktivieren',
    'account.success.disable.fa': '2-Faktor-Authentifizierung deaktiviert',
    'account.disable.2FA': '2FA deaktivieren',
};
