export default {
    'cmdRecords.execHistory.recallSent': 'Rückrufbefehl gesendet.',
    'cmdRecords.execHistory.unableSent': 'Senden nicht möglich.',
    'cmdRecords.execHistory.unlockSent': 'Entsperr-Befehl gesendet.',
    'cmdRecords.execHistory.cmdSent': 'Befehl gesendet',
    'cmdRecords.cmdInSchedule.timed': 'Terminiert',
    'cmdRecords.cmdInSchedule.recurring': 'Wiederkehrend',
    'cmdRecords.updateTime': 'Zeit aktualisieren',
    'cmdRecords.cmdName': 'Befehlsname',
    'cmdRecords.cmdOwner': 'Befehlsinhaber',
    'cmdRecords.timeMode': 'Zeitmodus',
    'cmdRecords.devices': 'Geräte',
    'cmdRecords.cmdStatus': 'Befehlsstatus',
    'cmdRecords.details': 'Details',
    'cmdRecords.executed': 'Ausgeführt',
    'cmdRecords.unexecuted': 'Nicht ausgeführt',
    'cmdRecords.recalled': 'Zurückgerufen',
    'cmdRecords.deviceCmdExecTable.settingFailed': 'Einstellung fehlgeschlagen',
    'cmdRecords.deviceCmdExecTable.systemError': 'Systemfehler',
    'cmdRecords.deviceCmdExecTable.unknownError': 'Unbekannter Fehler',
    'cmdRecords.deviceCmdExecTable.resetFail': 'Fehler zurücksetzen',
    'cmdRecords.deviceCmdExecTable.downloadError': 'Downloadfehler',
    'cmdRecords.deviceCmdExecTable.rejectByUser': 'Durch Benutzer ablehnen',
    'cmdRecords.deviceCmdExecTable.notImplemented': 'Diese Funktion ist nicht implementiert',
    'cmdRecords.deviceCmdExecTable.cmdCovered': 'Befehl abgedeckt',
    'cmdRecords.deviceCmdExecTable.notSupport': 'In Android nicht unterstützt',
    'cmdRecords.deviceCmdExecTable.unsupportResetWallpaper':
        'Zurücksetzen des Hintergrundbildes nicht unterstützt',
    'cmdRecords.deviceCmdExecTable.alreadyExists': 'Existiert bereits',
    'cmdRecords.deviceCmdExecTable.installConflict': 'Installationskonflikt',
    'cmdRecords.deviceCmdExecTable.versionTooOld': 'Version zu alt',
    'cmdRecords.deviceCmdExecTable.insufficientStorage': 'Nicht ausreichend Speicherplatz',
    'cmdRecords.deviceCmdExecTable.formatNotSupport': 'Format nicht unterstützt',
    'cmdRecords.deviceCmdExecTable.userRestricted': 'Benutzer beschränkt',
    'cmdRecords.deviceCmdExecTable.installError': 'Installationsfehler',
    'cmdRecords.deviceCmdExecTable.channelNameEmpty': 'Der Sendername ist leer',
    'cmdRecords.deviceCmdExecTable.nonExist': 'Nicht existent',
    'cmdRecords.deviceCmdExecTable.switchFailed': 'Wechsel fehlgeschlagen',
    'cmdRecords.deviceCmdExecTable.timeout': 'Zeitlimit',
    'cmdRecords.deviceCmdExecTable.deviceIsOff': 'Das Gerät ist ausgeschaltet',
    'cmdRecords.deviceCmdExecTable.deviceNotExists': 'Das Gerät existiert nicht',
    'cmdRecords.deviceCmdExecTable.virtualDeviceNotSupport':
        'Das virtuelle Gerät wird nicht unterstützt',
    'cmdRecords.deviceCmdExecTable.wolNotEnabled':'WOL nicht aktiviert',
    'cmdRecords.deviceCmdExecTable.withdrawal': 'Rücknahme',
    'cmdRecords.deviceCmdExecTable.waitForExecute': 'auf Ausführung warten',
    'cmdRecords.deviceCmdExecTable.deviceUnbound': 'Gerät losgebunden',
    'cmdRecords.deviceCmdExecTable.expired': 'abgelaufen',
    'cmdRecords.deviceCmdExecTable.noBinding': 'Keine Bindung',
    'cmdRecords.deviceCmdExecTable.wakeServerNotExists': 'Wake-Server nicht vorhanden',
    'cmdRecords.deviceCmdExecTable.wakeServerIsOff': 'Wake-Server ist ausgeschaltet',
    'cmdRecords.deviceCmdExecTable.cmdNotSupported': 'Befehl nicht unterstützt',
    'cmdRecords.deviceCmdExecTable.unlocked': 'Entsperrt',
    'cmdRecords.deviceCmdExecTable.reset': 'Zurücksetzen',
    'cmdRecords.deviceCmdExecTable.ok': 'OK',
    'cmdRecords.deviceCmdExecTable.deviceName': 'Gerätename',
    'cmdRecords.deviceCmdExecTable.execTime': 'Ausführungszeit',
    'cmdRecords.deviceCmdExecTable.execResults': 'Ausführungsergebnisse',
    'cmdRecords.deviceCmdExecTable.loading': 'Ladevorgang...',
    'cmdRecords.deviceCmdExecTable.resend': 'Erneut senden',
    'cmdRecords.deviceCmdExecTable.unlock': 'Entsperren',
    'cmdRecords.deviceCmdExecTable.recall': 'Zurückrufen',
    'cmdRecords.deviceCmdExecTable.wait': 'warten',
    'cmdRecords.deviceCmdExecTable.pending': 'ausstehend',
    'cmdRecords.deviceCmdExecTable.recalled': 'zurückgerufen',
    'cmdRecords.deviceCmdExecTable.covered': 'abgedeckt',
    'cmdRecords.deviceCmdExecTable.success': 'Erfolg',
    'cmdRecords.deviceCmdExecTable.failed': 'fehlgeschlagen',
    'cmdRecords.recordDetailDrawer.bells': 'Bells',
    'cmdRecords.recordDetailDrawer.text': 'Text',
    'cmdRecords.recordDetailDrawer.media': 'Medien',
    'cmdRecords.recordDetailDrawer.file': 'Datei',
    'cmdRecords.recordDetailDrawer.soundMode': 'Soundmodus',
    'cmdRecords.recordDetailDrawer.imageMode': 'Bildermodus',
    'cmdRecords.recordDetailDrawer.androidState': 'Android-Status',
    'cmdRecords.recordDetailDrawer.wallpaper': 'Hintergrundbild',
    'cmdRecords.recordDetailDrawer.logo': 'Logo',
    'cmdRecords.recordDetailDrawer.detail': 'Detail',
    'cmdRecords.recordDetailDrawer.switchTo': 'Wechseln zu',
    'cmdRecords.recordDetailDrawer.cmdOwner': 'Befehlsinhaber:',
    'cmdRecords.recordDetailDrawer.deviceNo': 'Geräte-Nr.:',
    'cmdRecords.recordDetailDrawer.devices': 'Geräte',
    'cmdRecords.recordDetailDrawer.timeMode': 'Zeitmodus:',
    'cmdRecords.recordDetailDrawer.cmdSetTime': 'Befehl Zeit einstellen:',
    'cmdRecords.recordDetailDrawer.unlockAllTip': 'Alle Geräte unter meiner Kontrolle entsperren',
    'cmdRecords.recordDetailDrawer.unlockAll': 'Alle entsperren',
    'cmdRecords.recordDetailDrawer.seeRecurring': 'Siehe wiederkehrende',
    'cmdRecords.recordDetailDrawer.recallAllTip': 'Alle Geräte unter meiner Kontrolle zurückrufen',
    'cmdRecords.recordDetailDrawer.recallAll': 'Alle zurückrufen',
    'cmdRecords.recordDetailDrawer.isNotManageTip':
        '{val1} Geräte, die sich nicht unter meiner Kontrolle befinden, ausgeführte {val2} einbeziehen',
    'cmdRecords.recordDetailDrawer.isManageTip':
        '{val1} Geräte, die sich nicht unter meiner Kontrolle befinden',
    'cmdRecords.tableFilter.selectCmdName': 'Befehlsname auswählen',
    'cmdRecords.tableFilter.selectTimeMode': 'Zeitmodus auswählen',
    'cmdRecords.tableFilter.selectCmdStatus': 'Befehlsstatus auswählen',
    'cmdRecords.recurringTable.fold': 'Klappen',
    'cmdRecords.recurringTable.expand': 'Erweitern',
    'cmdRecords.recurringTable.edit': 'Bearbeiten',
    'cmdRecords.recurringTable.sunday': 'So.',
    'cmdRecords.recurringTable.monday': 'Mo.',
    'cmdRecords.recurringTable.tuesday': 'Di.',
    'cmdRecords.recurringTable.wednesday': 'Mi.',
    'cmdRecords.recurringTable.thursday': 'Do.',
    'cmdRecords.recurringTable.friday': 'Fr.',
    'cmdRecords.recurringTable.saturday': 'Sa.',
    'cmdRecords.recurringTable.deleteCommand': 'Befehl löschen',
    'cmdRecords.recurringTable.areYouSureDelCommand':
        'Sind Sie sicher, dass Sie diesen Befehl löschen möchten?',
    'cmdRecords.recurringTable.statusChangeSuc': 'Status geändert',
    'cmdRecords.recurringTable.statusChangeFail': 'Ändern nicht möglich.',
    'cmdRecords.tableFilter.today': 'Heute',
    'cmdRecords.tableFilter.dayRange': '{val1} {val2} Tage',
    'cmdRecords.recordDetailDrawer.updateVersion': 'Version aktualisieren',
    'cmdRecords.recordDetailDrawer.livechannel': 'Sendername',
    'cmdRecords.deviceCmdExecTable.notsupport': 'OS nicht unterstützt',
    'cmdRecords.search.owner': 'Suche Befehlseigentümer email',
    'cmdRecords.deviceCmdExecTable.uninstall': 'App nicht vorhanden',
    'cmdRecords.send.failed': 'Sendebefehl fehlgeschlagen',
};
