export default {
    'common.noData': 'Keine Daten',
    'common.unknownError': 'Unbekannter Fehler.',
    'common.agreementTitle': 'Benutzervereinbarung für das Bytello-Geräteverwaltungssystem',
    'common.policyTitle': 'Datenschutzrichtlinie des Bytello-Geräteverwaltungssystems',
    'common.quitExpPlanTitle':
        'Hinweis zum Beenden des Product User Experience Plan [Bytello Device Management System]',
    'common.userExpPlanTitle': 'Bytello Device Management System Produktbenutzererfahrungsplan',
    'common.filter.clear': 'Filter löschen',
    'common.filter.apply': 'Filter anwenden',
    'common.pleaseSelectDevice': 'Bitte Geräte auswählen!',
    'common.selectCmd': 'Wählen Sie Befehl',
    'common.allTypes': 'Alle Arten',
    'common.soundBar': 'Sound bar',
    'common.ifp': 'IFP',
    'common.paginationTotal': 'Gesamt {val1} Artikel',
    'common.paginationTotal20Page': '20 / Seite',
    'common.paginationTotal40Page': '40 / Seite',
    'common.paginationTotal80page': '80 / Seite',
    'common.executeNow': 'Jetzt ausführen',
    'common.recurring': 'Wiederkehrend',
    'common.timed': 'Zeitlich festgelegt',
    'common.powerOn': 'Ein',
    'common.powerOff': 'Ausschalten',
    'common.reboot': 'Starten Sie neu',
    'common.bells': 'Glocken',
    'common.screenLock': 'Bildschirmsperre',
    'common.blockList': 'Blockliste',
    'common.notification': 'Text',
    'common.announcement': 'Multimedia',
    'common.filePublish': 'Datei senden',
    'common.liveChannel': 'Live-Kanal',
    'common.soundMode': 'Klangmodus',
    'common.imageMode': 'Bildmodus',
    'common.powerState': 'Energiezustand',
    'common.androidState': 'Android Zustand',
    'common.wallpaper': 'Hintergrund',
    'common.logo': 'Startbild',
    'common.emergency': 'Alarm',
    'common.softwareUpdate': 'Software-Aktualisierung',

    'common.applicationInstall': 'Anwendungsinstallation',
    'common.applicationUninstall': 'Anwendung deinstallieren',
    'common.applicationAble': 'Anwendung (aktivieren / deaktivieren)',
    'common.inputSwitch': 'Eingangsschalter',
    'common.actions': 'Aktionen',
    'common.selectGroup': 'Wähle die Gruppe',
    'common.deviceControl': 'Gerätesteuerung',
    'common.message': 'Botschaft',
    'common.deviceSetting': 'Geräteeinstellungen',
    'common.allGroup': 'Alle Gruppe',
};
