export default {
    'commandModal.pleaseSelectABell': 'Bitte wählen Sie eine Glocke aus.',
    'commandModal.bellList': 'Glockenliste',
    'commandModal.bellName': 'Name der Glocke',
    'commandModal.size': 'Größe',
    'commandModal.time': 'Zeit',
    'commandModal.pleaseUploadABell': 'Bitte eine Glocke hochladen',
    'commandModal.fileSize10M': 'Die Datei darf max. 10 MB groß sein',
    'commandModal.bellFormat': 'Die Datei sollte im MP3/WAV/AAC/OGG-Format sein',
    'commandModal.selectUpto': 'Wählen Sie bis zu {val1} gleichzeitig aus.',
    'commandModal.reachedMaxLimit': 'Das Höchstlimit wurde erreicht.',
    'commandModal.fileNotSupport': 'Das aktuelle Dateiformat unterstützt keine Vorschau.',
    'commandModal.youHaveSelected': 'Sie haben diese Datei ausgewählt.',
    'commandModal.sureDelete': 'Sind Sie sich sicher, dass Sie es löschen möchten?',
    'commandModal.deleteFile': 'Datei löschen?',
    'commandModal.bellForamtHint': 'Format: MP3、WAV、AAC、OGG',
    'commandModal.bellSize': 'Größe: max. 10 MB',
    'commandModal.playWhole': 'Das Ganze abspielen',
    'commandModal.setAtLeastOneCycle': 'Bitte wählen Sie mindestens einen Zyklus aus',
    'commandModal.lockDuration': 'Sperrdauer',
    'commandModal.now': 'Jetzt',
    'commandModal.selectATimePeriod': 'Bitte einen Zeitraum auswählen',
    'commandModal.timeExpired': 'Zeit abgelaufen',
    'commandModal.endTimeCannotEarlier': 'Die Endzeit darf nicht vor der Startzeit liegen',
    'commandModal.timeCannotRepeat': 'Die Zeit kann nicht wiederholt werden',
    'commandModal.periodNotRepeat': 'Der Zeitraum kann nicht wiederholt werden',
    'commandModal.selectMutimedia': 'Bitte wählen Sie ein Multimedia aus.',
    'commandModal.upTo50Uploads': 'Bis zu 50 Uploads',
    'commandModal.annFileFormat': 'Format: MP4、AVI、JPG、PNG',
    'commandModal.annFileSize': 'Größe: max. 200 MB',
    'commandModal.annTitle': 'Multimedia',
    'commandModal.selectAMutimedia': 'Ein Multimedia auswählen',
    'commandModal.pleaseUploadAMutim': 'Bitte ein Multimedia hochladen',
    'commandModal.preiew': 'Vorschau',
    'commandModal.deviceWillPlayAuto':
        '(Das Gerät wird automatisch abspielen, wenn es ausgeführt wird)',
    'commandModal.mutimediaList': 'Multimedia-Liste',
    'commandModal.fileMultFormat': 'Die Datei sollte im MP4/AVI/JPG/PNG-Format sein',
    'commandModal.fileMultSizeLimit': 'Die Datei darf max. 200 MB groß sein',
    'commandModal.wallpaperFormat': 'Die Datei sollte im JPG-Format sein',
    'commandModal.pleaseUploadA': 'Bitte {val1} hochladen',
    'commandModal.wallTitle': 'Hintergrundbild',
    'commandModal.logoTitle': 'Logo',
    'commandModal.soundModeStandard': 'Standard',
    'commandModal.soundModeClassroom': 'Klassenraum',
    'commandModal.soundModeMetting': 'Sitzung',
    'commandModal.soundModeCustom': 'Benutzerdefiniert',
    'commandModal.imageModeStandard': 'Standard',
    'commandModal.imageModeBright': 'Heller Modus',
    'commandModal.imageModeSoft': 'Soft',
    'commandModal.imageModeCustom': 'Benutzerdefiniert',
    'commandModal.switchAnd': 'Schalter Android aktivieren',
    'commandModal.allowToSwitch': 'Erlauben Sie Geräten Android-Sender zu wechseln.',
    'commandModal.NoSignalTimeNever': 'Nie',
    'commandModal.NoSignalTime1min': '1 Minute',
    'commandModal.NoSignalTime3min': '3 Minuten',
    'commandModal.NoSignalTime5min': '5 Minuten',
    'commandModal.NoSignalTime10min': '10 Minuten',
    'commandModal.NoSignalTime30min': '30 Minuten',
    'commandModal.NoSignalTime45min': '45 Minuten',
    'commandModal.NoSignalTime60hour': '60 Minuten',
    'commandModal.NoSignalTime90hour': '90 Minuten',
    'commandModal.NoSignalTime120hour': '120 Minuten',
    'commandModal.remainPowerOff': 'Ausgeschaltet lassen',
    'commandModal.autoPowerOn': 'Automatisches Einschalten',
    'commandModal.returnPowerState': 'Zurück zu dem Zustand vor dem Stromausfall',
    'commandModal.noSignalShutdown': 'Keine Signalabschaltung',
    'commandModal.autoPowerOff': 'Automatische Abschaltung, wenn kein Signal ankommt.',
    'commandModal.displayAfter': 'Anzeige nach Stromausfall',
    'commandModal.deviceDisplayReconn': 'Wiederherstellung der Geräteanzeige nach Stromausfall.',
    'commandModal.wallpaper': 'Hintergrundbild',
    'commandModal.logo': 'Logo',
    'commandModal.useDefault': 'Standard verwenden',
    'commandModal.wallpaperCustom': 'Benutzerdefiniert',
    'commandModal.returnToDefault': '(Zurück zum Standard-{val1} des Gerätes)',
    'commandModal.pleaseSelect': 'Bitte ein {val1} auswählen.',
    'commandModal.pleaseUpload': 'Bitte ein {val1} hochladen',
    'commandModal.pleaseSelectOne': 'bitte wählen Sie eins aus',
    'commandModal.upTo20Uploads': 'Bis zu 20 Uploads',
    'commandModal.wallSizeLimit': 'Größe: max. 3 MB (1920x1080)',
    'commandModal.list': 'Liste',
    'commandModal.selectedDevices': '{num} Geräte ausgewählt',
    'commandModal.filePublish.pleaseSelect': 'Bitte wählen Sie eine Dateiliste aus',
    'commandModal.filePublish.selectUpTo': 'Wählen Sie bis zu {val1} gleichzeitig aus.',
    'commandModal.filePublish.reachTheMaximum': 'Das Höchstlimit wurde erreicht.',
    'commandModal.filePublish.fileNameTooLong': 'Der Dateiname ist zu lang',
    'commandModal.filePublish.fileSize200': 'Die Datei darf max. 200 MB groß sein',
    'commandModal.filePublish.pleaseUpload': 'Bitte eine Datei hochladen',
    'commandModal.filePublish.selectAFile': 'Wählen Sie eine Datei aus',
    'commandModal.filePublish.fileWillSave': '(Die Datei wird im Finder gespeichert)',
    'commandModal.filePublish.multiTimeZoneSelected':
        'Die Befehle werden nach der lokalen Zeitzone des Geräts ausgeführt. (wenn mehrere Zeitzonen ausgewählt sind)',
    'commandModal.filePublish.fileList': 'Dateiliste',
    'commandModal.filePublish.fileName': 'Dateiname',
    'commandModal.filePublish.format': 'Format',
    'commandModal.filePublish.fileSize': 'Größe',
    'commandModal.filePublish.selected': 'Sie haben diese Datei ausgewählt.',
    'commandModal.filePublish.deleteConfirmTip':
        'Sind Sie sich sicher, dass Sie es löschen möchten?',
    'commandModal.filePublish.deleteConfirmTip1': 'Datei löschen?',
    'commandModal.filePublish.delete': 'Löschen',
    'commandModal.filePublish.upToFilesUploads': 'Bis zu {val1} Datei-Uploads',
    'commandModal.notification.times1': '1-mal',
    'commandModal.notification.times3': '3-mal',
    'commandModal.notification.times5': '5-mal',
    'commandModal.notification.times10': '10-mal',
    'commandModal.notification.times20': '20-mal',
    'commandModal.notification.canNotEmpty': 'Das Eingabefeld darf nicht leer sein',
    'commandModal.notification.text': 'Text',
    'commandModal.notification.preview': 'Vorschau',
    'commandModal.notification.displayArea': 'Anzeigebereich',
    'commandModal.notification.loopTimes': 'Loopzeiten',
    'commandModal.announcement.displayArea': 'Anzeigebereich',
    'commandModal.turnOnTheSwitch':
        'Schalten Sie den Schalter ein, um die Zeit und Wiederholungsbefehle einzustellen.',
    'commandModal.setAsSchedule': 'Als Zeitplan einrichten',
    'commandModal.setTime': 'Zeit einstellen',
    'commandModal.offlineMode': 'Offline-Modus',
    'commandModal.offlineTooltip':
        'Der Offline-Modus ermöglicht es Geräten, Befehle ohne Internetverbindung auszuführen.',
    'commandModal.timed': 'Terminiert',
    'commandModal.timeTooltip':
        'Die Befehle werden nach der lokalen Zeitzone des Geräts ausgeführt. (wenn mehrere Zeitzonen ausgewählt sind)',
    'commandModal.recurr': 'Wiederkehrend',
    'commandModal.recurrTooltip':
        'Nur ein Satz von Wiederholungsbefehlen für ein Gerät. Ein neuer Wiederholungs-Befehl wird den Alten überschreiben.',
    'commandModal.selectATime': 'Wählen Sie eine Zeit aus.',
    'commandModal.only10times': 'Ein Zyklus kann nur 10-mal eingestellt werden',
    'commandModal.addATime': 'Eine Zeit hinzufügen',
    'commandModal.addARecurring': 'Einen Wiederholungstermin hinzufügen',
    'commandModal.multipleTimeZones':
        'Es wurden Geräte in mehreren Zeitzonen ausgewählt.\r\nAnzeige-Datum und -Zeit in UTC{val1}.',
    'commandModal.oneTimeZones':
        'Gerät(e) in UTC{val1} ausgewählt.\r\nAnzeige-Datum und -Zeit in UTC{val2}.',
    'commandModal.loading': 'L A D E N',
    'commandModal.videoNotPlayed':
        'Falls dieses Video nicht ordnungsgemäß abgespielt wird, laden Sie es bitte herunter und sehen es sich an.',

    'commandModal.playmode': 'Modus abspielen',
    'commandModal.playmode.loop': 'Schleife',
    'commandModal.playmode.duration': 'Dauer der Wiedergabe',
    'commandModal.playmode.right': 'Rechte auf Betrieb',
    'commandModal.playmode.turnoff':
        'Schalten Sie den Schalter aus, damit der Benutzer den Befehl jederzeit ausschalten kann.',
    'commandModal.playmode.times': '{value} Zeiten',
    'commandModal.playmode.throughtout': 'Überall',
    'commandModal.playmode.min': '{value} Minute',
    'commandModal.powerOnHint':
        '{num} Geräte können den Einschaltbefehl aufgrund des WOL-Serverfehlers nicht ausführen',
    'commandModal.blockList.allowList': 'Zulassungsliste',
    'commandModal.blockList.closeHint':
        'Schließen Sie die vorhandene Whitelist oder Blocklist auf dem Gerät',
    'commandModal.blockList.listManage': 'Listenverwaltung',
    'commandModal.blockList.blockHint': 'Unzulässige URLs',
    'commandModal.blockList.allowHint': 'Bestimmte URLs erlaubt',
    'commandModal.blockList.URL': 'URL',
    'commandModal.blockList.enterURL': 'Geben Sie eine URL ein',
    'commandModal.blockList.mustBeValidURL': 'Muss eine gültige URL sein',
    'commandModal.blockList.URLExist': 'URL existiert bereits',
    'commandModal.blockList.enterURLHere': 'URL hier eingeben',
    'commandModal.blockList.listType': 'Listentyp',
    'commandModal.blockList.list': 'Aufführen',
    'commandModal.blockList.pleaseSelectAURL': 'Bitte wählen Sie eine URL aus',
    'commandModal.blockList.deleteUrl': 'URL löschen?',
    'commandModal.blockList.exist.url':'URL existiert bereits'
};
