export default {
    'dashboard.title': 'Instrumententafel',
    'dashboard.activeTrend': 'Online-Trend',
    'dashboard.statisticsTheDaily': 'Statistik des täglichen Online-Status aller Geräte',
    'dashboard.inactiveDevice': 'Offline-Gerät',
    'dashboard.devices': 'Geräte',
    'dashboard.deviceOffline': 'Geräte länger als 7 Tage offline',
    'dashboard.deviceName': 'Gerätename',
    'dashboard.Tags': 'Stichworte',
    'dashboard.lastOnlineTime': 'Letzte Online-Zeit',
    'dashboard.adminAccount': 'Administratorkonto',
    'dashboard.organizationCode': 'Organisationscode',
    'dashboard.maxConnection': 'Max. Verbindung',
    'dashboard.connectedNum': 'Registrierte Geräte',
    'dashboard.onlineNum': 'Online apparaten',
    'dashboatd.date': 'Datum',
    'dashboatd.onlineNumber': 'Online-Nummer',
    'dashboard.credits': 'Credits',
    'dashboard.daysRemain': 'Verbleibende Tage',
};
