export default {
    'deviceDetail.all': 'Alle',
    'deviceDetail.unbindDevice': 'Gerät abmelden',
    'deviceDetail.allDeviceDataErased': 'Alle Gerätedaten werden gelöscht.',
    'deviceDetail.deviceWillUnbind': 'Gerät {deviceName} wird von { unitName } losgebunden.',
    'deviceDetail.unbind': 'Abmelden',
    'deviceDetail.noData': 'Keine Daten',
    'deviceDetail.group': 'Gruppe: {val1}',
    'deviceDetail.deviceId': 'Geräte-ID',
    'deviceDetail.model': 'Modell',
    'deviceDetail.osVersion': 'Version des Betriebssystems',
    'deviceDetail.operationOs': 'Betriebssystem',
    'deviceDetail.processerCPU': 'CPU',
    'deviceDetail.touchFrame': 'Touch-Frame',
    'deviceDetail.DMSVersion': '{type} Version',
    'deviceDetail.devicesInCommands': 'Gerät in geplanten Befehlen',
    'deviceDetail.commands': 'Befehl im Zeitplan',
    'deviceDetail.mode': 'Modus',
    'deviceDetail.commandOwner': 'Befehlsinhaber',
    'deviceDetail.time': 'Zeit',
    'deviceDetail.ram': 'RAM',
    'deviceDetail.storage': 'Speicher',
    'deviceDetail.deviceInGroup': 'Gerät in Gruppen',
    'deviceDetail.groupName': 'Gruppenname',
    'deviceDetail.tags': 'Tags',
    'deviceDetail.selectAtag': 'Wählen Sie ein Tag aus oder erstellen Sie ein neues Tag',
    'deviceDetail.add': 'Hinzufügen',
    'deviceDetail.deviceName': 'Gerätename',
    'deviceDetail.deviceNameIsNull': 'Bitte Gerätenamen eingeben',
    'deviceDetail.onlyLettersHint': 'Es sind nur Zahlen und Symbole - + / erlaubt.',
    'deviceDetail.tagIsNull': 'Bitte geben Sie einen Tag ein',
    'deviceDetail.lettersNumberAllowed': 'Es sind nur Buchstaben und Zahlen erlaubt.',
    'deviceDetail.tagsExists': 'Tag existiert',
    'deviceDetail.addNew': 'Neues hinzufügen',
    'deviceDetail.deviceInfomation': 'Geräteinfos',
    'deviceDetail.deviceDetails': 'Gerätedetails',
    'deviceDetail.application.enable': 'Aktivieren',
    'deviceDetail.application.enableTip':
        'Nach der Aktivierung sind die Apps auf Geräten verfügbar, auf denen sie bereits installiert sind.',
    'deviceDetail.application.disable': 'Deaktivieren',
    'deviceDetail.application.disableTip':
        'Nach dem Deaktivieren sind die Apps auf Geräten, auf denen sie bereits installiert sind, nicht verfügbar.',
    'deviceDetail.application.processing': 'In Bearbeitung...',
    'deviceDetail.application.updateTip':
        'Die Anwendung ist während der Aktualisierung nicht verfügbar.',
    'deviceDetail.application.update': 'Aktualisierung',
    'deviceDetail.application.uninstall': 'Deinstallieren',
    'deviceDetail.application.uninstallTip': 'Die Apps werden vom Gerät deinstalliert.',
    'deviceDetail.application.cmdSentWaitForExec':
        'Befehl gesendet, bleiben Sie online, damit der Befehl ausgeführt werden kann.',
    'deviceDetail.application.applicationManagement': 'Anwendungsverwaltung',
    'deviceDetail.application.refreshed': 'Neu geladen',
    'deviceDetail.application.clickToRefresh': 'Klicken, um neu zu laden',
    'deviceDetail.application.thirdPartyApps': 'Apps von Drittanbietern',
    'deviceDetail.application.nativeApps': 'Systemeigene Apps',
    'deviceDetail.execTime': 'Ausführungszeit',
    'deviceDetail.deviceType': 'Geräte-Typ',
    'deviceDetail.SerialNo': 'Serien-Nr.',
    'deviceDetail.useageDataForToday': 'Heutige Nutzungsdaten',
    'deviceDetail.deviceUseage': 'Geräte-Nutzungsdaten',
    'deviceDetail.appUseage': 'Anwendungs-Nutzungsdaten',
    'deviceDetail.timeOfUse': 'Anwendungs-Nutzungsanzahl',
    'deviceDetail.countTheTime': 'Zählen Sie, wie häufig jede einzelne Anwendung genutzt wurde',
    'deviceDetail.useTime': 'Anwendungs-Nutzungszeit',
    'deviceDetail.countTheTotal':
        'Zählen Sie die akkumulierte Gesamtzeit jeder einzelnen Anwendung',
    'deviceDetail.bootTimes': 'Online-Frequenz',
    'deviceDetail.bootTime': 'Geräte-Nutzungszeit',
    'deviceDetail.tab.basic': 'Basic',
    'deviceDetail.tab.commands': 'Befehle',
    'deviceDetail.tab.useage': 'Daten',
    'deviceDetail.tab.application': 'Apps',
    'deviceDetail.onlineTime': 'Online-Zeit',
    'deviceDetail.noAppHint': 'Nicht verwendet',
    'deviceDetail.online': 'Online',
    'deviceDetail.offline': 'Offline',
    'deviceDetail.notify': 'Echtzeit-Anzeige Benachrichtigung',
    'deviceDetail.today': 'Heute',
    'deviceDetail.yesterday': 'Gestern',
    'deviceDetail.last7': 'Letzte 7 Tage',
    'deviceDetail.last30': 'Letzte 30 Tage',
    'deviceDetail.onlineTrends': 'Online-Trends',
    'deviceDetail.tooltipTime': 'Zeit',
    'deviceDetail.activeDays': 'Aktive Tage',
    'deviceDetail.onlineRate': 'Online-Rate',
    'deviceDetail.networkInterface': 'Netzwerkschnittstelle',
    'deviceDetail.macAdress': 'MAC-Adresse',
    'deviceDetail.IPAdress': 'IP Adresse',
    'deviceDetail.disconnected': 'Getrennt',
    'deviceDetail.Fold': 'Falten',
    'deviceDetail.Expand': 'Erweitern',
    'deviceDetail.application.disable.hide.slider':
        'Deaktivieren – Seitenleistenwerkzeuge ausblenden',
    'deviceDetail.application.disable.show.slider': 'Deaktivieren – Seitenleistentools anzeigen',
};
