export default {
    'deviceList.ifpAll': 'IFP: Alle({val1})',
    'deviceList.soundbarAll': 'Sound bar: Alle({val1})',
    'deviceList.allTypeAll': 'Alle Typen: Alle({val1})',
    'deviceList.deviceErased': 'Alle Gerätedaten werden gelöscht.',
    'deviceList.unbindTip': 'Gerät „{val1}“ wird von {val2} losgebunden.',
    'deviceList.groupNameCannotEmpty': 'Die Gruppenbezeichnung darf nicht leer sein',
    'deviceList.allDevices': 'Alle Geräte',
    'deviceList.groupNameExists': 'Die Gerätegruppe „Alle Geräte“ existiert bereits!',
    'deviceList.groupNameAlreadyExists': 'Die Gerätegruppe „{val1}“ existiert bereits!',
    'deviceList.deviceGroupCreated': 'Gerätegruppe erstellt',
    'deviceList.filter.searchDeviceName': 'Gerätenamen suchen',
    'deviceList.filter.selectStatus': 'Status auswählen',
    'deviceList.filter.selectTimezone': 'Zeitzone auswählen',
    'deviceList.filter.selectTags': 'Tags auswählen',
    'deviceList.table.deviceName': 'Gerätename',
    'deviceList.table.status': 'Status',
    'deviceList.table.tags': 'Tags',
    'deviceList.table.school': 'Organisation',
    'deviceList.table.timezone': 'Zeitzone',
    'deviceList.table.nextCmd': 'Nächster Befehl',
    'deviceList.table.coAdmin': 'Co-Administrator',
    'deviceList.table.details': 'Details',
    'deviceList.table.searchName': 'Suche {val1}',
    'deviceList.table.reset': 'Zurücksetzen',
    'deviceList.table.search': 'Suche',
    'deviceList.table.device': 'Gerät',
    'deviceList.group': 'Gruppe',
    'deviceList.hasTypeAll': '{val1}',
    'deviceList.tabel.all': 'Alle auswählen',
    'deviceList.tabel.list': 'Liste',
    'deviceList.tabel.grid': 'Raster',
    'deviceList.select.group': 'Gruppe',
    "device.table.school": "Schule",
};
