export default {
    'menu.home': 'Home',
    'menu.dashboard.dashboard': 'Instrumententafel',
    'menu.deviceManagement': 'Geräte',
    'menu.deviceManagement.allTypes': 'Alle Arten',
    'menu.deviceManagement.ifp': 'IFP',
    'menu.deviceManagement.soundBar': 'Sound bar',
    'menu.deviceManagement.ledWall': 'Led wall',
    'menu.functions': 'Fortgeschrittene',
    'menu.functions.profile': 'Profil',
    'menu.functions.appManage': 'Anwendungen',
    'menu.functions.inputSwitch': 'Eingabe-Schalter',
    'menu.functions.firmwareUpdate': 'Firmware update',
    'menu.functions.softwareUpdate': 'Software-Aktualisierung',
    'menu.commandRecords': 'Aufzeichnungen',
    'menu.commandRecords.exeHistory': 'Geschichte',
    'menu.commandRecords.inSchedule': 'Im Zeitplan',
    'menu.user.userManagement': 'Benutzerverwaltung',
    'menu.account.accountSettings': 'Kontoeinstellungen',
    'menu.systemManage': 'System',
    'menu.systemManage.adminManage': 'Benutzer',
    'menu.systemManage.schoolManage': 'Organisation',
    'menu.systemManage.passwordManage': 'Passwort',
    'menu.systemManage.userSettings': 'die Einstellungen',
    'menu.resources.resources': 'Ressourcen',
    'global.error.network': 'Netzwerkfehler',
    'global.network.timeout': 'Zeitlimit',
    'global.network.error': 'Internet-Fehler',
    'global.btn.ok': 'OK',
    'upload.getUploadPolicyError': 'Upload fehlgeschlagen',
    'upload.networkError': 'Upload fehlgeschlagen',
    'upload.cancelled': 'Task-Upload abbrechen!',
    'upload.formatError': 'Dateiformat-Fehler',
    'upload.fileNameError': 'Der Dateiname ist zu lang',
    'upload.parsing': 'Analyse läuft...',
    'upload.fileExist': 'Die Datei existiert bereits',
    'upload.fileNameTooLong': 'Der Dateiname ist zu lang',
    'upload.fileJPG': 'Die Datei sollte im JPG-Format sein',
    'upload.file3M1920': 'Die Datei darf max. 3 MB (1920x1080) groß sein',
    'upload.formatJPG': 'Format: JPG',
    'upload.size3M': 'Größe: max. 3 MB (1920x1080)',
    'global.cancel': 'Abbrechen',
    'global.save': 'Speichern',
    'global.confirm': 'Bestätigen',
    'global.send': 'Senden',
    'global.delete': 'Löschen',
    'global.close': 'Schließen',
    'global.commandSent': 'Befehl gesendet',
    'global.unableSend': 'Senden nicht möglich',
    'global.commandSave': 'Befehl gespeichert',
    'global.unableSave': 'Speichern nicht möglich',
    'global.commandDelete': 'Befehl gelöscht',
    'global.unableDelete': 'Löschen nicht möglich',
    'global.empty': 'Leer',
    'header.infoCenter': 'Infozentrum',
    'header.allSchool': 'Alle Organisationen',
    'header.sendAll': 'Alle senden',
    'header.todayCommand': 'Der heutige Befehl',
    'header.admin': 'Admin',
    'header.feedback': 'Feedback schicken',
    'header.trial': 'Testphase',
    'header.inactive': 'Inaktiv',
    'header.emergency': 'Alarm',
    'header.expired':'Abgelaufen',
    'global.lockTip':
        'Danach wird das Konto gesperrt und ein Aktivierungscode wird an Ihre E-Mail-Adresse gesendet.',
    'global.loading': 'Laden',
    'global.accept': 'Annehmen',
    'global.reject': 'Ablehnen',
    'global.protocplTip1': 'Durch die Anmeldung akzeptiere ich die ',
    'global.protocplTip2': 'und bestätige die Annahme der ',
    'global.userAgreeement': 'Nutzervereinbarung',
    'global.policy': 'Datenschutzrichtlinie',
    'global.pleaseCheck': 'Bitte lesen Sie die Nutzervereinbarung und die Datenschutzrichtlinie.',
    'global.switchDefaultTip':
        'Schalten Sie den Schalter ein, um die Uhrzeit und Wiederholungsbefehle einzustellen.',
    'global.noResults': 'Keine Ergebnisse',
    'global.off': 'Offline',
    'global.on': 'Online',
    'global.language': 'Sprache',
    'global.enroll': 'Anmelden',
    'global.last': 'Letzte',
    'global.next': 'Nächste',
    'global.continue': 'Fortfahren',
    'global.saveChanges': 'Änderungen speichern',
    'global.mode': 'Modus',
    'global.tags': 'Stichworte',
    'global.detail': 'Einzelheiten',
    'global.update.time': 'Updatezeit',
    'global.not.configured': 'Nicht konfiguriert',
    'global.save.and.sync': 'Speichern und synchronisieren',
    'global.license': 'Lizenz',
    'global.day.remaing': 'Verbleibender Tag',
    'global.linces.records': 'Aufzeichnungen',
    'global.license.helper.title':
        'Die verbleibenden Tage sind die Zeitdauer, die dieses Konto hat, um auf das Produkt zuzugreifen.',
    'global.license.helper.tip1':
        'Länge des Zugriffs = Das Minimum zwischen [Verfallsdauer] und [Gutschriften/eingeschriebene Geräte]',
    'global.license.helper.tip2':
        '[Ablauf der Frist] ist die Anzahl der Tage, die bis zum Verfallsdatum verwendet werden können.',
    'global.license.helper.tip3':
        '[Gutschriften/erfasste Geräte] ist die Anzahl der Tage, an denen die restliche Kreditunterstützung von der eingeschriebenen Einrichtung verwendet wurde.',
    'global.uploading':'Hochladen',
    'global.leave': 'Verlassen',
    "global.change":"Veränderung",
    "global.sending":"Senden",
    "global.get.code":"Code abrufen",
    "global.resend.code":"Code erneut senden",
    "global.change.email":"Ändern Sie die E-Mail",
    "global.unknow.error":"Unbekannter Fehler"
};
