export default {
    'group.deviceName': 'Gerätename',
    'group.timezone': 'Zeitzone',
    'group.groupManagement': 'Gruppen-Verwaltung',
    'group.delGroupTip': 'Diese Gruppe löschen?',
    'group.del': 'Löschen',
    'group.quit': 'Beenden',
    'group.popBtnText': 'Eine Gruppe schließen {val1}?',
    'group.create': 'Anlegen',
    'group.save': 'Speichern',
    'group.enterGroupName': 'Die Gruppenbezeichnung hier eingeben',
    'group.creating': 'erstellen',
    'group.modify': 'abändern',
    'group.addNew': 'Neue Gruppe hinzufügen',
    'group.all': 'Alle',
    'group.allDevices': 'Alle Geräte {val1}/{val2}',
    'group.selectedDevices': 'Ausgewählte Geräte {val1}',
    'group.conditionLimit': 'Bedingungsgrenze erreicht',
    'group.addCondition': 'Bedingung hinzufügen',
    'group.autoAllocation': 'Automatische Zuweisung',
    'group.manualSelection': 'Manuelle Auswahl',
    'group.enterConditionHere': 'Geben Sie hier eine Bedingung ein',
    'group.enterCondition': 'Bedingung eingeben',
    'group.select': 'Auswählen',
};
