export default {
    'channel.message.error': 'Bitte einen Sender auswählen',
    'channel.select.placehoder': 'Sender auswählen',
    'channel.live.name': 'Sendername',
    'channel.live.title': 'Live-Senderliste',
    'channel.modal.title': 'Sender löschen?',
    'channel.modal.content': 'Möchten Sie diesen Sender löschen?',
    'channel.modal.oktext': 'Löschen',
    'channel.form.nameerror': 'Der Name darf nicht leer sein.',
    'channel.form.addresserror': 'Die Adresse darf nicht leer sein.',
    'channel.form.formaterror': 'Das Adressformat ist falsch.',
    'channel.btn.create': 'Anlegen',
    'channel.btn.span': 'Unterstütztes Live-Stream-Protokoll: RTMP,RTSP und HTTP Live-Streaming',
    'channel.form.title': 'Live-Sender erstellen',
    'channel.form.labelname': 'Sendername',
    'channel.form.labeladdress': 'Adresse',
    'channel.live.label': 'Live-Sender',
    'channel.btn.channellist': 'Live-Senderliste',
    'channel.form.addressholder': 'Sender-URL',
    'channel.name.exist': 'Der Sender existiert bereits!',
    'channel.preview.notsupport': 'Für diesen Live-Sender wird keine Vorschau unterstützt',
    'channel.btn.newcreate': 'Live-Sender anlegen',

    'channel.edit.livechannel': 'Kanal bearbeiten',
    'channel.edit.save': 'Speichern',
};
