export default {
    'login.error.emailEmpty': 'Bitte geben Sie Ihre E-Mail-Adresse ein.',
    'login.error.emailInvalid': 'Diese E-Mail-Adresse ist leider ungültig.',
    'login.error.emailLetterInvalid':
        'Es sind leider nur Buchstaben (a-z), Zahlen(0-9) und Symbole (@._) erlaubt.',
    'login.error.emailNotFound': 'Zu dieser E-Mail-Adresse wurde kein Konto gefunden.',
    'login.error.createWidthAccount': 'Mit diesem Konto anlegen?',
    'login.error.pwdEmpty': 'Bitte geben Sie ein Passwort ein.',
    'login.error.pwdInvalid': 'Dieses Passwort ist leider falsch.',
    'login.error.pwdEqualMail':
        'Passwörter dürfen leider nicht mit der E-Mail-Adresse identisch sein',
    'login.error.pwdLength': 'Passwörter müssen 8-16 Zeichen enthalten.',
    'login.error.pwdFormat':
        'Ein Passwort muss zwei der folgenden Kategorien enthalten: Zahlen/Buchstaben/Sonderzeichen',
    'login.error.specialSymbol':
        'Es sind leider nur Buchstaben (a-z), Zahlen (0-9) und Sonderzeichen (~!@#$%^&*()+-=,./;|<>?) erlaubt',
    'login.error.pwdNotEqual': 'Diese Passwörter stimmen nicht überein',
    'login.error.notLogin': 'Sie sind nicht angemeldet, bitte melden Sie sich an.',
    'login.error.verify': 'Bitte überprüfen',
    'login.label.forgotPwd': 'Passwort vergessen?',
    'login.label.email': 'E-Mail',
    'login.label.notAccount': 'Kein Konto?',
    'login.label.createAccount': 'Ein Konto anlegen',
    'login.label.pwd': 'Passwort',
    'login.title.account': 'Konto',
    'login.title.login': 'Anmelden',
    'login.title.tips': 'Tipps',
    'login.btn.login': 'Anmelden',
    'login.btn.confirm': 'Bestätigen',
    'login.btn.ok': 'OK',
    'login.placeHolder.email': 'Geben Sie Ihre E-Mail-Adresse ein',
    'login.placeHolder.pwd': 'Geben Sie Ihr Passwort ein',
    'login.logout': 'Abmelden',
    'login.error.noAuth': 'Das Konto ist nicht autorisiert.',
    'login.forgetPwd': 'Passwort vergessen',
    'login.forgetTip':
        'Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link mit einem Verifizierungscode, um Ihr Passwort zurückzusetzen.',
    'login.verifyAgain': 'Es ist ein Fehler aufgetreten. Bitte erneut überprüfen.',
    'login.next': 'Nächste',
    'login.backToLogin': 'Zurück zur Anmeldung',
    'login.loginFailed': 'Anmeldung fehlgeschlagen',
    'login.accountExpired': 'Das Konto ist abgelaufen, bitte kontaktieren Sie das Hauptkonto',
    'login.accountNoAuth': 'Das Konto ist nicht autorisiert',
    'login.lockChances': '{val1} verbleibende Versuche',
    'login.resetSuc': 'Erfolgreich zurückgesetzt! Anmeldung...',
    'login.reset.characters816': '8-16 Zeichen',
    'login.reset.charactersCategories':
        'Zwei der folgenden Kategorien: Zahlen/Buchstaben/Sonderzeichen',
    'login.reset.canNotMatch': 'Darf nicht mit Ihrer E-Mail-Adresse identisch sein',
    'login.reset.curPwd': 'Aktuelles Passwort',
    'login.reset.newPwd': 'Neues Passwort',
    'login.reset.confirmPwd': 'Passwort bestätigen',
    'login.modifyPwd': 'Passwort ändern',
    'login.title.2FA': '2-Faktor-Authentifizierung',
    'login.2FA.input.tip':'Geben Sie den Bestätigungscode aus den Drittanbieter-Apps ein',
    "logout.text.tip":"Sie werden sich abmelden"
};
