export default {
    'profile.createNew': 'Neu',
    'profile.time': 'Erstellt in {createTime}, zuletzt geändert in {modifyTime}',
    'profile.set': 'Als standard festlegen',
    'profile.apply': 'Anwendung',
    'profile.type': 'Typ',
    'profile.applied': 'Angewandt',
    'profile.remove': 'löschen',
    'profile.modal.apply': 'Anwendung',
    'profile.modal.profilename': 'Konfigurationsname',
    'profile.detail.delete': 'löschen',
    'profile.detail.seeprofile': 'Prüfen',
    'profile.create.new': '{os}-Konfiguration erstellen',
    'profile.create.edit': '{os}-Konfiguration bearbeiten',
    'profile.create.security': 'Sicherheit',
    'profile.create.app': 'Apps-Verwaltung',
    'profile.create.securitydes':
        'Blockierung: Sperrlisten-Websites, um zu verhindern, dass Benutzer auf die Website zugreifen. Fügen Sie die Website der Zulassungsliste hinzu, um zu verhindern, dass Benutzer auf andere Websites als die Zulassungsliste zugreifen',
    'profile.create.appdes': 'Unterstützt die stille Installation von Anwendungen',
    'profile.create.appsettingdes': 'Stellen Sie Leistung, Anzeige und andere Gerätestatus ein',
    'profile.create.config': 'Aufbau',
    'profile.create.checkprofilename': 'Konfigurationsname darf nicht leer sein',
    'profile.create.checkurl': 'URL darf nicht leer sein',
    'profile.create.whiteblack': 'Blockierung',
    'profile.create.addurl': 'URL hinzufügen',
    'profile.create.urls': 'URL',
    'profile.create.appremove': 'Apps beim Entfernen des Profils vom Gerät entfernen',
    'profile.create.appsmanagement': 'Apps-Verwaltung',
    'profile.create.installapps': 'Installieren',
    'profile.create.addapps': 'App hinzufügen',
    'profile.create.appname': 'Anwendungsname',
    'profile.create.sleep': 'Automatische Schlafzeit',
    'profile.create.sleepdes':
        'Wechseln Sie automatisch in den Schlafmodus, wenn innerhalb einer bestimmten Zeit keine Bedienung erfolgt',
    'profile.create.poweroff': 'Automatische Abschaltung',
    'profile.create.poweroffdes':
        'Automatisches Herunterfahren, wenn das Gerät längere Zeit nicht bedient wird',
    'profile.create.signal': 'Keine Signalabschaltung',
    'profile.create.signaldes': 'Automatische Abschaltung bei fehlendem Signaleingang',
    'profile.create.powersetting': 'Stromausfalleinstellungen',
    'profile.create.powersettingdes': 'Das Gerät zeigt nach Stromausfall wieder verbunden an',
    'profile.create.wakeon': 'Aktivieren Sie das Aufwachen',
    'profile.create.andriodchannel': 'Android-Kanal',
    'profile.create.andriodchanneldes': 'Gerät zum Android-Kanal wechseln lassen',
    'profile.create.soundmode': 'Klangmodus',
    'profile.create.imagemode': 'Bildmodus',
    'profile.create.imagemodedes': 'Der Bildmodus unterstützt nur Nicht-Android-Kanäle',
    'profile.create.autoturnoff': 'Bildschirm automatisch ausschalten',
    'profile.create.autoturnoffdes':
        'Schalten Sie den Bildschirm automatisch ohne Bedienung innerhalb der angegebenen Zeit aus',
    'profile.create.sleepmode': 'Versetzen Sie das Gerät automatisch in den Schlafmodus',
    'profile.create.sleepmodedes':
        'Versetzen Sie das Gerät automatisch in den Schlafmodus, wenn innerhalb des angegebenen Zeitraums keine Bedienung erfolgt',
    'profile.create.poweroffopt': 'Verlassen',
    'profile.create.poweronopt': 'Anmachen',
    'profile.create.powerlastopt': 'Zuletzt',
    'profile.create.none': 'Niemals',
    'profile.create.warning':
        'Nur Clients der Version 1.9.0 oder höher unterstützen die Verwendung von Konfigurationsdateien',
    'profile.create.default': 'Ursprünglich',
    'profile.create.savesuccess': 'Erfolgreich gespeichert',
    'profile.create.savefailed': 'Speichern fehlgeschlagen',
    'profile.modal.deletetitle': 'Profil löschen',
    'profile.modal.deletecontent': 'Möchten Sie das Profil wirklich löschen?',
    'profile.create.enterurl': 'URL eingeben',

    'profile.create.deletewhiteblack': 'Sperrliste/Zulassungsliste löschen',
    'profile.create.uninstallapps': 'Apps deinstallieren',
    'profile.create.wakeonopt': 'Wake on LAN',
    'profile.create.autochannelopt': 'Android Kanal',
    'profile.create.sleepmodeopt': 'Schlafmodus',
    'profile.route.title': 'Profil nicht gespeichert',
    'profile.route.content':
        'Das Profil wurde nicht gespeichert. Möchten Sie diese Seite wirklich verlassen?',
    'profile.app.size': 'Größe: max. 300 MB',
    'profile.app.upfiles': 'Bis zu 50 Dateien können',
    'profile.create.hidesidebar': 'Seitenleiste ausblenden',
    'profile.data.and.time.format.automatically': 'Automatisch',
    'profile.data.and.time.format.matically': 'Manuell',
    'profile.12.hour.time': '12-Stunden-Zeit',
    'profile.24.hour.time': '24-Stunden-Zeit',
    'profile.save.failed': 'Fehler beim Speichern',
    'profile.save.failed.tip':
        'Bitte füllen Sie alle erforderlichen Felder aus oder schließen Sie die Konfigurationen, um das Profil zu speichern',
    'profile.device.general.settings': 'Allgemeine Einstellungen',
    'profile.update.software': 'Software aktualisieren',
    'profile.associated.devices': 'Zugehörige Geräte',
    'profile.not-compliant.num': 'Nicht konform',
    'profile.bytello.devices':
        'Einstellungen, die von Geräten unterstützt werden, die nur mit Bytelo funktionieren',
    'profile.date.and.time.label': 'Datum & Zeit',
    'profile.date.and.time.helper': 'Vom Netzwerk bereitgestellte Zeit nutzen',
    'profile.devices.time.zone': 'Zeitzone',
    'profile.devices.time.format': 'Zeitformat',
    'profile.devices.non.compliant': 'Nicht konform',
    'profile.devices.compliant': 'Konforme',
    'profile.action.sync': 'Synchronisieren',
    'profile.devices.compoliant.status': 'Geräte - Konformitätsstatus',
    'profile.details': 'Einzelheiten',
    'profile.applied.devices': 'Angewandte Geräte',
    'profile.create.brief1':
        'Eine Richtlinie ist eine Reihe von Konfigurationen und Einschränkungen, die entwickelt wurden, um bei DMS registrierte Geräte zu verwalten und zu schützen.',
    'profile.create.brief2':
        'Nach dem Festlegen eines Profils als Standardprofil empfängt und führt ein Gerät bei der Registrierung bei Ihrer Organisation automatisch das Standardprofil aus.',
    'profile.default.time.zone': 'Nicht ändern',
    'profile.set.default': 'Standard setzen',
    'profile.associated.status': 'Wählen Sie den Status „Geräte-kompatibel“ aus',
    'profile.associate': 'Assoziieren',
    'profile.devices': 'Geräte',
    'profile.add.devices': 'Geräte hinzufügen',
    'profile.associate.devices': 'Geräte zuordnen',
    'profile.edit.savesuccess': 'Speichern und synchronisieren Sie erfolgreich',
};
