export default {
    'register.activateSchool': 'Die Organisation aktivieren',
    'register.hasoOpenPer': ' hat die {type}-Berechtigung für Sie geöffnet.',
    'register.licenseInfo': 'Lizenzinformationen',
    'register.licenseType': 'Lizenztyp',
    'register.maxPanel': 'Max. Felder',
    'register.avaTime': 'Verfügbare Zeit',
    'register.schoolInfo': 'Organisationsdaten',
    'register.schoolCode': 'Organisationscode',
    'register.adminAccount': 'Administrator-Konto',
    'register.schoolName': 'Organisationsname',
    'register.location': 'Ort',
    'register.hint': 'Sollten Sie Fragen haben, wenden Sie sich an ',
    'register.maxPanelHint': 'Falls Sie die Anzahl erhöhen möchten, wenden Sie sich an ',
    'register.selectLocation': 'Wählen Sie Ihr Land oder Ihre Region',
    'register.typeSchoolName': 'Organisationsnamen eingeben',
    'register.schoolNameCannotRepeat':
        'Der Organisationsname darf in einer Region nicht wiederholt verwendet werden.',
    'register.selectLocationHint': 'Bitte wählen Sie einen Organisations-Standort aus.',
    'register.inputNoEmpty': 'das Eingabefeld darf nicht leer sein.',
    'register.4Digit': 'Mindestens 4 Zeichen',
    'register.quantity': 'Menge',
    'register.credits': 'Kredite',
};
