export default {
    'userDetail.pwdPermission': 'Passwort-Berechtigung',
    'userDetail.authCommands': 'Autorisierte Befehle',
    'userDetail.manage': 'Verwalten',
    'userDetail.authCommandsSave': 'Autorisierte Befehle gespeichert.',
    'userDetail.unableSave': 'Speichern nicht möglich.',
    'userDetail.authDevicesSave': 'Autorisierte Befehle gespeichert.',
    'userDetail.commandAuthFor': 'Befehlsautorisierung für ',
    'userDetail.device': 'Gerät',
    'userDetail.label': 'Label',
    'userDetail.deviceAuthFor': 'Geräteautorisierung für',
    'userDetail.authDevices': 'Autorisierte Geräte',
    'userDetail.deviceNo': 'Geräte-Nr.',
    'userDetail.authGroup': 'Autorisierte Gruppen',

    'userDetail.roleCannotDel': 'Die Rolle kann nicht gelöscht werden.',
    'userDetail.userIsUsing': 'Der Benutzer, der diese Rolle verwendet:',
    'userDetail.deleteRole': 'Rolle löschen?',
    'userDetail.roleName': 'Rollenname',
    'userDetail.customRole': 'Benutzerdefinierte Rolle',
    'userDetail.roleList': 'Rollenliste',
    'userDetail.allDevicesAndGroup': 'Alle Geräte und Gruppen',
    'userDetail.createDeviceGroup': 'Gerätegruppe erstellen',
    'userDetail.deleteGroup': 'Diese Gruppe löschen aus {username}?',
    'userDetail.switchRoleHint': 'Möchten Sie die Rolle {role} wirklich wechseln ?',
    'userDetail.userInfomation': 'Nutzerinformation',
    'userDetail.switchRole': 'Rolle wechseln',
    'userDetail.createSucc': 'Erfolgreich erstellen',
    'userDetail.operatorHint':
        'Betreiber: Dieser Benutzer hat die volle Autorität, in allen Aspekten der Plattform zu handeln.',
    'userDetail.viewerHint': `Viewer: Dieser Benutzer kann nur Geräte-, Benutzer-, Registrierungs- und Anwendungsinformationen anzeigen. Änderungen an Intune sind nicht möglich.`,
    'userDetail.customHint':
        'Benutzerdefinierte Rolle: Erstellen von Rollen mit benutzerdefinierten Berechtigungen.',
    'userDetail.roleNameExists': 'Rollenname {name} existiert bereits',
    'userDetail.createAGroup': 'Erstellen Sie eine Gruppe',
};
