export default {
    'user.title': 'Administrations-Manager',
    'user.username': 'Benutzername',
    'user.account': 'Konto',
    'user.role': 'Rolle',
    'user.latestOperation': 'Letzte Aktion',
    'user.deviceNum': 'Geräte-Nr.',
    'user.commandNum': 'Befehls-Nr.',
    'user.remotePwd': '{type}-Passwort',
    'user.screenLockPwd': 'Passwort für die Bildschirmsperre',
    'user.details': 'Details',
    'user.remotePwdStatus.disabled': 'Deaktiviert',
    'user.remotePwdStatus.visible': 'Sichtbar',
    'user.remotePwdStatus.invisible': 'Unsichtbar',
    'user.createSubAccount': 'Nutzer hinzufügen',
    'user.noAccountHint': 'Bitte legen Sie zuerst ein Unterkonto an',
    'user.deleteSucHint': 'Unterkonto {account} von {unitName} gelöscht.',
    'user.delete': 'Löschen',
    'user.deleteSubAccount': 'Unterkonto löschen',
    'user.deleteConfirm': 'Möchten Sie das {account} von {unitName} löschen? ',
    'user.anEmailWillSent': 'Es wird eine E-Mail an {account} gesendet.',
    'user.addAccountSucHint': '{email} zu {unitName} hinzugefügt.',
    'user.addAccountErrHint': 'Anlegen eines Unterkontos fehlgeschlagen.',
    'user.information': 'Informationen',
    'user.device': 'Gerät',
    'user.permission': 'Berechtigung',
    'user.prev': 'Vorh',
    'user.create': 'Anlegen',
    'user.next': 'Nächste',
    'user.createAPwd': 'Erstellen Sie ein Passwort, das:',
    'user.816Characters': '8-16 Zeichen',
    'user.twoCategories': 'Zwei der folgenden Kategorien: Zahlen/Buchstaben/Sonderzeichen',
    'user.cannotMatchEmail': 'Darf nicht mit Ihrer E-Mail-Adresse identisch sein',
    'user.accountAlreayHas': 'Dieses Konto ist bereits ein Benutzer der Organisation.',
    'user.emailCheckEmpty': 'Bitte geben Sie Ihre E-Mail-Adresse ein.',
    'user.emailCheckHasSpecialSymbol':
        'Es sind leider nur Buchstaben (a-z), Zahlen(0-9) und Symbole (@._) erlaubt.',
    'user.emailCheckFormat': 'Diese E-Mail-Adresse ist leider ungültig.',
    'user.pwdCheckEmpty': 'Bitte geben Sie ein Passwort ein.',
    'user.pwdCheckMatch':
        'Entschuldigung, das Passwort kann nicht mit Ihrer E-Mail-Adresse übereinstimmen.',
    'user.pwdCheckLength': 'Passwörter müssen mindestens 8 Zeichen enthalten.',
    'user.pwdCheckHasSpecialSymbol':
        'Es sind leider nur Buchstaben (a-z), Zahlen (0-9) und Sonderzeichen (~!@#$%^&*()+-=,./;|<>?) erlaubt',
    'user.pwdCheckFormat':
        'Passwörter müssen mindestens zwei der folgenden Elemente enthalten: Zahlen/Buchstaben/Sonderzeichen.',
    'user.usernameCheckEmpty': 'Bitte geben sie einen Benutzernamen ein',
    'user.usernameCheckFormat': 'Es sind leider nur Buchstaben (a-z) und Zahlen(0-9) erlaubt',
    'user.password': 'Passwort',
    'user.accountMatched': 'Das Konto stimmt überein',
    'user.enterAnEmail': 'Geben Sie eine E-Mail-Adresse ein',
    'user.modify': 'Abändern',
    'user.verify': 'Überprüfen',
    'user.deviceName': 'Gerätename',
    'user.coAdministrator': 'Co-Administrator',
    'user.selected': 'Ausgewählt',
    'user.allDevices': 'Alle Geräte',
    'user.permissionAuth': 'Erlaubnis autorisiert für',
    'user.pwdPermission': 'Passwort-Berechtigung',
    'user.allCommands': 'Alle Geräte',
    'user.emerHint': 'Senden Sie eine Warnmeldung an das Gerät.',
    'user.notificationHint': 'Eine Scroll-Nachricht an das Gerät senden.',
    'user.announcementHint': 'Video/Bild-Nachrichten an das Gerät senden.',
    'user.filePublishHint': 'Dateien an das Gerät senden.',
    'user.powerStateHint':
        'Stellen Sie die Statusanzeige ein, nachdem das Gerät eingeschaltet ist.',
    'user.androidStateHint': 'Stellen Sie die Sichtbarkeit des Android-Senders ein.',
    'user.wallpaperHint': 'Das Hintergrundbild auf dem Gerät per Fernsteuerung ändern.',
    'user.logoHint': 'Das Bootlogo per Fernsteuerung ändern.',
    'user.input': 'Eingabe',
    'user.hours': 'Laufen in { time } Stunden aus',
    'user.days': 'Laufen in { time } Tagen aus',
    'user.yearsDays': 'Laufen in { year } Jahren { days } Tagen aus',
    'user.years': 'Laufen in { year } Jahren aus',
    'user.hoursLeft': '{ time } Stunden verbleiben',
    'user.daysLeft': '{ time } Tage verbleiben',
    'user.yearsDaysLeft': '{ year } Jahre { days } Tage verbleiben',
    'user.yearsLeft': '{ year } Jahre verbleiben',
    'user.addUser': 'Nutzer hinzufügen',
    'user.allDevicesAndGroups': 'Alle Gruppen und Geräte',
    'user.enterRoleName': 'Geben Sie hier den Rollennamen ein',
    'user.standard':'Standard',
    'user.email.change.title1':'Konto-E-Mail ändern',
    'user.email.change.tip1':'Wir senden Ihnen einen Bestätigungscode-Link, um die E-Mail-Adresse des Kontos zu ändern.',
    'user.email.change.title2':"Bestätigen Sie, um fortzufahren",
    "user.email.change.tip2":"Brauchen Sie Hilfe? Bitte kontaktieren Sie {val1}",
    "user.email.change.title3":"Konto-E-Mail ändern",
    "user.email.change.tip3":"Der Administrator der Organisation wird sich abmelden. Das Login-Passwort bleibt nach der Änderung unverändert.",
    "user.email.change.new.input.tip":"Nowy e-mail",
    "user.email.change.input.placeholder":"Geben Sie hier eine neue E-Mail ein",
    "user.email.change.success.tip":"Konto-E-Mail erfolgreich geändert.",
    "user.email.change.fail.txt":"Entschuldigung, diese E-Mail-Adresse wurde bereits registriert."
};
