export default {
    'account.accountInfo': '帳戶管理',
    'account.account': '帳戶',
    'account.username': '用戶名',
    'account.resetPswd': '重設密碼',
    'account.resetPswdTip1': '重置密碼後，該帳戶將自動登出。',
    'account.resetPswdTip2': '警告：如果您使用其他用戶中心產品，密碼將同步更新。',
    'account.pswdManagement': '密碼管理',
    'account.password': '密碼',
    'account.remoteLock': '{type} 鎖定密碼',
    'account.password.remoteLock.desc':'輸入密碼以取消註冊設備。',
    'account.remoteLockDesc': '在設置中鎖定{type}。輸入密碼以解鎖。',
    'account.deviceSettingLock': '設備設置鎖定',
    'account.deviceSettingLockDesc': '裝置已鎖定。輸入密碼以解鎖。',
    'account.screenLock': '屏幕鎖密碼',
    'account.screenLockDesc': '將裝置鎖定一段時間。輸入密碼以解鎖。',
    'account.school': '組織',
    'account.schoolName': '組織名',
    'account.state': '州',
    'account.admin': '管理員',
    'account.email': '電子郵件',
    'account.schoolCode': '組織代碼',
    'account.serverManagement': 'WOL 服務器',
    'account.serverName': '伺服器名稱',
    'account.powerState': '服務器狀態',
    'account.connectNum': '連接號',
    'account.delete': '刪除',
    'account.deleteServer': '刪除伺服器',
    'account.delServerTip': '您是否要從{unitName}刪除{serverName}？',
    'account.delServerSuc': '伺服器{serverName}已從{unitName}中刪除。',
    'account.serverOff': '不可用',
    'account.serverOn': '可用的',
    'account.about': '關於',
    'account.legalInfo': '法律訊息',
    'account.userExpPlan': '用戶體驗計劃',
    'account.userExpPlan1': '用戶體驗計劃>',
    'account.OK': '好',
    'account.accept': '同意',
    'account.quit': '離開',
    'account.userArgeement': '用戶協議>',
    'account.privacyPolicy': '隱私政策>',
    'account.openLicense': '開源許可證 >',
    'account.pleaseEnterPswd': '請輸入您的密碼。',
    'account.pswdLen6': '密碼必須包含6個字符。',
    'account.pswdOnlyNumber': '抱歉，只允許輸入數字（0-9）。',
    'account.userNameValidateInfo': '抱歉，只允許使用字母（a-z），數字（0-9）和字符（@，_）。',
    'account.logout': '登出',
    'account.userName': '用戶名',
    'account.edit': '編輯',
    'account.pswd': '密碼',
    'account.reset': '重置',
    'account.location': '位置',
    'account.adminUserName': '管理員',
    'account.adminAccount': '管理員帳號',
    'account.schoolInfoMod': '組織信息修改',
    'account.deleteConfirm': '您要從{unitName}刪除{account}嗎？',
    'account.anEmailWillSent': '電子郵件將發送到{account}。',
    'account.serverManagement.hint':
        '局域網喚醒（WoL）是一種以太網或令牌環計算機網絡標準，該標准允許計算機通過網絡消息打開或喚醒。',
    'account.notConnectHint': '{num} 設備未連接到任何服務器',
    'account.connectedDeivces': '連接的設備',
    'account.two.factor.authentication': '兩因素身份驗證',
    'account.2FATip': '如果啟用了雙因素身份驗證，您將需要提供驗證碼才能登錄 Bytelo DMS',
    'account.error.twoFA.isEmpty': '請輸入6位驗證碼',
    'account.Authenticate.password.title': '繼續驗證',
    'account.disable.2FA.title': '禁用兩因素身份驗證',
    'account.Authenticate.password.label': '輸入您的帳戶密碼',
    'account.Authenticate.password.confirm': '認證',
    'account.enable.2FA.title': '啟用兩因素身份驗證',
    'account.Authenticate.tip':
        '啟用 2 因素身份驗證確保您的帳戶具有更高的安全性。 請安裝 Google Authenticator 或 Microsoft Authenticator',
    'account.Authenticate.ScanCode.title': '1 / 扫描下面码或使用您的驗證應用程序驗證代碼',
    'account.Authenticate.ScanCode.cannotScan': '無法掃描此碼',
    'account.Authenticate.code.text.title': '將此代碼輸入到身份驗證器應用程序：',
    'account.Authenticate.input.title': '2 / 從您的驗證應用程序輸入 6 位驗證碼',
    'account.error.faInvalid': '無效驗證碼',
    'account.Authenticate.2fa.enable': '啟用',
    'account.success.enable.fa': '成功啟用兩因素身份驗證',
    'account.success.disable.fa': '禁用两因素身份驗證',
    'account.disable.2FA': '禁用 2FA',
};
