export default {
    'application.uploading': '上載中',
    'application.uploadingTip': '上載應用程序，退出不會保存應用程序。',
    'application.exit': '離開',
    'application.cancel': '取消',
    'application.pleaseWait': '請等待當前的APK上傳完成。',
    'application.fileNameTooLong': '文件名太長',
    'application.support100Mb': '最大支援100MB',
    'application.alreadyHasNewer': '已經有此應用程序的較新版本。',
    'application.internetFailed': '連網失敗。',
    'application.uploadSuc': '上傳成功。',
    'application.deleteApk': '刪除APK',
    'application.deleteApkTip': '刪除後，{val1}將從應用程序管理列表中刪除。',
    'application.delete': '刪除',
    'application.deleteSuc': '應用程序已成功刪除。',
    'application.pleaseSelectDevice': '請選擇一個設備。',
    'application.uploadApk': '上載APK',
    'application.installApp': '安裝應用',
    'application.install': '安裝',
    'application.uninstallFromDevice': '從設備上卸載',
    'application.uninstall': '卸載',
    'application.uninstallTip': '卸載後，此應用將從設備中刪除。',
    'application.disableInDevice': '禁用設備',
    'application.disable': '禁用',
    'application.disableTip': '禁用後，該應用程序將無法在已安裝該應用程序的設備中使用。',
    'application.enableInDevice': '在設備中啟用',
    'application.enable': '啟用',
    'application.enableTip': '啟用後，該應用程序將在已安裝該應用程序的設備中可用。',
    'application.unavailable': '該應用將在更新期間不可使用。',
    'application.multiTimezoneSelected': '命令將在設備的本地時區執行。 （選擇多個時區時）',
    'application.selected': '已選',
    'application.applicationName': '應用名稱',
    'application.appVersion': '版本',
    'application.appSize': '大小',
    'application.searchTip': '搜索{val1}',
    'application.reset': '重置',
    'application.search': '搜索',
    'application.pleaseUpload': '請上傳APK',
    'application.file.location': '檔案位置',
    'application.file.tooltip':
    '此套裝軟體不支持靜默安裝。 請手動安裝。',
};
