export default {
    'commandModal.pleaseSelectABell': '請選擇一個鈴聲。',
    'commandModal.bellList': '鈴聲清單',
    'commandModal.bellName': '鈴聲名稱',
    'commandModal.size': '尺寸',
    'commandModal.time': '時間',
    'commandModal.pleaseUploadABell': '請上傳鈴聲',
    'commandModal.fileSize10M': '檔案大小應在10MB以內',
    'commandModal.bellFormat': '文件應為MP3，WAV，AAC，OGG格式',
    'commandModal.selectUpto': '一次最多選擇{val1}。',
    'commandModal.reachedMaxLimit': '達到最大限制。',
    'commandModal.fileNotSupport': '當前文件格式不支持預覽。',
    'commandModal.youHaveSelected': '您已選擇此文件。',
    'commandModal.sureDelete': '您確定要刪除它嗎？',
    'commandModal.deleteFile': '刪除文件？',
    'commandModal.bellForamtHint': '格式：MP3，WAV，AAC，OGG',
    'commandModal.bellSize': '大小：最大10MB',
    'commandModal.playWhole': '播放全部',
    'commandModal.setAtLeastOneCycle': '設置至少重複一次',
    'commandModal.lockDuration': '鎖定時間',
    'commandModal.now': '現在',
    'commandModal.selectATimePeriod': '請選擇一個時間段',
    'commandModal.timeExpired': '時間到期',
    'commandModal.endTimeCannotEarlier': '結束時間不能早於開始時間',
    'commandModal.timeCannotRepeat': '時間不能重複',
    'commandModal.periodNotRepeat': '時間段不能重複',
    'commandModal.selectMutimedia': '請選擇一個多媒體。',
    'commandModal.upTo50Uploads': '最多50次上傳',
    'commandModal.annFileFormat': '格式：MP4，AVI，JPG，PNG',
    'commandModal.annFileSize': '大小：最大200MB',
    'commandModal.annTitle': '多媒體',
    'commandModal.selectAMutimedia': '選擇一個多媒體',
    'commandModal.pleaseUploadAMutim': '請上傳一個多媒體',
    'commandModal.preiew': '預覽',
    'commandModal.deviceWillPlayAuto': '（設備執行時將自動播放）',
    'commandModal.mutimediaList': '多媒體列表',
    'commandModal.fileMultFormat': '檔案應為MP4，AVI，JPG，PNG格式',
    'commandModal.fileMultSizeLimit': '檔案大小應在200MB以內',
    'commandModal.wallpaperFormat': '文件應為JPG格式',
    'commandModal.pleaseUploadA': '請上傳{val1}',
    'commandModal.wallTitle': '壁紙',
    'commandModal.logoTitle': '圖標',
    'commandModal.soundModeStandard': '標準',
    'commandModal.soundModeClassroom': '課堂',
    'commandModal.soundModeMetting': '會議',
    'commandModal.soundModeCustom': '自訂',
    'commandModal.imageModeStandard': '標準',
    'commandModal.imageModeBright': '明亮模式',
    'commandModal.imageModeSoft': '柔和',
    'commandModal.imageModeCustom': '自訂',
    'commandModal.switchAnd': '切換android啟用',
    'commandModal.allowToSwitch': '允許設備切換到Android通道。',
    'commandModal.NoSignalTimeNever': '永不',
    'commandModal.NoSignalTime1min': '1分鐘',
    'commandModal.NoSignalTime3min': '3分鐘',
    'commandModal.NoSignalTime5min': '5分鐘',
    'commandModal.NoSignalTime10min': '10分鐘',
    'commandModal.NoSignalTime30min': '30分鐘',
    'commandModal.NoSignalTime45min': '45分鐘',
    'commandModal.NoSignalTime60hour': '60分鐘',
    'commandModal.NoSignalTime90hour': '90分鐘',
    'commandModal.NoSignalTime120hour': '120分鐘',
    'commandModal.remainPowerOff': '保持電源關閉',
    'commandModal.autoPowerOn': '自動開機',
    'commandModal.returnPowerState': '停電前返回電源狀態',
    'commandModal.noSignalShutdown': '無訊號關閉',
    'commandModal.autoPowerOff': '無訊號輸入時自動關閉電源。',
    'commandModal.displayAfter': '停電後顯示',
    'commandModal.deviceDisplayReconn': '停電後設備顯示重新連接。',
    'commandModal.wallpaper': '壁紙',
    'commandModal.logo': '圖標',
    'commandModal.useDefault': '默認情況下使用',
    'commandModal.wallpaperCustom': '自訂',
    'commandModal.returnToDefault': '（返回到設備的默認{val1}）',
    'commandModal.pleaseSelect': '請選擇一個{val1}。',
    'commandModal.pleaseUpload': '請上傳一個{val1}',
    'commandModal.pleaseSelectOne': '請選擇一個',
    'commandModal.upTo20Uploads': '最多20個上傳',
    'commandModal.wallSizeLimit': '大小：最大3MB（1920 * 1080）',
    'commandModal.list': '清單',
    'commandModal.selectedDevices': '{num} 所選設備',
    'commandModal.filePublish.pleaseSelect': '請選擇一個',
    'commandModal.filePublish.selectUpTo': '一次最多選擇{val1}。',
    'commandModal.filePublish.reachTheMaximum': '達到最大限制。',
    'commandModal.filePublish.fileNameTooLong': '檔案名太長',
    'commandModal.filePublish.fileSize200': '檔案大小應在200MB以內',
    'commandModal.filePublish.pleaseUpload': '請上傳檔案',
    'commandModal.filePublish.selectAFile': '選擇一個檔案',
    'commandModal.filePublish.fileWillSave': '（文件將保存到查找器）',
    'commandModal.filePublish.multiTimeZoneSelected':
        '命令將在設備的本地時區執行。 （選擇多個時區時）',
    'commandModal.filePublish.fileList': '檔案清單',
    'commandModal.filePublish.fileName': '文件名',
    'commandModal.filePublish.format': '格式',
    'commandModal.filePublish.fileSize': '大小',
    'commandModal.filePublish.selected': '您已選擇此文件。',
    'commandModal.filePublish.deleteConfirmTip': '您確定要刪除它嗎？',
    'commandModal.filePublish.deleteConfirmTip1': '刪除文件？',
    'commandModal.filePublish.delete': '刪除',
    'commandModal.filePublish.upToFilesUploads': '最多上傳{val1}個文件',
    'commandModal.notification.times1': '1次',
    'commandModal.notification.times3': '3次',
    'commandModal.notification.times5': '5次',
    'commandModal.notification.times10': '10次',
    'commandModal.notification.times20': '20次',
    'commandModal.notification.canNotEmpty': '輸入不能空白',
    'commandModal.notification.text': '文字',
    'commandModal.notification.preview': '預覽',
    'commandModal.notification.displayArea': '顯示區域',
    'commandModal.notification.loopTimes': '循環時間',
    'commandModal.announcement.displayArea': '顯示區域',
    'commandModal.turnOnTheSwitch': '打開開關以設置時間和重複命令。',
    'commandModal.setAsSchedule': '設置為排程',
    'commandModal.setTime': '設置時間',
    'commandModal.offlineMode': '離線模式',
    'commandModal.offlineTooltip': '離線模式允許設備在沒有網路連接的情況下執行命令。',
    'commandModal.timed': '定時的',
    'commandModal.timeTooltip': '指令將在設備的本地時區執行。 （選擇多個時區時）',
    'commandModal.recurr': '重複發生',
    'commandModal.recurrTooltip': '一個設備只有一組重複執行命令。新的重複命令將覆蓋舊的命令。',
    'commandModal.selectATime': '選擇一個時間。',
    'commandModal.only10times': '一個週期只能設置10次',
    'commandModal.addATime': '添加時間',
    'commandModal.addARecurring': '添加重複',
    'commandModal.multipleTimeZones': '“選擇了多個時區的設備。將日期和時間顯示為UTC {val1}。”',
    'commandModal.oneTimeZones': '“已選擇UTC {val1}中的設備。將日期和時間顯示為UTC {val2}。”',
    'commandModal.loading': 'L O A D I N G',
    'commandModal.videoNotPlayed': '如果此視頻無法正常播放，請下載並觀看。',

    'commandModal.playmode': '播放模式',
    'commandModal.playmode.loop': '迴圈',
    'commandModal.playmode.duration': '播放時長',
    'commandModal.playmode.right': '操作權',
    'commandModal.playmode.turnoff': '關閉開關，讓用戶隨時關閉命令。',
    'commandModal.playmode.times': '{value} 次',
    'commandModal.playmode.throughtout': '貫穿',
    'commandModal.playmode.min': '{value} 分鐘',
    'commandModal.powerOnHint': '{num} 設備無法執行開機命令,由於 WOL 服務器錯誤',
    'commandModal.blockList.allowList': '允許列表',
    'commandModal.blockList.closeHint': '關閉設備上現有的白名單或阻止名單',
    'commandModal.blockList.listManage': '列表管理',
    'commandModal.blockList.blockHint': '不允許的網址',
    'commandModal.blockList.allowHint': '允許使用特定 URL',
    'commandModal.blockList.URL': '網址',
    'commandModal.blockList.enterURL': '輸入網址',
    'commandModal.blockList.mustBeValidURL': '必須是有效的網址',
    'commandModal.blockList.URLExist': '網址已存在',
    'commandModal.blockList.enterURLHere': '在此輸入網址',
    'commandModal.blockList.listType': '列表類型',
    'commandModal.blockList.list': '列表',
    'commandModal.blockList.pleaseSelectAURL': '請選擇一個網址',
    'commandModal.blockList.deleteUrl': '刪除網址？',
    'commandModal.blockList.exist.url':'網址已存在'

};
