export default {
    'common.noData': '沒有數據',
    'common.unknownError': '未知錯誤。',
    'common.agreementTitle': 'Bytello設備管理系統用戶協議',
    'common.policyTitle': 'Bytello設備管理系統隱私政策',
    'common.quitExpPlanTitle': '退出[Bytello設備管理系統]產品用戶體驗計劃的通知',
    'common.userExpPlanTitle': 'Bytello設備管理系統產品用戶體驗計劃',
    'common.filter.clear': '清除篩選',
    'common.filter.apply': '套用篩選器',
    'common.pleaseSelectDevice': '請選擇設備！',
    'common.selectCmd': '選擇指令',
    'common.allTypes': '所有類型',
    'common.soundBar': 'Sound bar',
    'common.ifp': 'IFP',
    'common.paginationTotal': '共{val1}個項目',
    'common.paginationTotal20Page': '20 /頁',
    'common.paginationTotal40Page': '40 /頁',
    'common.paginationTotal80page': '80 /頁',
    'common.executeNow': '立即執行',
    'common.recurring': '重複發生',
    'common.timed': '定時',
    'common.powerOn': '開機',
    'common.powerOff': '關機設置',
    'common.reboot': '重新啟動',
    'common.bells': '鐘聲',
    'common.screenLock': '螢幕鎖定',
    'common.blockList': '黑名單',
    'common.notification': '文本',
    'common.announcement': '多媒體',
    'common.filePublish': '檔案發佈',
    'common.liveChannel': '直播頻道',
    'common.soundMode': '聲音模式',
    'common.imageMode': '影像模式',
    'common.powerState': '電源狀態',
    'common.androidState': 'Android狀態',
    'common.wallpaper': '桌布設定',
    'common.logo': '開機標誌',
    'common.emergency': '警報',
    'common.softwareUpdate': '軟體更新',
    'common.applicationInstall': '應用安裝',
    'common.applicationUninstall': '應用程序卸載',
    'common.applicationAble': '應用程序（啟用/禁用）',
    'common.inputSwitch': '輸入源切換',
    'common.actions': '動作',
    'common.selectGroup': '選擇組',
    'common.deviceControl': '設備控制',
    'common.message': '消息',
    'common.deviceSetting': '設備設定',
    'common.allGroup': '所有組',
};
