export default {
    'dashboard.title': '儀表板',
    'dashboard.activeTrend': '在線趨勢',
    'dashboard.statisticsTheDaily': '統計所有設備的每日在線狀態',
    'dashboard.inactiveDevice': '離線設備',
    'dashboard.devices': '設備',
    'dashboard.deviceOffline': '設備脫機超過7天',
    'dashboard.deviceName': '設備名稱',
    'dashboard.Tags': '標籤',
    'dashboard.lastOnlineTime': '上次上網時間',
    'dashboard.adminAccount': '管理員帳號',
    'dashboard.organizationCode': '組織代碼',
    'dashboard.maxConnection': '最大連接數',
    'dashboard.connectedNum': '已註冊的設備',
    'dashboard.onlineNum': '在線設備',
    'dashboatd.date': '日期',
    'dashboatd.onlineNumber': '在線數量',
    'dashboard.credits': '學分',
    'dashboard.daysRemain': '剩余天數',
};
