export default {
    'deviceList.ifpAll': 'IFP：全部（{val1}）',
    'deviceList.soundbarAll': 'Sound bar：全部（{val1}）',
    'deviceList.allTypeAll': '所有類型：全部（{val1}）',
    'deviceList.deviceErased': '所有設備數據將被刪除。',
    'deviceList.unbindTip': '設備“ {val1}”將與{val2}解除綁定。',
    'deviceList.groupNameCannotEmpty': '群組名稱不能為空白',
    'deviceList.allDevices': '所有裝置',
    'deviceList.groupNameExists': '設備群組“所有設備”已存在！',
    'deviceList.groupNameAlreadyExists': '設備群組“ {val1}”已經存在！',
    'deviceList.deviceGroupCreated': '設備群組已創建',
    'deviceList.filter.searchDeviceName': '搜索設備名稱',
    'deviceList.filter.selectStatus': '選擇狀態',
    'deviceList.filter.selectTimezone': '選擇時區',
    'deviceList.filter.selectTags': '選擇標籤',
    'deviceList.table.deviceName': '設備名稱',
    'deviceList.table.status': '狀態',
    'deviceList.table.tags': '標籤',
    'deviceList.table.school': '組織',
    'deviceList.table.timezone': '時區',
    'deviceList.table.nextCmd': '下一條指令',
    'deviceList.table.coAdmin': '共同管理員',
    'deviceList.table.details': '細節',
    'deviceList.table.searchName': '搜尋{val1}',
    'deviceList.table.reset': '重置',
    'deviceList.table.search': '搜尋',
    'deviceList.table.device': '設備',
    'deviceList.group': '組',
    'deviceList.hasTypeAll': '{val1}',
    'deviceList.tabel.all': '全選',
    'deviceList.tabel.list': '列表',
    'deviceList.tabel.grid': '平鋪',
    'deviceList.select.group': '組',
    'device.table.school': '學校',
};
