export default {
    'menu.home': '家',
    'menu.dashboard.dashboard': '儀表板',
    'menu.deviceManagement': '設備',
    'menu.deviceManagement.allTypes': '所有類型',
    'menu.deviceManagement.ifp': 'IFP',
    'menu.deviceManagement.soundBar': 'Sound bar',
    'menu.deviceManagement.ledWall': 'Led wall',
    'menu.functions': '先進的',
    'menu.functions.profile': '配置',
    'menu.functions.appManage': '應用領域',
    'menu.functions.inputSwitch': '輸入源切換',
    'menu.functions.firmwareUpdate': '固件升級',
    'menu.functions.softwareUpdate': '軟體更新',
    'menu.commandRecords': '記錄',
    'menu.commandRecords.exeHistory': '歷史',
    'menu.commandRecords.inSchedule': '定時任務',
    'menu.user.userManagement': '用戶管理',
    'menu.account.accountSettings': '帳號設定',
    'menu.systemManage': '系統',
    'menu.systemManage.adminManage': '用戶',
    'menu.systemManage.schoolManage': '組織',
    'menu.systemManage.passwordManage': '密碼',
    'menu.systemManage.userSettings': '設置',
    'menu.resources.resources': '資源',
    'header.home': '首頁',
    'breadcrumb.item': '麵包屑項目',
    'breadcrumb.debugger': '麵包屑調試器',
    'global.error.network': '網路錯誤',
    'global.network.timeout': '超時',
    'global.network.error': '網路錯誤',
    'global.btn.ok': '好',
    'upload.getUploadPolicyError': '上傳失敗',
    'upload.networkError': '上傳失敗',
    'upload.cancelled': '取消任務上傳！',
    'upload.formatError': '文件格式錯誤',
    'upload.fileNameError': '文件名太長',
    'upload.parsing': '正在解析...',
    'upload.fileExist': '文件已存在',
    'upload.fileNameTooLong': '文件名太長',
    'upload.fileJPG': '文件應為JPG格式',
    'upload.file3M1920': '檔案大小不得超過3MB（1920 * 1080）',
    'upload.formatJPG': '格式：JPG',
    'upload.size3M': '大小：最大3MB（1920x1080）',
    'global.cancel': '取消',
    'global.confirm': '確認',
    'global.save': '保存',
    'global.send': '發送',
    'global.delete': '刪除',
    'global.close': '關閉',
    'global.commandSent': '命令已發送',
    'global.unableSend': '無法發送',
    'global.commandSave': '命令已保存',
    'global.unableSave': '無法保存',
    'global.commandDelete': '命令已刪除',
    'global.unableDelete': '無法刪除',
    'global.empty': '空的',
    'header.infoCenter': '資訊中心',
    'header.allSchool': '所有組織',
    'header.sendAll': '全部發送',
    'header.feedback': '發送反饋',
    'header.todayCommand': '今天的指令',
    'header.admin': '管理員',
    'header.trial': '試用',
    'header.inactive': '不活動',
    'header.expired':'已到期',
    'header.emergency': '警報',
    'global.lockTip': '之後，該帳戶將被鎖定，並且激活碼將發送到您的電子郵件。',
    'global.loading': '載入中',
    'global.accept': '接受',
    'global.reject': '拒絕',
    'global.protocplTip1': '通過註冊，我接受',
    'global.protocplTip2': '並確認接受',
    'global.userAgreeement': '用戶協議',
    'global.policy': '隱私政策',
    'global.pleaseCheck': '請檢查用戶協議和隱私政策。',
    'global.switchDefaultTip': '打開開關以設置時間和重複命令。',
    'global.noResults': '沒結果',
    'global.off': '離線',
    'global.on': '在線',
    'global.language': '語言',
    'global.enroll': '註冊',
    'global.last': '最後',
    'global.next': '下一個',
    'global.continue': '繼續',
    'global.saveChanges': '保存更改',
    'global.mode': '模式',
    'global.tags': '標籤',
    'global.detail': '細節',
    'global.update.time': '更新時間',
    'global.not.configured': '未配置',
    'global.save.and.sync': '保存和同步',
    'global.license': '執照',
    'global.day.remaing': '剩余天數',
    'global.linces.records': '記錄',
    'global.license.helper.title': '剩余天數是此帳戶必須訪問產品的時間長度。',
    'global.license.helper.tip1': '訪問時間長度=介於[到期時間]和[信用/注册設備]之間的最小值',
    'global.license.helper.tip2': '[到期時間]是截止到期日期可以使用的天數。',
    'global.license.helper.tip3': '[學分/注册設備]是注册設備使用剩餘信用支持的天數。',
    'global.uploading':'上傳',
    'global.leave': '離開',
    "global.change":"改變",
    "global.sending":"發送",
    "global.get.code":"獲取代碼",
    "global.resend.code":"重新發送驗證碼",
    "global.change.email":"更改電子郵件",
    "global.unknow.error":"未知錯誤"
};
