export default {
    'group.deviceName': '設備名稱',
    'group.timezone': '時區',
    'group.groupManagement': '集團管理',
    'group.delGroupTip': '刪除這個群組？',
    'group.del': '刪除',
    'group.quit': '放棄',
    'group.popBtnText': '退出{val1}一個群組？',
    'group.create': '創建',
    'group.save': '儲存',
    'group.enterGroupName': '在此處輸入群組名稱',
    'group.creating': '創造',
    'group.modify': '修改',
    'group.addNew': '新增群組',
    'group.all': '所有',
    'group.allDevices': '所有設備{val1} / {val2}',
    'group.selectedDevices': '所選設備{val1}',
    'group.conditionLimit': '達到條件限制',
    'group.addCondition': '添加條件',
    'group.autoAllocation': '自動分配',
    'group.manualSelection': '手動選擇',
    'group.enterConditionHere': '在此輸入條件',
    'group.enterCondition': '輸入條件',
    'group.select': '選擇',
};
