export default {
    'channel.message.error': '請選擇一個頻道',
    'channel.select.placehoder': '選擇一個頻道',
    'channel.live.name': '頻道名稱',
    'channel.live.title': '直播頻道列表',
    'channel.modal.title': '刪除頻道?',
    'channel.modal.content': '您要刪除此頻道嗎？',
    'channel.modal.oktext': '刪除',
    'channel.form.nameerror': '名稱不能為空。',
    'channel.form.addresserror': '地址不能為空。',
    'channel.form.formaterror': '地址格式錯誤。',
    'channel.btn.create': '創造',
    'channel.btn.span': '支持的實時流協議：RTMP，RTSP和HTTP實時流',
    'channel.form.title': '建立直播頻道',
    'channel.form.labelname': '頻道名稱',
    'channel.form.labeladdress': '網址',
    'channel.live.label': '直播頻道',
    'channel.btn.channellist': '直播頻道列表',
    'channel.form.addressholder': '頻道地址',
    'channel.name.exist': '頻道名稱已存在！',
    'channel.preview.notsupport': '該頻道不支持預覽',
    'channel.btn.newcreate': '请创建一个直播频道',
    'channel.edit.livechannel': '編輯直播頻道',
    'channel.edit.save': '保存',
};
