export default {
    'login.error.emailEmpty': '請輸入您的電子郵件地址。',
    'login.error.emailInvalid': '抱歉，此電子郵件無效。',
    'login.error.emailLetterInvalid':
        '抱歉，只允許使用字母（a-z），數字（0-9）和符號（@ ._）。',
    'login.error.emailNotFound': '找不到與此電子郵件帳戶。',
    'login.error.createWidthAccount': '用這個帳號創建？',
    'login.error.pwdEmpty': '請輸入密碼。',
    'login.error.pwdInvalid': '抱歉，此密碼不正確。',
    'login.error.pwdEqualMail': '抱歉，密碼與您的電子郵件地址不匹配',
    'login.error.pwdLength': '密碼必須包含8-16個字符。',
    'login.error.pwdFormat': '密碼必須具有以下兩個類別:數字/字母/特殊字符',
    'login.error.specialSymbol':
        '抱歉，只允許使用字母（a-z），數字（0-9）和特殊字符（〜！@＃$％^＆*（）+-=，。/; | <>？）',
    'login.error.pwdNotEqual': '這些密碼不匹配',
    'login.error.notLogin': '您尚未登錄，請登錄。',
    'login.error.verify': '請確認',
    'login.label.forgotPwd': '忘記密碼？',
    'login.label.email': '電子郵件',
    'login.label.notAccount': '沒有賬號？',
    'login.label.createAccount': '創建一個',
    'login.label.pwd': '密碼',
    'login.title.account': '帳戶',
    'login.title.login': '登錄',
    'login.title.tips': '提示',
    'login.btn.login': '登錄',
    'login.btn.confirm': '確認',
    'login.btn.ok': '好',
    'login.placeHolder.email': '輸入你的電子郵箱地址',
    'login.placeHolder.pwd': '輸入密碼',
    'login.logout': '登出',
    'login.error.noAuth': '帳戶未授權。',
    'login.forgetPwd': '忘記密碼',
    'login.forgetTip':
        '輸入您的電子郵件地址，我們將向您發送一個驗證碼鏈接以重置密碼。',
    'login.verifyAgain': '發生了錯誤。請再次驗證。',
    'login.next': '下一個',
    'login.backToLogin': '回到登入',
    'login.loginFailed': '登錄失敗',
    'login.accountExpired': '帳戶已過期，請聯繫上級帳戶',
    'login.accountNoAuth': '帳戶未授權',
    'login.lockChances': '還剩{val1}個機會',
    'login.resetSuc': '重置成功！登錄…',
    'login.reset.characters816': '8-16個字符',
    'login.reset.charactersCategories': '以下兩類：數字/字母/特殊字符',
    'login.reset.canNotMatch': '無法匹配您的電子郵件地址',
    'login.reset.curPwd': '當前密碼',
    'login.reset.newPwd': '新密碼',
    'login.reset.confirmPwd': '確認密碼',
    'login.modifyPwd': '修改密碼',
    'login.title.2FA': '兩因素身份驗證',
    'login.2FA.input.tip':'輸入第三方應用的驗證碼',
    "logout.text.tip":"您將登出"
  };
  