export default {
    'noDevice.deviceManagement': '設備管理',
    'noDevice.enrollDevice': '設備綁定',
    'noDevice.deviceEnrollment': '設備註冊',
    'noDevice.bindThrough': '通過設備上的{type}應用進行綁定',
    'noDevice.adminAccIs': '管理員帳戶:',
    'noDevice.schoolCodeIs': '組織代碼: ',
    'noDevice.seeMore': '您可以查看更多信息在 ',
    'noDevice.option1': '選項1',
    'noDevice.enterConnInfo': '輸入連接信息',
    'noDevice.option2': '選項2',
    'noDevice.enrollmentUsingUSB': '使用USB註冊',
    'noDevice.download': '下載',
    'noDevice.inUDisk': `在U盤上，請勿修改。`,
    'noDevice.makeSureTheApp': '確保已安裝該應用程序。',
    'noDevice.insertUDisk': '將U盤插入設備。',
    'noDevice.clickBind': '單擊綁定，信息將自動填寫。',
    'noDevice.allSchoolHint': '選擇組織在“註冊”中查看更多信息',
    'noDevice.netErr': '網絡錯誤。請重新下載',
};
