export default {
    'profile.createNew': '新建',
    'profile.time': '創建於 {createTime}，最後修改於 {modifyTime}',
    'profile.set': '設為默認',
    'profile.apply': '應用',
    'profile.type': '類型',
    'profile.applied': '已應用',
    'profile.remove': '刪除默認值',
    'profile.modal.apply': '應用配置',
    'profile.modal.profilename': '配置名稱',
    'profile.detail.delete': '刪除配置',
    'profile.detail.seeprofile': '查看配置',
    'profile.create.new': '創建 {os} 配置',
    'profile.create.edit': '編輯 {os} 配置',
    'profile.create.security': '安全',
    'profile.create.app': '應用管理',
    'profile.create.securitydes':
        '屏蔽：阻止列表網站以阻止用戶訪問該網站。 將網站列入允許名單以阻止用戶訪問除允許名單之外的任何網站',
    'profile.create.appdes': '支持靜默安裝應用程序',
    'profile.create.appsettingdes': '設置電源、顯示等設備狀態',
    'profile.create.config': '配置',
    'profile.create.checkprofilename': '配置名称不能為空',
    'profile.create.checkurl': '網址不能為空',
    'profile.create.whiteblack': '阻塞',
    'profile.create.addurl': '添加網址',
    'profile.create.urls': '網址',
    'profile.create.appremove': '刪除配置文件時從設備中刪除應用程序',
    'profile.create.appsmanagement': '應用管理',
    'profile.create.installapps': '安裝應用',
    'profile.create.addapps': '添加應用',
    'profile.create.appname': '應用名稱',
    'profile.create.sleep': '自動休眠時間',
    'profile.create.sleepdes': '指定時間內無操作自動進入休眠模式',
    'profile.create.poweroff': '自動關機',
    'profile.create.poweroffdes': '一段時間不操作設備自動關機',
    'profile.create.signal': '無信號關機',
    'profile.create.signaldes': '無信號輸入時自動關機',
    'profile.create.powersetting': '停電設置',
    'profile.create.powersettingdes': '斷電後設備顯示重新連接',
    'profile.create.wakeon': '啟用喚醒',
    'profile.create.andriodchannel': '安卓頻道',
    'profile.create.andriodchanneldes': '允許設備切換到 Android 頻道',
    'profile.create.soundmode': '聲音模式',
    'profile.create.imagemode': '圖像模式',
    'profile.create.imagemodedes': '圖像模式僅支持非 Android 渠道',
    'profile.create.autoturnoff': '自動關閉屏幕',
    'profile.create.autoturnoffdes': '指定時間內無操作自動關閉屏幕',
    'profile.create.sleepmode': '自動將設備置於睡眠模式',
    'profile.create.sleepmodedes': '指定時間段內無操作時自動將設備置於睡眠模式',
    'profile.create.poweroffopt': '離開',
    'profile.create.poweronopt': '開啟',
    'profile.create.powerlastopt': '最後的',
    'profile.create.none': '從不',
    'profile.create.warning': '僅 V1.9.0 或更高版本的客戶端支持使用配置文件',
    'profile.create.default': '默認',
    'profile.create.savesuccess': '保存成功',
    'profile.create.savefailed': '保存失敗',
    'profile.modal.deletetitle': '刪除配置',
    'profile.modal.deletecontent': '您確定要刪除配置文件嗎？',
    'profile.create.enterurl': '輸入網址',
    'profile.create.deletewhiteblack': '删除阻止列表/允许列表',
    'profile.create.uninstallapps': '卸载应用',
    'profile.create.wakeonopt': '局域网唤醒',
    'profile.create.autochannelopt': 'Andriod通道',
    'profile.create.sleepmodeopt': '睡眠模式',
    'profile.route.title': '配置未保存',
    'profile.route.content': '配置未保存，您確定要離開此頁面嗎？',
    'profile.app.size': '大小：最大 300MB',
    'profile.app.upfiles': '最多可上傳 50 個文件',
    'profile.create.hidesidebar': '隱藏側邊欄',
    'profile.data.and.time.format.automatically': '自動地',
    'profile.data.and.time.format.matically': '手動',
    'profile.12.hour.time': '12小時制',
    'profile.24.hour.time': '24小時制',
    'profile.save.failed': '保存失敗',
    'profile.save.failed.tip': '請填寫所有必填字段或關閉配置以保存配置文件',
    'profile.device.general.settings': '通用設置',
    'profile.update.software': '更新軟件',
    'profile.associated.devices': '關聯設備',
    'profile.not-compliant.num': '不合規',
    'profile.bytello.devices': '僅適用於 Bytelo 的設備支持的設置',
    'profile.date.and.time.label': '日期和時間',
    'profile.date.and.time.helper': '使用網絡提供的時間',
    'profile.devices.time.zone': '時區',
    'profile.devices.time.format': '時間格式',
    'profile.devices.non.compliant': '不合規',
    'profile.devices.compliant': '合規',
    'profile.action.sync': '同步',
    'profile.devices.compoliant.status': '設備 - 合規狀態',
    'profile.details': '細節',
    'profile.applied.devices': '應用設備',
    'profile.create.brief1': '策略是一組配置和限制，旨在管理和保護在 DMS 中註冊的設備。',
    'profile.create.brief2':
        '將配置文件設置為默認配置文件後，當設備註冊到您的組織時，它將自動接收並執行默認配置文件。',
    'profile.default.time.zone': '不要改變',
    'profile.set.default': '設為默認',
    'profile.associated.status': '選擇設備兼容狀態',
    'profile.associate': '聯繫',
    'profile.devices': '設備',
    'profile.add.devices': '添加設備',
    'profile.associate.devices': '關聯設備',
    'profile.edit.savesuccess': '保存並同步成功',
};
