export default {
    'register.activateSchool': '激活組織',
    'register.hasoOpenPer': ' 已為您打開{type}權限。',
    'register.licenseInfo': 'License 信息',
    'register.licenseType': 'License 類型',
    'register.maxPanel': '最大面板數',
    'register.avaTime': '可用時間',
    'register.schoolInfo': '組織信息',
    'register.schoolCode': '組織代碼',
    'register.adminAccount': '管理員帳號',
    'register.schoolName': '組織名稱',
    'register.location': '位置',
    'register.hint': '如有任何疑問，請聯繫 ',
    'register.maxPanelHint': '如需增加數量，請聯繫 ',
    'register.selectLocation': '選擇您的國家或地區',
    'register.typeSchoolName': '輸入組織名稱',
    'register.schoolNameCannotRepeat': '組織名稱不能在一個區域內重複。',
    'register.selectLocationHint': '請選擇組織位置。',
    'register.inputNoEmpty': '輸入不能為空。',
    'register.4Digit': '至少4位數字',
    'register.quantity': '數量',
    'register.credits': '學分',
};
