export default {
  'remote.detail.control': '屏幕控制',
  'remote.detail.realtime': '實時顯示',
  'remote.full.turnon':'屏幕控制已打開',
  'remote.full.turnoff':'屏幕控制已關閉',
  'remote.full.exitcontrol':'退出屏幕控制',
  'remote.remote.control':'遠程控制：',
  'remote.full.control':'屏幕控制',
  'remote.preview.off':'設備已關閉',
  'remote.preview.getscreen':'正在獲取屏幕...',
  'remote.video.offline':'該設備處於離線狀態，請嘗試檢查設備狀態或網絡狀態',
  'remote.video.error':'該設備正在由另一個用戶連接。 請稍後再試',
  'remote.video.failedtitle':'該設備離線.',
  'remote.video.try':'嘗試',
  'remote.video.checkpower':'·檢查設備的電源和網絡狀態',
  'remote.video.buttonreconnect':'·點擊下面的按鈕嘗試重新連接',
  'remote.video.button':'重新連線',
  'remote.video.loading':'載入中',
  'remote.command.tooltip':'現在執行',
  'remote.command.poweron':'開機',
  'remote.command.poweroff':'關機',
  'remote.command.reboot':'重啟',
  'remote.command.lock':'鎖屏',
  'remote.command.unlock':'解鎖',
  'remote.pop.power':'設備電源',
  'remote.pop.lock':'設備鎖',
  'remote.reject.title':'設備用戶被拒絕',
  'remote.reject.conent':'需要遠程控制的用戶許可，使用前請先與用戶協商。',
  'remote.reject.okexit':'退出',
  'remote.reject.ok':'好',
  'remote.device.touch':'設備觸控',
  'remote.tooltip.waiting':'等待許可',
};
