export default {
    'user.title': '管理員管理',
    'user.username': '用戶名',
    'user.account': '帳戶',
    'user.role': '角色',
    'user.latestOperation': '最新操作',
    'user.deviceNum': '設備編號',
    'user.commandNum': '指令編號',
    'user.remotePwd': '{type}密碼',
    'user.screenLockPwd': '屏幕鎖定密碼',
    'user.details': '細節',
    'user.remotePwdStatus.disabled': '禁止使用',
    'user.remotePwdStatus.visible': '可見',
    'user.remotePwdStatus.invisible': '無形',
    'user.createSubAccount': '添加用戶',
    'user.noAccountHint': '請先創建一個子帳戶',
    'user.deleteSucHint': '子帳戶{account}已從{unitName}中刪除。',
    'user.delete': '刪除',
    'user.deleteSubAccount': '刪除子賬戶',
    'user.deleteConfirm': '您要從{unitName}刪除{account}嗎？',
    'user.anEmailWillSent': '電子郵件將發送到{account}。',
    'user.addAccountSucHint': '{email}已添加到{unitName}。',
    'user.addAccountErrHint': '無法創建子帳戶。',
    'user.information': '訊息',
    'user.device': '設備',
    'user.permission': '允許',
    'user.prev': '上一個',
    'user.create': '創建',
    'user.next': '下一個',
    'user.createAPwd': '創建一個密碼：',
    'user.816Characters': '8-16個字符',
    'user.twoCategories': '以下兩類：數字/字母/特殊',
    'user.cannotMatchEmail': '無法匹配您的電子郵件地址',
    'user.accountAlreayHas': '此帳戶已經是組織的用戶。',
    'user.emailCheckEmpty': '請輸入您的電子郵件地址。',
    'user.emailCheckHasSpecialSymbol': '抱歉，只允許使用字母（a-z），數字（0-9）和符號（@ ._）。',
    'user.emailCheckFormat': '抱歉，此電子郵件無效。',
    'user.pwdCheckEmpty': '請輸入密碼。',
    'user.pwdCheckMatch': '抱歉，密碼與您的電子郵件地址不符。',
    'user.pwdCheckLength': '密碼必須至少包含8個字符。',
    'user.pwdCheckHasSpecialSymbol':
        '抱歉，只允許使用字母（a-z），數字（0-9）和特殊字符（〜！@＃$％^＆*（）+-=，。/; \\ | <>？）',
    'user.pwdCheckFormat': '密碼必須至少包含以下兩項：數字/字母/特殊字符。',
    'user.usernameCheckEmpty': '請輸入用戶名',
    'user.usernameCheckFormat': '抱歉，只允許輸入字母（a-z），數字（0-9）',
    'user.password': '密碼',
    'user.accountMatched': '帳戶匹配',
    'user.enterAnEmail': '輸入電子郵件地址',
    'user.modify': '修改',
    'user.verify': '校驗',
    'user.deviceName': '設備名稱',
    'user.coAdministrator': '共同管理員',
    'user.selected': '已選',
    'user.allDevices': '所有裝置',
    'user.permissionAuth': '授權用於',
    'user.pwdPermission': '密碼權限',
    'user.allCommands': '所有裝置',
    'user.emerHint': '向設備發送警報消息。',
    'user.notificationHint': '將滾動消息發送到設備。',
    'user.announcementHint': '將視頻/圖片消息推送到設備。',
    'user.filePublishHint': '將文件發送到設備。',
    'user.powerStateHint': '開機後設置狀態顯示。',
    'user.androidStateHint': '設置Android頻道的可見性。',
    'user.wallpaperHint': '遠程更改設備牆紙。',
    'user.logoHint': '遠程更改開機動畫。',
    'user.input': '輸入值',
    'user.hours': '在{time}小時後到期',
    'user.days': '在{time}天后到期',
    'user.yearsDays': '在{year}年{days}天后到期',
    'user.years': '在{year}年后到期',

    'user.hoursLeft': '還剩{time}小時',
    'user.daysLeft': '還剩{time}天',
    'user.yearsDaysLeft': '還剩{year}年{days}天',
    'user.yearsLeft': '還剩{year}年',
    'user.addUser': '添加用戶',
    'user.allDevicesAndGroups': '所有組和設備',
    'user.enterRoleName': '在此處輸入角色名稱',
    'user.standard': '標準',
    'user.email.change.title1':'更改帳戶電子郵件',
    'user.email.change.tip1':'我們將向您發送驗證碼鏈接以更改帳戶電子郵件。',
    'user.email.change.title2':"驗證以繼續",
    "user.email.change.tip2":"需要幫忙？ 請聯繫{ val1 }",
    "user.email.change.title3":"更改帳戶電子郵件",
    "user.email.change.tip3":"更改組織管理員將註銷。 登錄密碼更改後保持不變。",
    "user.email.change.new.input.tip":"新郵件",
    "user.email.change.input.placeholder":"在此處輸入新電子郵件",
    "user.email.change.success.tip":"已成功更改帳戶電子郵件。",
    "user.email.change.fail.txt":"很抱歉，此電子郵件已被註冊。"
};
