export default {
    'userDetail.pwdPermission': '密碼權限',
    'userDetail.authCommands': '授權命令',
    'userDetail.manage': '管理',
    'userDetail.authCommandsSave': '授權命令已保存。',
    'userDetail.unableSave': '無法保存。',
    'userDetail.authDevicesSave': '授權命令已保存。',
    'userDetail.commandAuthFor': '的命令授權',
    'userDetail.device': '設備',
    'userDetail.label': '標籤',
    'userDetail.deviceAuthFor': '的設備授權',
    'userDetail.authDevices': '授權設備',
    'userDetail.deviceNo': '設備編號',
    'userDetail.authGroup': '授權組',
    'userDetail.roleCannotDel': '無法刪除角色。',
    'userDetail.userIsUsing': '使用此角色的用戶：',
    'userDetail.deleteRole': '刪除角色？',
    'userDetail.roleName': '角色名稱',
    'userDetail.customRole': '自定義角色',
    'userDetail.roleList': '角色列表',
    'userDetail.allDevicesAndGroup': '所有設備和組',
    'userDetail.createDeviceGroup': '創建設備組',
    'userDetail.deleteGroup': '從該組中刪除 {username}?',
    'userDetail.switchRoleHint': '確定要切換{role}角色嗎 ?',
    'userDetail.userInfomation': '用戶信息',
    'userDetail.switchRole': '切換角色',
    'userDetail.createSucc': '創建成功',
    'userDetail.operatorHint': '操作員 ：該用戶擁有對平台各個方面進行操作的完全權限。',
    'userDetail.viewerHint': `查看者：該用戶只能查看設備、用戶、註冊和申請信息。 無法對 Intune 進行更改。`,
    'userDetail.customHint': '自定義角色：創建具有自定義權限的角色。',
    'userDetail.roleNameExists': '角色名稱 {name} 已存在',
    'userDetail.createAGroup': '創建一個組',
};
