export default {
    'verify.error.invaild': '請輸入驗證碼。',
    'verify.error.emailIsUsed': '該E-mail已經取用。',
    'verify.error.emailNoFound': '找不到與此電子郵件帳戶。',
    'verify.error.expired': '抱歉，此代碼已過期。',
    'verify.error.error': '抱歉，此代碼不正確。',
    'verify.error.timeout':'抱歉，驗證碼已過期。',
    'verify.back': '返回',
    'verify.verifyEmail': '輸入驗證碼',
    'verify.backToSignUp': '返回註冊',
    'verify.unlockSuc': '帳戶已成功解鎖',
    'verify.createSuc': '創造成功！登錄…',
    'verify.protocol1': '輸入我們發送給的驗證碼 ',
    'verify.protocol2': '. 如果您沒有看到，請檢查您的垃圾郵件文件夾或提交的地址是否正確。',
    'verify.verify': '校驗',
    'verify.notReceivedTheCode': '還沒有收到驗證碼',
    'verify.sendItAgain': '再發一次',
    "verify.error.empty":"請輸入 6 位代碼。",
    'verify.enter.emil.tip':"輸入 6 位代碼",
    'verify.enter.email.placeholder':"輸入新電子郵件"
};
